# Partition Cell Types Deepclean

Perform deepcleaning removal of doublet clusters based on manual annotation

Relabel L3 AIFI cell type labels based on deepcleaning manual annotations

## Load libraries

In [1]:
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)
warnings.simplefilter(action='ignore', category=RuntimeWarning)

import concurrent.futures
from concurrent.futures import ThreadPoolExecutor
from datetime import date
import hisepy
import os
import pandas as pd
import re
import scanpy as sc
import scanpy.external as sce
import glob

In [108]:
out_dir = 'deepcleaned_output'
if not os.path.isdir(out_dir):
    os.makedirs(out_dir)

## Helper functions

These make it a bit simpler to cache and read in files from HISE

In [3]:
def cache_uuid_path(uuid):
    cache_path = '/home/jupyter/cache/{u}'.format(u = uuid)
    if not os.path.isdir(cache_path):
        hise_res = hisepy.reader.cache_files([uuid])
    filename = os.listdir(cache_path)[0]
    cache_file = '{p}/{f}'.format(p = cache_path, f = filename)
    return cache_file

In [4]:
def read_parquet_uuid(uuid):
    cache_file = cache_uuid_path(uuid)
    res = pd.read_parquet(cache_file)
    return res

In [5]:
def sort_adata_uuid(uuid, sort_cols = ['AIFI_L2', 'sample.sampleKitGuid']):
    cache_file = cache_uuid_path(uuid)
    adata = sc.read_h5ad(cache_file)
    obs = adata.obs
    obs = obs.sort_values(sort_cols)
    adata = adata[obs.index]
    adata.write_h5ad(cache_file)

This function will enable us to connect to our .h5ad files without loading the entire thing into memory. We'll then load only the cells that we want for each cell class to assemble them for writing. This should save us some overhead as we do our subsetting.

In [6]:
def read_adata_backed_uuid(uuid):
    cache_file = cache_uuid_path(uuid)
    res = sc.read_h5ad(cache_file, backed = 'r')
    return res

This function will remove Ig-related genes, which is recommended by Marla Glass for analysis of B cell subtypes

In [7]:
def remove_ig_genes(adata):
    igl_genes = [gene for gene in adata.var_names if gene.startswith("IGL")]
    igk_genes = [gene for gene in adata.var_names if gene.startswith("IGK")]
    ighc_genes = [gene for gene in adata.var_names if gene.startswith("IGH")]
    exl_genes = igl_genes + igk_genes + ighc_genes

    filtered_genes = [gene for gene in adata.var_names if gene not in exl_genes]
    adata = adata[:, filtered_genes]

    return adata

This function will apply a standard normalization, nearest neighbors, clustering, and UMAP process to our cell subsets:

In [8]:
def process_adata(adata, resolution = 2):
    
    # Keep a copy of the raw data
    adata = adata.raw.to_adata()
    adata.raw = adata

    print('Normalizing', end = "; ")
    # Normalize and log transform
    sc.pp.normalize_total(adata)
    sc.pp.log1p(adata)

    print('Finding HVGs', end = "; ")
    # Restrict downstream steps to variable genes
    sc.pp.highly_variable_genes(adata)
    adata = adata[:, adata.var_names[adata.var['highly_variable']]].copy()

    print('Scaling', end = "; ")
    # Scale variable genes
    sc.pp.scale(adata)

    print('PCA', end = "; ")
    # Run PCA
    sc.tl.pca(adata, svd_solver = 'arpack')
    
    print('Neighbors', end = "; ")
    # Find nearest neighbors
    sc.pp.neighbors(
        adata, 
        n_neighbors = 50,
        n_pcs = 30
    )

    print('Leiden', end = "; ")
    # Find clusters
    sc.tl.leiden(
        adata, 
        resolution = resolution, 
        key_added = 'leiden_{r}'.format(r = resolution),
        n_iterations = 2
    )

    print('UMAP', end = "; ")
    # Run UMAP
    sc.tl.umap(adata, min_dist = 0.05)
    
    print('Renormalizing')
    adata = adata.raw.to_adata()
    adata.raw = adata

    # Normalize and log transform
    sc.pp.normalize_total(adata)
    sc.pp.log1p(adata)
    
    return adata

In [9]:
def format_cell_type(cell_type):
    cell_type = re.sub('\\+', 'pos', cell_type)
    cell_type = re.sub('-', 'neg', cell_type)
    cell_type = re.sub(' ', '_', cell_type)
    return cell_type

In [10]:
def element_id(n = 3):
    import periodictable
    from random import randrange
    rand_el = []
    for i in range(n):
        el = randrange(0,118)
        rand_el.append(periodictable.elements[el].name)
    rand_str = '-'.join(rand_el)
    return rand_str

In [11]:
# make a function to find files
def get_filepaths_with_glob(root_path: str, file_regex: str):
    return glob.glob(os.path.join(root_path, file_regex))

In [31]:
# Define a function to extract the desired substring using regex
def extract_substring(path, pattern = r'up1_cluster_unharmonize_(.*?)_\d{4}-\d{2}-\d{2}\.h5ad'):
    #pattern = r'preRA_cluster_harmonize_(.*?)_\d{4}-\d{2}-\d{2}\.h5ad'
    match = re.search(pattern, path)
    if match:
        return match.group(1)
    return None

In [14]:
def read_anndata_files(file_tuples):
    """
    Read Anndata objects from H5AD files and store them in a dictionary with custom names.

    Parameters:
        file_tuples (list of tuples): List of tuples where each tuple contains filename and desired name.

    Returns:
        dict: Dictionary containing Anndata objects with custom names.
    """
    anndata_dict = {}
    for filename, name in file_tuples:
        anndata_obj = anndata.read_h5ad(filename)
        anndata_dict[name] = anndata_obj
    return anndata_dict

In [15]:
def reformat_cell_type(cell_type):
    '''convert cell type names read in from file back to original L3 labels'''
    cell_type = re.sub('pos', '+', cell_type)
    cell_type = re.sub('neg', '-', cell_type)
    cell_type = re.sub('_',' ', cell_type)
    return cell_type

## Identify files for use in HISE

In [16]:
search_id = 'sodium-gadolinium-silicon'

Retrieve files stored in our HISE project store

In [17]:
ps_df = hisepy.list_files_in_project_store('Dyna_IHandA')
ps_df = ps_df[['id', 'name']]

Filter for files from the previous notebook using our search_id

In [18]:
search_df = ps_df[ps_df['name'].str.contains(search_id)]
search_df = search_df.sort_values('name')

In [19]:
h5ad_df = search_df[search_df['name'].str.contains('.h5ad')]

In [20]:
h5ad_df

,id,name
218,7467d353-d8bf-467e-911c-4f759b83caf7,sodium-gadolinium-silicon/up1_cluster_unharmon...
219,eebab05a-bd3c-4921-8ae3-7345fac966c9,sodium-gadolinium-silicon/up1_cluster_unharmon...
220,410fc93a-f497-4ea4-81e2-fb8cbdc79a28,sodium-gadolinium-silicon/up1_cluster_unharmon...
221,6b18c554-64b3-43ae-9514-6ecd18c30f4d,sodium-gadolinium-silicon/up1_cluster_unharmon...
222,6f5b21ba-d98b-4003-bcf0-30e26a2cc2df,sodium-gadolinium-silicon/up1_cluster_unharmon...
...,...,...
213,e71668a5-f418-47d1-add1-40540e6b81d3,sodium-gadolinium-silicon/up1_cluster_unharmon...
214,4aa69351-6c4e-4527-83bd-b34e0e5127e6,sodium-gadolinium-silicon/up1_cluster_unharmon...
215,4a18d4bc-46a6-4946-8997-ef65d3e7144f,sodium-gadolinium-silicon/up1_cluster_unharmon...
216,04e4ecdd-4aeb-4f29-9326-94078d132295,sodium-gadolinium-silicon/up1_cluster_unharmon...
217,ee8e6ae5-848f-476c-b6cb-694dea40c889,sodium-gadolinium-silicon/up1_cluster_unharmon...

In [81]:
h5ad_uuids = {}
for i in range(h5ad_df.shape[0]):
    fn = h5ad_df['name'].tolist()[i]
    group_name = re.sub('.+pbmc_', '', fn)
    group_name = re.sub('_init.+', '', group_name)
    h5ad_uuids[group_name] = h5ad_df['id'].tolist()[i]

In [82]:
h5ad_uuids

{'sodium-gadolinium-silicon/up1_cluster_unharmonize_ASDC_2024-09-30.h5ad': '7467d353-d8bf-467e-911c-4f759b83caf7',
 'sodium-gadolinium-silicon/up1_cluster_unharmonize_Activated_memory_B_cell_2024-09-30.h5ad': 'eebab05a-bd3c-4921-8ae3-7345fac966c9',
 'sodium-gadolinium-silicon/up1_cluster_unharmonize_Adaptive_NK_cell_2024-09-30.h5ad': '410fc93a-f497-4ea4-81e2-fb8cbdc79a28',
 'sodium-gadolinium-silicon/up1_cluster_unharmonize_BaEoMaP_cell_2024-09-30.h5ad': '6b18c554-64b3-43ae-9514-6ecd18c30f4d',
 'sodium-gadolinium-silicon/up1_cluster_unharmonize_C1Qpos_CD16_monocyte_2024-09-30.h5ad': '6f5b21ba-d98b-4003-bcf0-30e26a2cc2df',
 'sodium-gadolinium-silicon/up1_cluster_unharmonize_CD14pos_cDC2_2024-09-30.h5ad': '153e45fc-e772-497c-9c4b-e986b7885f01',
 'sodium-gadolinium-silicon/up1_cluster_unharmonize_CD27neg_effector_B_cell_2024-09-30.h5ad': '9acd576f-2271-4ddb-b93e-20f0f63f87af',
 'sodium-gadolinium-silicon/up1_cluster_unharmonize_CD27pos_effector_B_cell_2024-09-30.h5ad': 'fcafe12f-3a15-4807-aaea-e93f08445d02',
 'sodium-gadolinium-silicon/up1_cluster_unharmonize_CD4_MAIT_2024-09-30.h5ad': '66122892-cddf-4c40-88b2-eaa53b7a6f4c',
 'sodium-gadolinium-silicon/up1_cluster_unharmonize_CD56bright_NK_cell_2024-09-30.h5ad': 'c9356501-0f48-4590-83ea-34da6dc72b56',
 'sodium-gadolinium-silicon/up1_cluster_unharmonize_CD8_MAIT_2024-09-30.h5ad': '0942c4af-20b7-4e2c-a822-a2e8f5044fff',
 'sodium-gadolinium-silicon/up1_cluster_unharmonize_CD8aa_2024-09-30.h5ad': 'e8dfca7a-e64e-469b-bcc8-6d32a291ffed',
 'sodium-gadolinium-silicon/up1_cluster_unharmonize_CD95_memory_B_cell_2024-09-30.h5ad': 'caad876a-5c80-4d5a-b245-c6c112b40912',
 'sodium-gadolinium-silicon/up1_cluster_unharmonize_CLP_cell_2024-09-30.h5ad': 'defe9422-db72-4210-b933-6f8919b001c5',
 'sodium-gadolinium-silicon/up1_cluster_unharmonize_CMP_cell_2024-09-30.h5ad': 'b2eec8c5-5bf9-47df-9428-ce26878f017d',
 'sodium-gadolinium-silicon/up1_cluster_unharmonize_CM_CD4_T_cell_2024-09-30.h5ad': 'e19e9467-2945-4ddc-ac95-1403cc0aee4b',
 'sodium-gadolinium-silicon/up1_cluster_unharmonize_CM_CD8_T_cell_2024-09-30.h5ad': 'c78d13d1-9580-4b4f-b212-11890ce22544',
 'sodium-gadolinium-silicon/up1_cluster_unharmonize_Core_CD14_monocyte_2024-09-30.h5ad': '60c73f54-4210-463f-9ced-920eb73bf924',
 'sodium-gadolinium-silicon/up1_cluster_unharmonize_Core_CD16_monocyte_2024-09-30.h5ad': 'b8d55475-5c20-4bdb-8980-edaae687d77d',
 'sodium-gadolinium-silicon/up1_cluster_unharmonize_Core_memory_B_cell_2024-09-30.h5ad': '27701eca-1fc6-4d14-9ed6-099e4d1b2668',
 'sodium-gadolinium-silicon/up1_cluster_unharmonize_Core_naive_B_cell_2024-09-30.h5ad': 'c5f11c26-23c5-4288-9200-176d57a52ddd',
 'sodium-gadolinium-silicon/up1_cluster_unharmonize_Core_naive_CD4_T_cell_2024-09-30.h5ad': 'f54f89d0-340d-47a9-bef2-ebcb854c6d72',
 'sodium-gadolinium-silicon/up1_cluster_unharmonize_Core_naive_CD8_T_cell_2024-09-30.h5ad': '7ae41ec4-d970-424c-bba3-f5c9debfb3df',
 'sodium-gadolinium-silicon/up1_cluster_unharmonize_DN_T_cell_2024-09-30.h5ad': '48602a6c-9cb1-491d-a2d6-1075bf989e86',
 'sodium-gadolinium-silicon/up1_cluster_unharmonize_Early_memory_B_cell_2024-09-30.h5ad': '91b76287-3228-48ac-9e7d-20e18db64d1c',
 'sodium-gadolinium-silicon/up1_cluster_unharmonize_Erythrocyte_2024-09-30.h5ad': 'cd41cf65-774e-4963-b7a9-58c1ece9b4e6',
 'sodium-gadolinium-silicon/up1_cluster_unharmonize_GZMBneg_CD27neg_EM_CD4_T_cell_2024-09-30.h5ad': 'e117a6f9-38fb-4b96-8286-9caa4a6cffeb',
 'sodium-gadolinium-silicon/up1_cluster_unharmonize_GZMBneg_CD27pos_EM_CD4_T_cell_2024-09-30.h5ad': '740e57fd-9f61-47d0-9aa2-a91ae11eb189',
 'sodium-gadolinium-silicon/up1_cluster_unharmonize_GZMBpos_Vd2_gdT_2024-09-30.h5ad': 'd4c7b35c-bd04-4369-877e-1aa7735c8075',
 'sodium-gadolinium-silicon/up1_cluster_unharmonize_GZMKneg_CD27pos_EM_CD8_T_cell_2024-09-30.h5ad': '2a2d7da2-9477-49bb-9875-75465025c82a',
 'sodium-gadolinium-silicon/up1_cluster_unharmonize_GZMKneg_CD56dim_NK_cell_2024-09-30.h5ad': '048f530d-b389-40be-928c-d2abb0edb733',
 'sodium-gadolinium-silicon/up1_cluster_unharmonize_GZMKpos_CD27pos_EM_CD8_T_cell_2024-09-30.h5ad': '23deb0fc-c3d3-46da-8ac6-32aade5fe560',
 'sodium-gadolinium-silicon/up1_cluster_unharmonize_GZMKpos_CD56dim_NK_cell_2024-09-30.h5ad': '6d336963-8f41-4f62-9e5c-fa0a37702593',
 'sodium-gadolinium-silicon/up1_cluster_unharmonize_GZMKpos_Vd2_gdT_2024-09-30.h5ad': '839619aa-e3b2-4547-bd90-4176964e382f',
 'sodium-gadolinium-silicon/up1_cluster_unharmonize_GZMKpos_memory_CD4_Treg_2024-09-30.h5ad': '6ba5d0c5-0491-443a-9203-f633736c450f',
 'sodium-gadolinium-silicon/up1_cluster_unharmonize_HLAnegDRhi_cDC2_2024-09-30.h5ad': 'c446f59a-37ce-4941-becb-532ba52692da',
 'sodium-gadolinium-silicon/up1_cluster_unharmonize_IL1Bpos_CD14_monocyte_2024-09-30.h5ad': 'b4f0e6f3-7029-4646-bb76-63e76d1a71f1',
 'sodium-gadolinium-silicon/up1_cluster_unharmonize_ILC_2024-09-30.h5ad': '073a6180-e0e1-4ea0-9b75-1b1f8fef0584',
 'sodium-gadolinium-silicon/up1_cluster_unharmonize_ISGpos_CD14_monocyte_2024-09-30.h5ad': '006eef48-c6be-4358-bf66-26e26c21b18d',
 'sodium-gadolinium-silicon/up1_cluster_unharmonize_ISGpos_CD16_monocyte_2024-09-30.h5ad': '202a9e27-0856-48b4-94fe-70ab09bd22b6',
 'sodium-gadolinium-silicon/up1_cluster_unharmonize_ISGpos_CD56dim_NK_cell_2024-09-30.h5ad': 'f759e068-c4b0-430d-9cd5-8d8575f08da4',
 'sodium-gadolinium-silicon/up1_cluster_unharmonize_ISGpos_MAIT_2024-09-30.h5ad': '8120ab33-5d51-4446-ba0c-463d63566062',
 'sodium-gadolinium-silicon/up1_cluster_unharmonize_ISGpos_cDC2_2024-09-30.h5ad': '13fb0746-6261-46e8-9a48-1c6f274fde7f',
 'sodium-gadolinium-silicon/up1_cluster_unharmonize_ISGpos_memory_CD4_T_cell_2024-09-30.h5ad': '2861547e-5606-4554-bcc2-da57161c2bf5',
 'sodium-gadolinium-silicon/up1_cluster_unharmonize_ISGpos_memory_CD8_T_cell_2024-09-30.h5ad': '02a52e24-afce-490b-8232-74f193db36a4',
 'sodium-gadolinium-silicon/up1_cluster_unharmonize_ISGpos_naive_B_cell_2024-09-30.h5ad': 'c49caec9-53ed-4219-be46-8c534408a10c',
 'sodium-gadolinium-silicon/up1_cluster_unharmonize_ISGpos_naive_CD4_T_cell_2024-09-30.h5ad': '64a0bcaf-68f3-48f2-a488-2571f42cbd4d',
 'sodium-gadolinium-silicon/up1_cluster_unharmonize_ISGpos_naive_CD8_T_cell_2024-09-30.h5ad': 'fb534804-80c4-4d46-b182-32bc7bdc80ca',
 'sodium-gadolinium-silicon/up1_cluster_unharmonize_Intermediate_monocyte_2024-09-30.h5ad': '5b2a49ea-96e6-4d96-962b-12a284cafe54',
 'sodium-gadolinium-silicon/up1_cluster_unharmonize_KLRB1pos_memory_CD4_Treg_2024-09-30.h5ad': 'd566c813-fdec-4583-b125-73d8ddc04648',
 'sodium-gadolinium-silicon/up1_cluster_unharmonize_KLRB1pos_memory_CD8_Treg_2024-09-30.h5ad': '40df01e8-82ce-4851-a67f-528e91d382c4',
 'sodium-gadolinium-silicon/up1_cluster_unharmonize_KLRF1neg_GZMBpos_CD27neg_EM_CD8_T_cell_2024-09-30.h5ad': '7f9d8e3d-e901-4f25-b9f9-49739e83dc3b',
 'sodium-gadolinium-silicon/up1_cluster_unharmonize_KLRF1neg_GZMBpos_CD27neg_memory_CD4_T_cell_2024-09-30.h5ad': '587352cf-bfa2-41e5-a19b-7ab531e253de',
 'sodium-gadolinium-silicon/up1_cluster_unharmonize_KLRF1neg_effector_Vd1_gdT_2024-09-30.h5ad': 'fb90a3e5-5a30-4e1b-ba66-f70807655747',
 'sodium-gadolinium-silicon/up1_cluster_unharmonize_KLRF1pos_GZMBpos_CD27neg_EM_CD8_T_cell_2024-09-30.h5ad': '8b2c297c-2e45-4345-9d99-f6a5f3211994',
 'sodium-gadolinium-silicon/up1_cluster_unharmonize_KLRF1pos_effector_Vd1_gdT_2024-09-30.h5ad': '506d1341-8654-49d2-8e77-572e53836b8c',
 'sodium-gadolinium-silicon/up1_cluster_unharmonize_Memory_CD4_Treg_2024-09-30.h5ad': '8a7e22a1-c9f1-4118-a238-4fb38791e87c',
 'sodium-gadolinium-silicon/up1_cluster_unharmonize_Naive_CD4_Treg_2024-09-30.h5ad': '23c65764-a97e-444f-95bc-d19cb643da42',
 'sodium-gadolinium-silicon/up1_cluster_unharmonize_Naive_Vd1_gdT_2024-09-30.h5ad': '09fb23a7-3641-4303-a228-2f1eebdfb7a1',
 'sodium-gadolinium-silicon/up1_cluster_unharmonize_Plasma_cell_2024-09-30.h5ad': 'df3092a2-cad7-463e-a462-fde70e9c475b',
 'sodium-gadolinium-silicon/up1_cluster_unharmonize_Platelet_2024-09-30.h5ad': 'ba92105f-2f48-419c-9319-d608db735049',
 'sodium-gadolinium-silicon/up1_cluster_unharmonize_Proliferating_NK_cell_2024-09-30.h5ad': 'cce6b185-ac84-4d63-a9ee-89060ba6390b',
 'sodium-gadolinium-silicon/up1_cluster_unharmonize_Proliferating_T_cell_2024-09-30.h5ad': 'c1c0be81-c6b1-4b8b-87f9-133301163297',
 'sodium-gadolinium-silicon/up1_cluster_unharmonize_SOX4pos_Vd1_gdT_2024-09-30.h5ad': '5eb0cadf-1e90-45fd-aeac-4f5b7a553711',
 'sodium-gadolinium-silicon/up1_cluster_unharmonize_SOX4pos_naive_CD4_T_cell_2024-09-30.h5ad': '09dd6805-0246-4fee-a3d1-ecc6b3cc3edd',
 'sodium-gadolinium-silicon/up1_cluster_unharmonize_SOX4pos_naive_CD8_T_cell_2024-09-30.h5ad': 'e71668a5-f418-47d1-add1-40540e6b81d3',
 'sodium-gadolinium-silicon/up1_cluster_unharmonize_Transitional_B_cell_2024-09-30.h5ad': '4aa69351-6c4e-4527-83bd-b34e0e5127e6',
 'sodium-gadolinium-silicon/up1_cluster_unharmonize_Type_2_polarized_memory_B_cell_2024-09-30.h5ad': '4a18d4bc-46a6-4946-8997-ef65d3e7144f',
 'sodium-gadolinium-silicon/up1_cluster_unharmonize_cDC1_2024-09-30.h5ad': '04e4ecdd-4aeb-4f29-9326-94078d132295',
 'sodium-gadolinium-silicon/up1_cluster_unharmonize_pDC_2024-09-30.h5ad': 'ee8e6ae5-848f-476c-b6cb-694dea40c889'}

In [83]:
len(h5ad_uuids)

70

In [76]:
#removing up1_cluster_unharmonize_KLRB1pos_memory_CD8_Treg_2024-09-30.h5ad from the list
h5ad_uuids.pop('sodium-gadolinium-silicon/up1_cluster_unharmonize_KLRB1pos_memory_CD8_Treg_2024-09-30.h5ad')
h5ad_uuids

{'sodium-gadolinium-silicon/up1_cluster_unharmonize_ASDC_2024-09-30.h5ad': '7467d353-d8bf-467e-911c-4f759b83caf7',
 'sodium-gadolinium-silicon/up1_cluster_unharmonize_Activated_memory_B_cell_2024-09-30.h5ad': 'eebab05a-bd3c-4921-8ae3-7345fac966c9',
 'sodium-gadolinium-silicon/up1_cluster_unharmonize_Adaptive_NK_cell_2024-09-30.h5ad': '410fc93a-f497-4ea4-81e2-fb8cbdc79a28',
 'sodium-gadolinium-silicon/up1_cluster_unharmonize_BaEoMaP_cell_2024-09-30.h5ad': '6b18c554-64b3-43ae-9514-6ecd18c30f4d',
 'sodium-gadolinium-silicon/up1_cluster_unharmonize_C1Qpos_CD16_monocyte_2024-09-30.h5ad': '6f5b21ba-d98b-4003-bcf0-30e26a2cc2df',
 'sodium-gadolinium-silicon/up1_cluster_unharmonize_CD14pos_cDC2_2024-09-30.h5ad': '153e45fc-e772-497c-9c4b-e986b7885f01',
 'sodium-gadolinium-silicon/up1_cluster_unharmonize_CD27neg_effector_B_cell_2024-09-30.h5ad': '9acd576f-2271-4ddb-b93e-20f0f63f87af',
 'sodium-gadolinium-silicon/up1_cluster_unharmonize_CD27pos_effector_B_cell_2024-09-30.h5ad': 'fcafe12f-3a15-4807-aaea-e93f08445d02',
 'sodium-gadolinium-silicon/up1_cluster_unharmonize_CD4_MAIT_2024-09-30.h5ad': '66122892-cddf-4c40-88b2-eaa53b7a6f4c',
 'sodium-gadolinium-silicon/up1_cluster_unharmonize_CD56bright_NK_cell_2024-09-30.h5ad': 'c9356501-0f48-4590-83ea-34da6dc72b56',
 'sodium-gadolinium-silicon/up1_cluster_unharmonize_CD8_MAIT_2024-09-30.h5ad': '0942c4af-20b7-4e2c-a822-a2e8f5044fff',
 'sodium-gadolinium-silicon/up1_cluster_unharmonize_CD8aa_2024-09-30.h5ad': 'e8dfca7a-e64e-469b-bcc8-6d32a291ffed',
 'sodium-gadolinium-silicon/up1_cluster_unharmonize_CD95_memory_B_cell_2024-09-30.h5ad': 'caad876a-5c80-4d5a-b245-c6c112b40912',
 'sodium-gadolinium-silicon/up1_cluster_unharmonize_CLP_cell_2024-09-30.h5ad': 'defe9422-db72-4210-b933-6f8919b001c5',
 'sodium-gadolinium-silicon/up1_cluster_unharmonize_CMP_cell_2024-09-30.h5ad': 'b2eec8c5-5bf9-47df-9428-ce26878f017d',
 'sodium-gadolinium-silicon/up1_cluster_unharmonize_CM_CD4_T_cell_2024-09-30.h5ad': 'e19e9467-2945-4ddc-ac95-1403cc0aee4b',
 'sodium-gadolinium-silicon/up1_cluster_unharmonize_CM_CD8_T_cell_2024-09-30.h5ad': 'c78d13d1-9580-4b4f-b212-11890ce22544',
 'sodium-gadolinium-silicon/up1_cluster_unharmonize_Core_CD14_monocyte_2024-09-30.h5ad': '60c73f54-4210-463f-9ced-920eb73bf924',
 'sodium-gadolinium-silicon/up1_cluster_unharmonize_Core_CD16_monocyte_2024-09-30.h5ad': 'b8d55475-5c20-4bdb-8980-edaae687d77d',
 'sodium-gadolinium-silicon/up1_cluster_unharmonize_Core_memory_B_cell_2024-09-30.h5ad': '27701eca-1fc6-4d14-9ed6-099e4d1b2668',
 'sodium-gadolinium-silicon/up1_cluster_unharmonize_Core_naive_B_cell_2024-09-30.h5ad': 'c5f11c26-23c5-4288-9200-176d57a52ddd',
 'sodium-gadolinium-silicon/up1_cluster_unharmonize_Core_naive_CD4_T_cell_2024-09-30.h5ad': 'f54f89d0-340d-47a9-bef2-ebcb854c6d72',
 'sodium-gadolinium-silicon/up1_cluster_unharmonize_Core_naive_CD8_T_cell_2024-09-30.h5ad': '7ae41ec4-d970-424c-bba3-f5c9debfb3df',
 'sodium-gadolinium-silicon/up1_cluster_unharmonize_DN_T_cell_2024-09-30.h5ad': '48602a6c-9cb1-491d-a2d6-1075bf989e86',
 'sodium-gadolinium-silicon/up1_cluster_unharmonize_Early_memory_B_cell_2024-09-30.h5ad': '91b76287-3228-48ac-9e7d-20e18db64d1c',
 'sodium-gadolinium-silicon/up1_cluster_unharmonize_Erythrocyte_2024-09-30.h5ad': 'cd41cf65-774e-4963-b7a9-58c1ece9b4e6',
 'sodium-gadolinium-silicon/up1_cluster_unharmonize_GZMBneg_CD27neg_EM_CD4_T_cell_2024-09-30.h5ad': 'e117a6f9-38fb-4b96-8286-9caa4a6cffeb',
 'sodium-gadolinium-silicon/up1_cluster_unharmonize_GZMBneg_CD27pos_EM_CD4_T_cell_2024-09-30.h5ad': '740e57fd-9f61-47d0-9aa2-a91ae11eb189',
 'sodium-gadolinium-silicon/up1_cluster_unharmonize_GZMBpos_Vd2_gdT_2024-09-30.h5ad': 'd4c7b35c-bd04-4369-877e-1aa7735c8075',
 'sodium-gadolinium-silicon/up1_cluster_unharmonize_GZMKneg_CD27pos_EM_CD8_T_cell_2024-09-30.h5ad': '2a2d7da2-9477-49bb-9875-75465025c82a',
 'sodium-gadolinium-silicon/up1_cluster_unharmonize_GZMKneg_CD56dim_NK_cell_2024-09-30.h5ad': '048f530d-b389-40be-928c-d2abb0edb733',
 'sodium-gadolinium-silicon/up1_cluster_unharmonize_GZMKpos_CD27pos_EM_CD8_T_cell_2024-09-30.h5ad': '23deb0fc-c3d3-46da-8ac6-32aade5fe560',
 'sodium-gadolinium-silicon/up1_cluster_unharmonize_GZMKpos_CD56dim_NK_cell_2024-09-30.h5ad': '6d336963-8f41-4f62-9e5c-fa0a37702593',
 'sodium-gadolinium-silicon/up1_cluster_unharmonize_GZMKpos_Vd2_gdT_2024-09-30.h5ad': '839619aa-e3b2-4547-bd90-4176964e382f',
 'sodium-gadolinium-silicon/up1_cluster_unharmonize_GZMKpos_memory_CD4_Treg_2024-09-30.h5ad': '6ba5d0c5-0491-443a-9203-f633736c450f',
 'sodium-gadolinium-silicon/up1_cluster_unharmonize_HLAnegDRhi_cDC2_2024-09-30.h5ad': 'c446f59a-37ce-4941-becb-532ba52692da',
 'sodium-gadolinium-silicon/up1_cluster_unharmonize_IL1Bpos_CD14_monocyte_2024-09-30.h5ad': 'b4f0e6f3-7029-4646-bb76-63e76d1a71f1',
 'sodium-gadolinium-silicon/up1_cluster_unharmonize_ILC_2024-09-30.h5ad': '073a6180-e0e1-4ea0-9b75-1b1f8fef0584',
 'sodium-gadolinium-silicon/up1_cluster_unharmonize_ISGpos_CD14_monocyte_2024-09-30.h5ad': '006eef48-c6be-4358-bf66-26e26c21b18d',
 'sodium-gadolinium-silicon/up1_cluster_unharmonize_ISGpos_CD16_monocyte_2024-09-30.h5ad': '202a9e27-0856-48b4-94fe-70ab09bd22b6',
 'sodium-gadolinium-silicon/up1_cluster_unharmonize_ISGpos_CD56dim_NK_cell_2024-09-30.h5ad': 'f759e068-c4b0-430d-9cd5-8d8575f08da4',
 'sodium-gadolinium-silicon/up1_cluster_unharmonize_ISGpos_MAIT_2024-09-30.h5ad': '8120ab33-5d51-4446-ba0c-463d63566062',
 'sodium-gadolinium-silicon/up1_cluster_unharmonize_ISGpos_cDC2_2024-09-30.h5ad': '13fb0746-6261-46e8-9a48-1c6f274fde7f',
 'sodium-gadolinium-silicon/up1_cluster_unharmonize_ISGpos_memory_CD4_T_cell_2024-09-30.h5ad': '2861547e-5606-4554-bcc2-da57161c2bf5',
 'sodium-gadolinium-silicon/up1_cluster_unharmonize_ISGpos_memory_CD8_T_cell_2024-09-30.h5ad': '02a52e24-afce-490b-8232-74f193db36a4',
 'sodium-gadolinium-silicon/up1_cluster_unharmonize_ISGpos_naive_B_cell_2024-09-30.h5ad': 'c49caec9-53ed-4219-be46-8c534408a10c',
 'sodium-gadolinium-silicon/up1_cluster_unharmonize_ISGpos_naive_CD4_T_cell_2024-09-30.h5ad': '64a0bcaf-68f3-48f2-a488-2571f42cbd4d',
 'sodium-gadolinium-silicon/up1_cluster_unharmonize_ISGpos_naive_CD8_T_cell_2024-09-30.h5ad': 'fb534804-80c4-4d46-b182-32bc7bdc80ca',
 'sodium-gadolinium-silicon/up1_cluster_unharmonize_Intermediate_monocyte_2024-09-30.h5ad': '5b2a49ea-96e6-4d96-962b-12a284cafe54',
 'sodium-gadolinium-silicon/up1_cluster_unharmonize_KLRB1pos_memory_CD4_Treg_2024-09-30.h5ad': 'd566c813-fdec-4583-b125-73d8ddc04648',
 'sodium-gadolinium-silicon/up1_cluster_unharmonize_KLRF1neg_GZMBpos_CD27neg_EM_CD8_T_cell_2024-09-30.h5ad': '7f9d8e3d-e901-4f25-b9f9-49739e83dc3b',
 'sodium-gadolinium-silicon/up1_cluster_unharmonize_KLRF1neg_GZMBpos_CD27neg_memory_CD4_T_cell_2024-09-30.h5ad': '587352cf-bfa2-41e5-a19b-7ab531e253de',
 'sodium-gadolinium-silicon/up1_cluster_unharmonize_KLRF1neg_effector_Vd1_gdT_2024-09-30.h5ad': 'fb90a3e5-5a30-4e1b-ba66-f70807655747',
 'sodium-gadolinium-silicon/up1_cluster_unharmonize_KLRF1pos_GZMBpos_CD27neg_EM_CD8_T_cell_2024-09-30.h5ad': '8b2c297c-2e45-4345-9d99-f6a5f3211994',
 'sodium-gadolinium-silicon/up1_cluster_unharmonize_KLRF1pos_effector_Vd1_gdT_2024-09-30.h5ad': '506d1341-8654-49d2-8e77-572e53836b8c',
 'sodium-gadolinium-silicon/up1_cluster_unharmonize_Memory_CD4_Treg_2024-09-30.h5ad': '8a7e22a1-c9f1-4118-a238-4fb38791e87c',
 'sodium-gadolinium-silicon/up1_cluster_unharmonize_Naive_CD4_Treg_2024-09-30.h5ad': '23c65764-a97e-444f-95bc-d19cb643da42',
 'sodium-gadolinium-silicon/up1_cluster_unharmonize_Naive_Vd1_gdT_2024-09-30.h5ad': '09fb23a7-3641-4303-a228-2f1eebdfb7a1',
 'sodium-gadolinium-silicon/up1_cluster_unharmonize_Plasma_cell_2024-09-30.h5ad': 'df3092a2-cad7-463e-a462-fde70e9c475b',
 'sodium-gadolinium-silicon/up1_cluster_unharmonize_Platelet_2024-09-30.h5ad': 'ba92105f-2f48-419c-9319-d608db735049',
 'sodium-gadolinium-silicon/up1_cluster_unharmonize_Proliferating_NK_cell_2024-09-30.h5ad': 'cce6b185-ac84-4d63-a9ee-89060ba6390b',
 'sodium-gadolinium-silicon/up1_cluster_unharmonize_Proliferating_T_cell_2024-09-30.h5ad': 'c1c0be81-c6b1-4b8b-87f9-133301163297',
 'sodium-gadolinium-silicon/up1_cluster_unharmonize_SOX4pos_Vd1_gdT_2024-09-30.h5ad': '5eb0cadf-1e90-45fd-aeac-4f5b7a553711',
 'sodium-gadolinium-silicon/up1_cluster_unharmonize_SOX4pos_naive_CD4_T_cell_2024-09-30.h5ad': '09dd6805-0246-4fee-a3d1-ecc6b3cc3edd',
 'sodium-gadolinium-silicon/up1_cluster_unharmonize_SOX4pos_naive_CD8_T_cell_2024-09-30.h5ad': 'e71668a5-f418-47d1-add1-40540e6b81d3',
 'sodium-gadolinium-silicon/up1_cluster_unharmonize_Transitional_B_cell_2024-09-30.h5ad': '4aa69351-6c4e-4527-83bd-b34e0e5127e6',
 'sodium-gadolinium-silicon/up1_cluster_unharmonize_Type_2_polarized_memory_B_cell_2024-09-30.h5ad': '4a18d4bc-46a6-4946-8997-ef65d3e7144f',
 'sodium-gadolinium-silicon/up1_cluster_unharmonize_cDC1_2024-09-30.h5ad': '04e4ecdd-4aeb-4f29-9326-94078d132295',
 'sodium-gadolinium-silicon/up1_cluster_unharmonize_pDC_2024-09-30.h5ad': 'ee8e6ae5-848f-476c-b6cb-694dea40c889'}

## Download and sort .h5ad files

Sorting the .h5ad files by AIFI_L2 will make reading each cell type much faster by placing cells of the same type next to each other in the sparse matrix.

In [80]:
# run once
for uuid in h5ad_uuids.values():
    sort_adata_uuid(uuid, sort_cols = ['AIFI_L3'])

downloading fileID: 7467d353-d8bf-467e-911c-4f759b83caf7
Files have been successfully downloaded!
downloading fileID: eebab05a-bd3c-4921-8ae3-7345fac966c9
Files have been successfully downloaded!
downloading fileID: 410fc93a-f497-4ea4-81e2-fb8cbdc79a28
Files have been successfully downloaded!
downloading fileID: 6b18c554-64b3-43ae-9514-6ecd18c30f4d
Files have been successfully downloaded!
downloading fileID: 6f5b21ba-d98b-4003-bcf0-30e26a2cc2df
Files have been successfully downloaded!
downloading fileID: 153e45fc-e772-497c-9c4b-e986b7885f01
Files have been successfully downloaded!
downloading fileID: 9acd576f-2271-4ddb-b93e-20f0f63f87af
Files have been successfully downloaded!
downloading fileID: fcafe12f-3a15-4807-aaea-e93f08445d02
Files have been successfully downloaded!
downloading fileID: 66122892-cddf-4c40-88b2-eaa53b7a6f4c
Files have been successfully downloaded!
downloading fileID: c9356501-0f48-4590-83ea-34da6dc72b56
Files have been successfully downloaded!
downloading fileID: 0942c4af-20b7-4e2c-a822-a2e8f5044fff
Files have been successfully downloaded!
downloading fileID: e8dfca7a-e64e-469b-bcc8-6d32a291ffed
Files have been successfully downloaded!
downloading fileID: caad876a-5c80-4d5a-b245-c6c112b40912
Files have been successfully downloaded!
downloading fileID: defe9422-db72-4210-b933-6f8919b001c5
Files have been successfully downloaded!
downloading fileID: b2eec8c5-5bf9-47df-9428-ce26878f017d
Files have been successfully downloaded!
downloading fileID: e19e9467-2945-4ddc-ac95-1403cc0aee4b
Files have been successfully downloaded!
downloading fileID: c78d13d1-9580-4b4f-b212-11890ce22544
Files have been successfully downloaded!
downloading fileID: 60c73f54-4210-463f-9ced-920eb73bf924
Files have been successfully downloaded!
downloading fileID: b8d55475-5c20-4bdb-8980-edaae687d77d
Files have been successfully downloaded!
downloading fileID: 27701eca-1fc6-4d14-9ed6-099e4d1b2668
Files have been successfully downloaded!
downloading fileID: c5f11c26-23c5-4288-9200-176d57a52ddd
Files have been successfully downloaded!
downloading fileID: f54f89d0-340d-47a9-bef2-ebcb854c6d72
Files have been successfully downloaded!
downloading fileID: cd41cf65-774e-4963-b7a9-58c1ece9b4e6
Files have been successfully downloaded!
downloading fileID: e117a6f9-38fb-4b96-8286-9caa4a6cffeb
Files have been successfully downloaded!
downloading fileID: 740e57fd-9f61-47d0-9aa2-a91ae11eb189
Files have been successfully downloaded!
downloading fileID: d4c7b35c-bd04-4369-877e-1aa7735c8075
Files have been successfully downloaded!
downloading fileID: 2a2d7da2-9477-49bb-9875-75465025c82a
Files have been successfully downloaded!
downloading fileID: 048f530d-b389-40be-928c-d2abb0edb733
Files have been successfully downloaded!
downloading fileID: 23deb0fc-c3d3-46da-8ac6-32aade5fe560
Files have been successfully downloaded!
downloading fileID: 6d336963-8f41-4f62-9e5c-fa0a37702593
Files have been successfully downloaded!
downloading fileID: 839619aa-e3b2-4547-bd90-4176964e382f
Files have been successfully downloaded!
downloading fileID: 6ba5d0c5-0491-443a-9203-f633736c450f
Files have been successfully downloaded!
downloading fileID: c446f59a-37ce-4941-becb-532ba52692da
Files have been successfully downloaded!
downloading fileID: b4f0e6f3-7029-4646-bb76-63e76d1a71f1
Files have been successfully downloaded!
downloading fileID: 073a6180-e0e1-4ea0-9b75-1b1f8fef0584
Files have been successfully downloaded!
downloading fileID: 006eef48-c6be-4358-bf66-26e26c21b18d
Files have been successfully downloaded!
downloading fileID: 202a9e27-0856-48b4-94fe-70ab09bd22b6
Files have been successfully downloaded!
downloading fileID: f759e068-c4b0-430d-9cd5-8d8575f08da4
Files have been successfully downloaded!
downloading fileID: 8120ab33-5d51-4446-ba0c-463d63566062
Files have been successfully downloaded!
downloading fileID: 13fb0746-6261-46e8-9a48-1c6f274fde7f
Files have been successfully downloaded!
downloading fileID: 2861547e-5606-4554-bcc2-da57161c2bf5
Files have been successfully downloaded!
downloading fileID: 02a52e24-afce-490b-8232-74f193db36a4
Files have been successfully downloaded!
downloading fileID: c49caec9-53ed-4219-be46-8c534408a10c
Files have been successfully downloaded!
downloading fileID: 64a0bcaf-68f3-48f2-a488-2571f42cbd4d
Files have been successfully downloaded!
downloading fileID: fb534804-80c4-4d46-b182-32bc7bdc80ca
Files have been successfully downloaded!
downloading fileID: 5b2a49ea-96e6-4d96-962b-12a284cafe54
Files have been successfully downloaded!
downloading fileID: d566c813-fdec-4583-b125-73d8ddc04648
Files have been successfully downloaded!
downloading fileID: 7f9d8e3d-e901-4f25-b9f9-49739e83dc3b
Files have been successfully downloaded!
downloading fileID: 587352cf-bfa2-41e5-a19b-7ab531e253de
Files have been successfully downloaded!
downloading fileID: fb90a3e5-5a30-4e1b-ba66-f70807655747
Files have been successfully downloaded!
downloading fileID: 8b2c297c-2e45-4345-9d99-f6a5f3211994
Files have been successfully downloaded!
downloading fileID: 506d1341-8654-49d2-8e77-572e53836b8c
Files have been successfully downloaded!
downloading fileID: 8a7e22a1-c9f1-4118-a238-4fb38791e87c
Files have been successfully downloaded!
downloading fileID: 23c65764-a97e-444f-95bc-d19cb643da42
Files have been successfully downloaded!
downloading fileID: 09fb23a7-3641-4303-a228-2f1eebdfb7a1
Files have been successfully downloaded!
downloading fileID: df3092a2-cad7-463e-a462-fde70e9c475b
Files have been successfully downloaded!
downloading fileID: ba92105f-2f48-419c-9319-d608db735049
Files have been successfully downloaded!
downloading fileID: cce6b185-ac84-4d63-a9ee-89060ba6390b
Files have been successfully downloaded!
downloading fileID: c1c0be81-c6b1-4b8b-87f9-133301163297
Files have been successfully downloaded!
downloading fileID: 5eb0cadf-1e90-45fd-aeac-4f5b7a553711
Files have been successfully downloaded!
downloading fileID: 09dd6805-0246-4fee-a3d1-ecc6b3cc3edd
Files have been successfully downloaded!
downloading fileID: e71668a5-f418-47d1-add1-40540e6b81d3
Files have been successfully downloaded!
downloading fileID: 4aa69351-6c4e-4527-83bd-b34e0e5127e6
Files have been successfully downloaded!
downloading fileID: 4a18d4bc-46a6-4946-8997-ef65d3e7144f
Files have been successfully downloaded!
downloading fileID: 04e4ecdd-4aeb-4f29-9326-94078d132295
Files have been successfully downloaded!
downloading fileID: ee8e6ae5-848f-476c-b6cb-694dea40c889
Files have been successfully downloaded!

## Open connections to .h5ad files

Now that they're sorted, we can open these files with on-disk backing so we don't have to read the entire file at once.

## Process files

In [84]:
input_path = "/home/jupyter/certpro_up1/unharmonized_output/"

In [85]:
### read in processed leiden adata
filenames = get_filepaths_with_glob(input_path, "up1_cluster_unharmonize_*.h5ad")  
filenames[:5]
len(filenames)

70

In [86]:
### extract cell types
# Apply the function to each filename in the list using list comprehension
cell_types = [extract_substring(path) for path in filenames]
cell_types[:5]

['Core_CD14_monocyte',
 'KLRF1neg_GZMBpos_CD27neg_EM_CD8_T_cell',
 'CD14pos_cDC2',
 'GZMKpos_CD27pos_EM_CD8_T_cell',
 'ISGpos_MAIT']

In [87]:
file_dict = dict(zip(cell_types, filenames))
list(file_dict.items())[:10]

[('Core_CD14_monocyte',
  '/home/jupyter/certpro_up1/unharmonized_output/up1_cluster_unharmonize_Core_CD14_monocyte_2024-09-30.h5ad'),
 ('KLRF1neg_GZMBpos_CD27neg_EM_CD8_T_cell',
  '/home/jupyter/certpro_up1/unharmonized_output/up1_cluster_unharmonize_KLRF1neg_GZMBpos_CD27neg_EM_CD8_T_cell_2024-09-30.h5ad'),
 ('CD14pos_cDC2',
  '/home/jupyter/certpro_up1/unharmonized_output/up1_cluster_unharmonize_CD14pos_cDC2_2024-09-30.h5ad'),
 ('GZMKpos_CD27pos_EM_CD8_T_cell',
  '/home/jupyter/certpro_up1/unharmonized_output/up1_cluster_unharmonize_GZMKpos_CD27pos_EM_CD8_T_cell_2024-09-30.h5ad'),
 ('ISGpos_MAIT',
  '/home/jupyter/certpro_up1/unharmonized_output/up1_cluster_unharmonize_ISGpos_MAIT_2024-09-30.h5ad'),
 ('CD56bright_NK_cell',
  '/home/jupyter/certpro_up1/unharmonized_output/up1_cluster_unharmonize_CD56bright_NK_cell_2024-09-30.h5ad'),
 ('CM_CD8_T_cell',
  '/home/jupyter/certpro_up1/unharmonized_output/up1_cluster_unharmonize_CM_CD8_T_cell_2024-09-30.h5ad'),
 ('SOX4pos_naive_CD4_T_cell',
  '/home/jupyter/certpro_up1/unharmonized_output/up1_cluster_unharmonize_SOX4pos_naive_CD4_T_cell_2024-09-30.h5ad'),
 ('CMP_cell',
  '/home/jupyter/certpro_up1/unharmonized_output/up1_cluster_unharmonize_CMP_cell_2024-09-30.h5ad'),
 ('IL1Bpos_CD14_monocyte',
  '/home/jupyter/certpro_up1/unharmonized_output/up1_cluster_unharmonize_IL1Bpos_CD14_monocyte_2024-09-30.h5ad')]

In [88]:
#### read in doublet csv
doublet_df = pd.read_csv("/home/jupyter/certpro_up1/final_UP1_doublet - Sheet1-2.csv")
### select only cell type and doublet leiden
doublet_df = doublet_df[["AIFI_L3", "leiden (cluster to be removed)"]]
# reformat cell types
doublet_df['AIFI_L3'] = [format_cell_type(cell_type) for cell_type in doublet_df['AIFI_L3']]
doublet_df

                           AIFI_L3 leiden (cluster to be removed)
0                             ASDC                          12,15
1          Activated_memory_B_cell                            0,8
2                 Adaptive_NK_cell                 14,19,20,21,17
3             C1Qpos_CD16_monocyte                  1,11,16,13,18
4                     CD14pos_cDC2               1,15,20,22,23,21
..                             ...                            ...
61        SOX4pos_naive_CD8_T_cell                       15,18,13
62             Transitional_B_cell              20,23,22,21,24,14
63  Type_2_polarized_memory_B_cell                           17,8
64                            cDC1                     15,10,9,16
65                             pDC           15,17,20,22,21,23,13

[66 rows x 2 columns]

In [89]:
doublet_df['AIFI_L3']

0                               ASDC
1            Activated_memory_B_cell
2                   Adaptive_NK_cell
3               C1Qpos_CD16_monocyte
4                       CD14pos_cDC2
                   ...
61          SOX4pos_naive_CD8_T_cell
62               Transitional_B_cell
63    Type_2_polarized_memory_B_cell
64                              cDC1
65                               pDC
Name: AIFI_L3, Length: 66, dtype: object

## Store doublet clusters

In [90]:
# Convert the DataFrame to a dictionary
doublet_cluster_dict = {}

for index, row in doublet_df.iterrows():
    key = row['AIFI_L3']
    # Check if the value is not NaN or None
    if pd.notna(row['leiden (cluster to be removed)']):
        values = row['leiden (cluster to be removed)'].split(',')
    else:
        values = []
    doublet_cluster_dict[key] = values

#print(doublet_cluster_dict)

In [91]:
doublet_cluster_dict

{'ASDC': ['12', '15'],
 'Activated_memory_B_cell': ['0', '8'],
 'Adaptive_NK_cell': ['14', '19', '20', '21', '17'],
 'C1Qpos_CD16_monocyte': ['1', '11', '16', '13', '18'],
 'CD14pos_cDC2': ['1', '15', '20', '22', '23', '21'],
 'CD27pos_effector_B_cell': ['17', '21', '20'],
 'CD27neg_effector_B_cell': ['15', '17', '22', '14', '19'],
 'CD4_MAIT': ['13', '16', '4', '2', '9', '7', '16', '3', '6', '15', '17', '5'],
 'CD56bright_NK_cell': ['7', '21', '22', '24', '26'],
 'CD8_MAIT': ['19', '21', '12'],
 'CD95_memory_B_cell': ['8', '13', '15'],
 'CLP_cell': ['8', '0', '5'],
 'CMP_cell': ['7'],
 'CM_CD4_T_cell': ['18', '20', '22', '24'],
 'CM_CD8_T_cell': ['25'],
 'Core_CD14_monocyte': ['19', '20', '28', '30'],
 'Core_CD16_monocyte': ['14', '15', '17', '19'],
 'Core_memory_B_cell': ['15', '19'],
 'Core_naive_B_cell': ['17', '21'],
 'Core_naive_CD4_T_cell': ['16', '17', '18', '23', '21', '22'],
 'Core_naive_CD8_T_cell': ['16'],
 'DN_T_cell': ['21', '18', '20'],
 'Early_memory_B_cell': ['3', '16', '26'],
 'Erythrocyte': ['0',
  '1',
  '2',
  '3',
  '5',
  '6',
  '7',
  '8',
  '9',
  '10',
  '11',
  '13',
  '14',
  '15',
  '16',
  '17',
  '18',
  '19',
  '20',
  '21',
  '22',
  '23'],
 'GZMBpos_Vd2_gdT': ['19', '22'],
 'GZMBneg_CD27pos_EM_CD4_T_cell': ['19'],
 'GZMBneg_CD27neg_EM_CD4_T_cell': ['16', '21', '22', '23', '24'],
 'GZMKpos_CD27pos_EM_CD8_T_cell': ['22', '18', '21'],
 'GZMKpos_CD56dim_NK_cell': ['7', '18', '22', '20'],
 'GZMKpos_Vd2_gdT': ['14', '19'],
 'GZMKneg_CD27pos_EM_CD8_T_cell': ['19'],
 'GZMKneg_CD56dim_NK_cell': ['18', '20', '24', '25'],
 'HLAnegDRhi_cDC2': ['23', '25', '14', '9', '22'],
 'IL1Bpos_CD14_monocyte': ['32', '28', '18', '6', '15', '30'],
 'ILC': ['17'],
 'ISGpos_CD14_monocyte': ['4', '16', '20', '21', '23'],
 'ISGpos_CD16_monocyte': ['1', '3', '7', '15', '17', '18', '19'],
 'ISGpos_CD56dim_NK_cell': ['6', '7', '16', '17', '19', '20', '1', '13'],
 'ISGpos_MAIT': ['14', '16', '17'],
 'ISGpos_cDC2': ['2', '14', '16', '17'],
 'ISGpos_memory_CD4_T_cell': ['24', '15', '19', '22'],
 'ISGpos_memory_CD8_T_cell': ['16'],
 'ISGpos_naive_B_cell': ['11', '16', '20', '21', '19'],
 'ISGpos_naive_CD4_T_cell': ['20', '21'],
 'ISGpos_naive_CD8_T_cell': ['15'],
 'Intermediate_monocyte': ['1', '3', '18'],
 'KLRB1pos_memory_CD4_Treg': ['17'],
 'KLRF1pos_GZMBpos_CD27neg_EM_CD8_T_cell': ['18', '22', '16'],
 'KLRF1pos_effector_Vd1_gdT': ['17', '19', '21', '16'],
 'KLRF1neg_GZMBpos_CD27neg_EM_CD8_T_cell': ['25', '26', '27', '24'],
 'KLRF1neg_GZMBpos_CD27neg_memory_CD4_T_cell': ['17'],
 'KLRF1neg_effector_Vd1_gdT': ['9', '17', '19', '20'],
 'Memory_CD4_Treg': ['19', '7'],
 'Naive_CD4_Treg': ['17', '18'],
 'Naive_Vd1_gdT': ['19'],
 'Plasma_cell': ['23', '13', '18', '10'],
 'Platelet': ['18', '10', '7', '16', '17', '13', '14'],
 'Proliferating_NK_cell': ['21', '20', '10', '8'],
 'Proliferating_T_cell': ['13', '22', '25'],
 'SOX4pos_Vd1_gdT': ['19', '20', '21'],
 'SOX4pos_naive_CD4_T_cell': ['14', '16'],
 'SOX4pos_naive_CD8_T_cell': ['15', '18', '13'],
 'Transitional_B_cell': ['20', '23', '22', '21', '24', '14'],
 'Type_2_polarized_memory_B_cell': ['17', '8'],
 'cDC1': ['15', '10', '9', '16'],
 'pDC': ['15', '17', '20', '22', '21', '23', '13']}

## Store Relabel Cell Type Clusters

Store list of leiden clusters to relabel to L3 cell types

In [162]:
relabel_df = pd.read_csv("../data/relabel_deepclean_sheet_06_11_24.csv")
relabel_df = relabel_df[['AIFI_L3', 'relabel_name','clusters']]
# reformat cell types
relabel_df['AIFI_L3'] = [format_cell_type(cell_type) for cell_type in relabel_df['AIFI_L3']]
# filter by cell types that need to be relabeled and clusters only
relabel_df = relabel_df.dropna(thresh= 2)
relabel_df

,AIFI_L3,relabel_name,clusters
0,ASDC,ASDC_uk1_B,"0,1,7"
1,Activated_memory_B_cell,Activated memory B cell_uk1,1
2,Adaptive_NK_cell,Adaptive NK cell_uk1_T,"7,11,20,21"
14,CM_CD4_T_cell,"CM CD4 T cell_uk1_CD8,CM CD4 T cell_uk2","12,17"
24,Early_memory_B_cell,Early memory B cell_uk1,"12,13"
27,GZMBneg_CD27pos_EM_CD4_T_cell,GZMB- CD27+ EM CD4 T cell_uk1_CD8,15
28,GZMBneg_CD27neg_EM_CD4_T_cell,GZMB- CD27- EM CD4 T cell_uk1_CD8,6
29,GZMKpos_CD27pos_EM_CD8_T_cell,GZMK+ CD27+ EM CD8 T cell_uk1_gdt,"10,15,17"
37,ILC,ILC_uk1,2
43,ISGpos_memory_CD4_T_cell,ISG+ memory CD4 T cell_uk1_CD8,15
51,KLRF1pos_GZMBpos_CD27neg_EM_CD8_T_cell,"[KLRF1+_GZMB+_CD27-_EM_CD8_uk1],[KLRF1+_GZMB+_...","[30],[23],[1,4,15,16]"
53,KLRF1neg_GZMBpos_CD27neg_EM_CD8_T_cell,KLRF1-_GZMB+_CD27-_EM_CD8_uk1,20
54,KLRF1neg_GZMBpos_CD27neg_memory_CD4_T_cell,KLRF1-_GZMB+_CD27-_mem_CD4_uk1,"5,6"
63,Proliferating_T_cell,Prolif_T_uk1,16
68,Type_2_polarized_memory_B_cell,T2MBC_uk1,19

In [98]:
### remove cell types with more than one names to be relabeled
multiple_relabel_cond = relabel_df['AIFI_L3'].str.contains('|'.join(['CM_CD4_T_cell', 'KLRF1pos_GZMBpos_CD27neg_EM_CD8_T_cell']))
relabel_df_single = relabel_df[~multiple_relabel_cond]
relabel_df_multi = relabel_df[multiple_relabel_cond]

In [99]:
relabel_df_single

,AIFI_L3,relabel_name,clusters
0,ASDC,ASDC_uk1_B,"0,1,7"
1,Activated_memory_B_cell,Activated memory B cell_uk1,1
2,Adaptive_NK_cell,Adaptive NK cell_uk1_T,"7,11,20,21"
24,Early_memory_B_cell,Early memory B cell_uk1,"12,13"
27,GZMBneg_CD27pos_EM_CD4_T_cell,GZMB- CD27+ EM CD4 T cell_uk1_CD8,15
28,GZMBneg_CD27neg_EM_CD4_T_cell,GZMB- CD27- EM CD4 T cell_uk1_CD8,6
29,GZMKpos_CD27pos_EM_CD8_T_cell,GZMK+ CD27+ EM CD8 T cell_uk1_gdt,"10,15,17"
37,ILC,ILC_uk1,2
43,ISGpos_memory_CD4_T_cell,ISG+ memory CD4 T cell_uk1_CD8,15
53,KLRF1neg_GZMBpos_CD27neg_EM_CD8_T_cell,KLRF1-_GZMB+_CD27-_EM_CD8_uk1,20
54,KLRF1neg_GZMBpos_CD27neg_memory_CD4_T_cell,KLRF1-_GZMB+_CD27-_mem_CD4_uk1,"5,6"
63,Proliferating_T_cell,Prolif_T_uk1,16
68,Type_2_polarized_memory_B_cell,T2MBC_uk1,19

In [100]:
relabel_df_multi

,AIFI_L3,relabel_name,clusters
14,CM_CD4_T_cell,"CM CD4 T cell_uk1_CD8,CM CD4 T cell_uk2","12,17"
51,KLRF1pos_GZMBpos_CD27neg_EM_CD8_T_cell,"[KLRF1+_GZMB+_CD27-_EM_CD8_uk1],[KLRF1+_GZMB+_...","[30],[23],[1,4,15,16]"

In [83]:
# Create the dictionary
relabel_cluster_dict = {}

for index, row in relabel_df_single.iterrows():
    key = row['AIFI_L3']
    # parse clusters that have multiple relabel name within same cell types
    cl = row['clusters'].split(',')
    parsed_cl =  [cluster.strip('[]').split(',') for cluster in cl]
    value = (row['relabel_name'].split(','), cl)
    relabel_cluster_dict[key] = value

In [84]:
print(relabel_cluster_dict)

{'ASDC': (['ASDC_uk1_B'], ['0', '1', '7']), 'Activated_memory_B_cell': (['Activated memory B cell_uk1'], ['1']), 'Adaptive_NK_cell': (['Adaptive NK cell_uk1_T'], ['7', '11', '20', '21']), 'Early_memory_B_cell': (['Early memory B cell_uk1'], ['12', '13']), 'GZMBneg_CD27pos_EM_CD4_T_cell': (['GZMB- CD27+ EM CD4 T cell_uk1_CD8'], ['15']), 'GZMBneg_CD27neg_EM_CD4_T_cell': (['GZMB- CD27- EM CD4 T cell_uk1_CD8'], ['6']), 'GZMKpos_CD27pos_EM_CD8_T_cell': (['GZMK+ CD27+ EM CD8 T cell_uk1_gdt'], ['10', '15', '17']), 'ILC': (['ILC_uk1'], ['2']), 'ISGpos_memory_CD4_T_cell': (['ISG+ memory CD4 T cell_uk1_CD8'], ['15']), 'KLRF1neg_GZMBpos_CD27neg_EM_CD8_T_cell': (['KLRF1-_GZMB+_CD27-_EM_CD8_uk1'], ['20']), 'KLRF1neg_GZMBpos_CD27neg_memory_CD4_T_cell': (['KLRF1-_GZMB+_CD27-_mem_CD4_uk1'], ['5', '6']), 'Proliferating_T_cell': (['Prolif_T_uk1'], ['16']), 'Type_2_polarized_memory_B_cell': (['T2MBC_uk1'], ['19'])}

In [150]:
### manually add cell types with multiple renaming labels to dictionary
multi_relabel_dict = {
    'KLRF1pos_GZMBpos_CD27neg_EM_CD8_T_cell': (
        ['KLRF1+_GZMB+_CD27-_EM_CD8_uk1', 'KLRF1+_GZMB+_CD27-_EM_CD8_uk2', 'KLRF1+GZMB+_CD27-_EM_CD8_uk3'],
        [['30'], ['23'], ['1','4','15','16']]),
    'CM_CD4_T_cell': (
        ['CM CD4 T cell_uk1_CD8', 'CM CD4 T cell_uk2'], 
        [['12'],['17']])}
multi_relabel_dict

{'KLRF1pos_GZMBpos_CD27neg_EM_CD8_T_cell': (['KLRF1+_GZMB+_CD27-_EM_CD8_uk1',
   'KLRF1+_GZMB+_CD27-_EM_CD8_uk2',
   'KLRF1+GZMB+_CD27-_EM_CD8_uk3'],
  [['30'], ['23'], ['1', '4', '15', '16']]),
 'CM_CD4_T_cell': (['CM CD4 T cell_uk1_CD8', 'CM CD4 T cell_uk2'],
  [['12'], ['17']])}

## Process Each Cell Types

In [122]:
### create unit test: cell type with no renaming, cell type with 1 rename and cell type with multiple rename
#subfile_dict = dict((k, file_dict[k]) for k in ('CD4_MAIT', 'ASDC', 'CM_CD4_T_cell'))
subfile_dict = dict((k, file_dict[k]) for k in ('CD4_MAIT', 'ASDC', 'CM_CD4_T_cell'))

subfile_dict

{'CD4_MAIT': '../../05-clustering/scripts/output/preRA_cluster_harmonize_CD4_MAIT_2024-05-25.h5ad',
 'ASDC': '../../05-clustering/scripts/output/preRA_cluster_harmonize_ASDC_2024-05-25.h5ad',
 'CM_CD4_T_cell': '../../05-clustering/scripts/output/preRA_cluster_harmonize_CM_CD4_T_cell_2024-05-26.h5ad'}

In [92]:
out_files = []
out_files

[]

In [94]:
# Initialize out_files as a list at the beginning
out_files = []

# Initialize a list to store each meta DataFrame
meta_list = []

# Iterate over the dictionary containing file names
for label, file in file_dict.items():
    print("Key:", label)
    print("Value:", file)

    # Read the h5ad file
    adata = sc.read_h5ad(file)
    print(adata)

    # Subset doublet dictionary by current cell types
    doublet_clust = doublet_cluster_dict.get(label, [])
    print('Doublet clusters: ' + str(doublet_clust))

    #### Label doublets in metadata
    if len(doublet_clust) == 0:
        print("The list is empty")
        adata.obs['doublets_manual'] = 'no'
    else:
        adata.obs['doublets_manual'] = ['yes' if leiden in doublet_clust else 'no' for leiden in adata.obs['leiden_2']]
    
    # Check the distribution of doublets
    print(pd.crosstab(adata.obs['doublets_manual'], adata.obs['leiden_2']))

    ### Export doublet metadata
    meta = adata.obs[['barcodes', 'batch_id', 'cell_name', 'sample.sampleKitGuid','subject.subjectGuid', 'sample.visitName', 'pbmc_sample_id', 'AIFI_L3', 'leiden_2','doublets_manual']]
    meta.head()

    # Append the current meta DataFrame to the list
    meta_list.append(meta)
    
    # Export the metadata to CSV
    meta.to_csv('./deepcleaned_output/up1_doublet_meta_{c}_{d}.csv'.format(
        c=label,
        d=date.today()
    ))

    # Subset anndata by singlets only
    adata_subset = adata[adata.obs['doublets_manual'] == 'no']
    print("Subsetted cells to: " + str(adata.shape))

    # Export the cleaned anndata
    print('Saving processed data')
    out_file = './deepcleaned_output/up1_deepcleaned_{c}_{d}.h5ad'.format(
        c=label,
        d=date.today()
    )
    adata_subset.write_h5ad(out_file)

    # Append to the output file list
    out_files.append(out_file)

Key: Core_CD14_monocyte
Value: /home/jupyter/certpro_up1/unharmonized_output/up1_cluster_unharmonize_Core_CD14_monocyte_2024-09-30.h5ad
AnnData object with n_obs × n_vars = 224790 × 33538
    obs: 'barcodes', 'batch_id', 'cell_name', 'cell_uuid', 'chip_id', 'hto_barcode', 'hto_category', 'n_genes', 'n_mito_umis', 'n_reads', 'n_umis', 'original_barcodes', 'pbmc_sample_id', 'pool_id', 'well_id', 'sample.sampleKitGuid', 'cohort.cohortGuid', 'subject.subjectGuid', 'subject.biologicalSex', 'subject.race', 'subject.ethnicity', 'subject.birthYear', 'sample.visitName', 'sample.drawDate', 'specimens.specimenGuid', 'specimens.specimenType', 'file.id', 'file.batchID', 'subset_grp', 'predicted_doublet', 'doublet_score', 'AIFI_L1', 'AIFI_L1_score', 'AIFI_L2', 'AIFI_L2_score', 'AIFI_L3', 'AIFI_L3_score', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mito', 'log1p_total_counts_mito', 'pct_counts_mito', 'leiden_2'
    uns: 'hvg', 'leiden', 'log1p', 'neighbors', 'pca', 'rank_genes_groups', 'umap'
    obsm: 'X_pca', 'X_umap'
    obsp: 'connectivities', 'distances'
Doublet clusters: ['19', '20', '28', '30']
leiden_2             0      1      2      3      4      5      6      7  \
doublets_manual
no               13685  13255  12937  12893  12650  12217  12134  10775
yes                  0      0      0      0      0      0      0      0

leiden_2             8     9  ...    21    22    23    24    25    26    27  \
doublets_manual               ...
no               10168  9996  ...  4887  4044  3359  3278  3030  2272  1683
yes                  0     0  ...     0     0     0     0     0     0     0

leiden_2          28   29   30
doublets_manual
no                 0  957    0
yes              965    0  334

[2 rows x 31 columns]
Subsetted cells to: (224790, 33538)
Saving processed data

/opt/conda/lib/python3.10/site-packages/anndata/_core/anndata.py:1292: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c

Key: KLRF1neg_GZMBpos_CD27neg_EM_CD8_T_cell
Value: /home/jupyter/certpro_up1/unharmonized_output/up1_cluster_unharmonize_KLRF1neg_GZMBpos_CD27neg_EM_CD8_T_cell_2024-09-30.h5ad
AnnData object with n_obs × n_vars = 90994 × 33538
    obs: 'barcodes', 'batch_id', 'cell_name', 'cell_uuid', 'chip_id', 'hto_barcode', 'hto_category', 'n_genes', 'n_mito_umis', 'n_reads', 'n_umis', 'original_barcodes', 'pbmc_sample_id', 'pool_id', 'well_id', 'sample.sampleKitGuid', 'cohort.cohortGuid', 'subject.subjectGuid', 'subject.biologicalSex', 'subject.race', 'subject.ethnicity', 'subject.birthYear', 'sample.visitName', 'sample.drawDate', 'specimens.specimenGuid', 'specimens.specimenType', 'file.id', 'file.batchID', 'subset_grp', 'predicted_doublet', 'doublet_score', 'AIFI_L1', 'AIFI_L1_score', 'AIFI_L2', 'AIFI_L2_score', 'AIFI_L3', 'AIFI_L3_score', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mito', 'log1p_total_counts_mito', 'pct_counts_mito', 'leiden_2'
    uns: 'hvg', 'leiden', 'log1p', 'neighbors', 'pca', 'rank_genes_groups', 'umap'
    obsm: 'X_pca', 'X_umap'
    obsp: 'connectivities', 'distances'
Doublet clusters: ['25', '26', '27', '24']
leiden_2            0     1     2     3     4     5     6     7     8     9  \
doublets_manual
no               7795  7660  6983  6775  5326  5239  4994  4909  4331  4198
yes                 0     0     0     0     0     0     0     0     0     0

leiden_2         ...    18    19    20    21   22   23   24   25   26   27
doublets_manual  ...
no               ...  1739  1734  1409  1115  842  734    0    0    0    0
yes              ...     0     0     0     0    0    0  643  547  533  280

[2 rows x 28 columns]
Subsetted cells to: (90994, 33538)
Saving processed data

/opt/conda/lib/python3.10/site-packages/anndata/_core/anndata.py:1292: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c

Key: CD14pos_cDC2
Value: /home/jupyter/certpro_up1/unharmonized_output/up1_cluster_unharmonize_CD14pos_cDC2_2024-09-30.h5ad
AnnData object with n_obs × n_vars = 9288 × 33538
    obs: 'barcodes', 'batch_id', 'cell_name', 'cell_uuid', 'chip_id', 'hto_barcode', 'hto_category', 'n_genes', 'n_mito_umis', 'n_reads', 'n_umis', 'original_barcodes', 'pbmc_sample_id', 'pool_id', 'well_id', 'sample.sampleKitGuid', 'cohort.cohortGuid', 'subject.subjectGuid', 'subject.biologicalSex', 'subject.race', 'subject.ethnicity', 'subject.birthYear', 'sample.visitName', 'sample.drawDate', 'specimens.specimenGuid', 'specimens.specimenType', 'file.id', 'file.batchID', 'subset_grp', 'predicted_doublet', 'doublet_score', 'AIFI_L1', 'AIFI_L1_score', 'AIFI_L2', 'AIFI_L2_score', 'AIFI_L3', 'AIFI_L3_score', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mito', 'log1p_total_counts_mito', 'pct_counts_mito', 'leiden_2'
    uns: 'hvg', 'leiden', 'log1p', 'neighbors', 'pca', 'rank_genes_groups', 'umap'
    obsm: 'X_pca', 'X_umap'
    obsp: 'connectivities', 'distances'
Doublet clusters: ['1', '15', '20', '22', '23', '21']
leiden_2           0    1    2    3    4    5    6    7    8    9  ...   14  \
doublets_manual                                                    ...
no               674    0  610  555  527  503  500  470  440  426  ...  367
yes                0  642    0    0    0    0    0    0    0    0  ...    0

leiden_2          15   16   17   18   19   20   21  22  23
doublets_manual
no                 0  332  320  308  300    0    0   0   0
yes              366    0    0    0    0  138  100  71  23

[2 rows x 24 columns]
Subsetted cells to: (9288, 33538)
Saving processed data

/opt/conda/lib/python3.10/site-packages/anndata/_core/anndata.py:1292: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c

Key: GZMKpos_CD27pos_EM_CD8_T_cell
Value: /home/jupyter/certpro_up1/unharmonized_output/up1_cluster_unharmonize_GZMKpos_CD27pos_EM_CD8_T_cell_2024-09-30.h5ad
AnnData object with n_obs × n_vars = 48412 × 33538
    obs: 'barcodes', 'batch_id', 'cell_name', 'cell_uuid', 'chip_id', 'hto_barcode', 'hto_category', 'n_genes', 'n_mito_umis', 'n_reads', 'n_umis', 'original_barcodes', 'pbmc_sample_id', 'pool_id', 'well_id', 'sample.sampleKitGuid', 'cohort.cohortGuid', 'subject.subjectGuid', 'subject.biologicalSex', 'subject.race', 'subject.ethnicity', 'subject.birthYear', 'sample.visitName', 'sample.drawDate', 'specimens.specimenGuid', 'specimens.specimenType', 'file.id', 'file.batchID', 'subset_grp', 'predicted_doublet', 'doublet_score', 'AIFI_L1', 'AIFI_L1_score', 'AIFI_L2', 'AIFI_L2_score', 'AIFI_L3', 'AIFI_L3_score', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mito', 'log1p_total_counts_mito', 'pct_counts_mito', 'leiden_2'
    uns: 'hvg', 'leiden', 'log1p', 'neighbors', 'pca', 'rank_genes_groups', 'umap'
    obsm: 'X_pca', 'X_umap'
    obsp: 'connectivities', 'distances'
Doublet clusters: ['22', '18', '21']
leiden_2            0     1     2     3     4     5     6     7     8     9  \
doublets_manual
no               3719  3508  3507  3456  3161  2976  2613  2465  2397  2117
yes                 0     0     0     0     0     0     0     0     0     0

leiden_2         ...   19   20   21   22   23   24   25   26   27   28
doublets_manual  ...
no               ...  727  702    0    0  638  445  344  201  190  100
yes              ...    0    0  673  646    0    0    0    0    0    0

[2 rows x 29 columns]
Subsetted cells to: (48412, 33538)
Saving processed data

/opt/conda/lib/python3.10/site-packages/anndata/_core/anndata.py:1292: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c

Key: ISGpos_MAIT
Value: /home/jupyter/certpro_up1/unharmonized_output/up1_cluster_unharmonize_ISGpos_MAIT_2024-09-30.h5ad
AnnData object with n_obs × n_vars = 1323 × 33538
    obs: 'barcodes', 'batch_id', 'cell_name', 'cell_uuid', 'chip_id', 'hto_barcode', 'hto_category', 'n_genes', 'n_mito_umis', 'n_reads', 'n_umis', 'original_barcodes', 'pbmc_sample_id', 'pool_id', 'well_id', 'sample.sampleKitGuid', 'cohort.cohortGuid', 'subject.subjectGuid', 'subject.biologicalSex', 'subject.race', 'subject.ethnicity', 'subject.birthYear', 'sample.visitName', 'sample.drawDate', 'specimens.specimenGuid', 'specimens.specimenType', 'file.id', 'file.batchID', 'subset_grp', 'predicted_doublet', 'doublet_score', 'AIFI_L1', 'AIFI_L1_score', 'AIFI_L2', 'AIFI_L2_score', 'AIFI_L3', 'AIFI_L3_score', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mito', 'log1p_total_counts_mito', 'pct_counts_mito', 'leiden_2'
    uns: 'hvg', 'leiden', 'log1p', 'neighbors', 'pca', 'rank_genes_groups', 'umap'
    obsm: 'X_pca', 'X_umap'
    obsp: 'connectivities', 'distances'
Doublet clusters: ['14', '16', '17']
leiden_2           0    1    2    3   4   5   6   7   8   9  10  11  12  13  \
doublets_manual
no               176  135  122  106  99  91  81  80  71  63  54  50  36  31
yes                0    0    0    0   0   0   0   0   0   0   0   0   0   0

leiden_2         14  15  16  17  18
doublets_manual
no                0  28   0   0  17
yes              31   0  27  25   0
Subsetted cells to: (1323, 33538)
Saving processed data

/opt/conda/lib/python3.10/site-packages/anndata/_core/anndata.py:1292: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c

Key: CD56bright_NK_cell
Value: /home/jupyter/certpro_up1/unharmonized_output/up1_cluster_unharmonize_CD56bright_NK_cell_2024-09-30.h5ad
AnnData object with n_obs × n_vars = 25591 × 33538
    obs: 'barcodes', 'batch_id', 'cell_name', 'cell_uuid', 'chip_id', 'hto_barcode', 'hto_category', 'n_genes', 'n_mito_umis', 'n_reads', 'n_umis', 'original_barcodes', 'pbmc_sample_id', 'pool_id', 'well_id', 'sample.sampleKitGuid', 'cohort.cohortGuid', 'subject.subjectGuid', 'subject.biologicalSex', 'subject.race', 'subject.ethnicity', 'subject.birthYear', 'sample.visitName', 'sample.drawDate', 'specimens.specimenGuid', 'specimens.specimenType', 'file.id', 'file.batchID', 'subset_grp', 'predicted_doublet', 'doublet_score', 'AIFI_L1', 'AIFI_L1_score', 'AIFI_L2', 'AIFI_L2_score', 'AIFI_L3', 'AIFI_L3_score', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mito', 'log1p_total_counts_mito', 'pct_counts_mito', 'leiden_2'
    uns: 'hvg', 'leiden', 'log1p', 'neighbors', 'pca', 'rank_genes_groups', 'umap'
    obsm: 'X_pca', 'X_umap'
    obsp: 'connectivities', 'distances'
Doublet clusters: ['7', '21', '22', '24', '26']
leiden_2            0     1     2     3     4     5     6     7     8     9  \
doublets_manual
no               2201  2104  2048  2044  1463  1385  1320     0  1043  1029
yes                 0     0     0     0     0     0     0  1298     0     0

leiden_2         ...   17   18   19   20   21   22   23   24   25  26
doublets_manual  ...
no               ...  563  562  550  435    0    0  268    0  166   0
yes              ...    0    0    0    0  399  271    0  185    0  89

[2 rows x 27 columns]
Subsetted cells to: (25591, 33538)
Saving processed data

/opt/conda/lib/python3.10/site-packages/anndata/_core/anndata.py:1292: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c

Key: CM_CD8_T_cell
Value: /home/jupyter/certpro_up1/unharmonized_output/up1_cluster_unharmonize_CM_CD8_T_cell_2024-09-30.h5ad
AnnData object with n_obs × n_vars = 45097 × 33538
    obs: 'barcodes', 'batch_id', 'cell_name', 'cell_uuid', 'chip_id', 'hto_barcode', 'hto_category', 'n_genes', 'n_mito_umis', 'n_reads', 'n_umis', 'original_barcodes', 'pbmc_sample_id', 'pool_id', 'well_id', 'sample.sampleKitGuid', 'cohort.cohortGuid', 'subject.subjectGuid', 'subject.biologicalSex', 'subject.race', 'subject.ethnicity', 'subject.birthYear', 'sample.visitName', 'sample.drawDate', 'specimens.specimenGuid', 'specimens.specimenType', 'file.id', 'file.batchID', 'subset_grp', 'predicted_doublet', 'doublet_score', 'AIFI_L1', 'AIFI_L1_score', 'AIFI_L2', 'AIFI_L2_score', 'AIFI_L3', 'AIFI_L3_score', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mito', 'log1p_total_counts_mito', 'pct_counts_mito', 'leiden_2'
    uns: 'hvg', 'leiden', 'log1p', 'neighbors', 'pca', 'rank_genes_groups', 'umap'
    obsm: 'X_pca', 'X_umap'
    obsp: 'connectivities', 'distances'
Doublet clusters: ['25']
leiden_2            0     1     2     3     4     5     6     7     8     9  \
doublets_manual
no               3858  3008  2908  2893  2583  2421  2374  2319  2175  2167
yes                 0     0     0     0     0     0     0     0     0     0

leiden_2         ...    16    17    18   19   20   21   22   23   24   25
doublets_manual  ...
no               ...  1426  1272  1128  675  575  511  411  373  337    0
yes              ...     0     0     0    0    0    0    0    0    0  223

[2 rows x 26 columns]
Subsetted cells to: (45097, 33538)
Saving processed data

/opt/conda/lib/python3.10/site-packages/anndata/_core/anndata.py:1292: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c

Key: SOX4pos_naive_CD4_T_cell
Value: /home/jupyter/certpro_up1/unharmonized_output/up1_cluster_unharmonize_SOX4pos_naive_CD4_T_cell_2024-09-30.h5ad
AnnData object with n_obs × n_vars = 143476 × 33538
    obs: 'barcodes', 'batch_id', 'cell_name', 'cell_uuid', 'chip_id', 'hto_barcode', 'hto_category', 'n_genes', 'n_mito_umis', 'n_reads', 'n_umis', 'original_barcodes', 'pbmc_sample_id', 'pool_id', 'well_id', 'sample.sampleKitGuid', 'cohort.cohortGuid', 'subject.subjectGuid', 'subject.biologicalSex', 'subject.race', 'subject.ethnicity', 'subject.birthYear', 'sample.visitName', 'sample.drawDate', 'specimens.specimenGuid', 'specimens.specimenType', 'file.id', 'file.batchID', 'subset_grp', 'predicted_doublet', 'doublet_score', 'AIFI_L1', 'AIFI_L1_score', 'AIFI_L2', 'AIFI_L2_score', 'AIFI_L3', 'AIFI_L3_score', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mito', 'log1p_total_counts_mito', 'pct_counts_mito', 'leiden_2'
    uns: 'hvg', 'leiden', 'log1p', 'neighbors', 'pca', 'rank_genes_groups', 'umap'
    obsm: 'X_pca', 'X_umap'
    obsp: 'connectivities', 'distances'
Doublet clusters: ['14', '16']
leiden_2             0      1      2      3      4      5      6      7  \
doublets_manual
no               15609  15203  14252  13249  12293  12071  12037  10664
yes                  0      0      0      0      0      0      0      0

leiden_2             8     9  ...    13    14    15   16   17   18   19  20  \
doublets_manual               ...
no               10470  9031  ...  2044     0  1232    0  562  256  140   7
yes                  0     0  ...     0  1717     0  898    0    0    0   0

leiden_2         21  22
doublets_manual
no                4   2
yes               0   0

[2 rows x 23 columns]
Subsetted cells to: (143476, 33538)
Saving processed data

/opt/conda/lib/python3.10/site-packages/anndata/_core/anndata.py:1292: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c

Key: CMP_cell
Value: /home/jupyter/certpro_up1/unharmonized_output/up1_cluster_unharmonize_CMP_cell_2024-09-30.h5ad
AnnData object with n_obs × n_vars = 1158 × 33538
    obs: 'barcodes', 'batch_id', 'cell_name', 'cell_uuid', 'chip_id', 'hto_barcode', 'hto_category', 'n_genes', 'n_mito_umis', 'n_reads', 'n_umis', 'original_barcodes', 'pbmc_sample_id', 'pool_id', 'well_id', 'sample.sampleKitGuid', 'cohort.cohortGuid', 'subject.subjectGuid', 'subject.biologicalSex', 'subject.race', 'subject.ethnicity', 'subject.birthYear', 'sample.visitName', 'sample.drawDate', 'specimens.specimenGuid', 'specimens.specimenType', 'file.id', 'file.batchID', 'subset_grp', 'predicted_doublet', 'doublet_score', 'AIFI_L1', 'AIFI_L1_score', 'AIFI_L2', 'AIFI_L2_score', 'AIFI_L3', 'AIFI_L3_score', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mito', 'log1p_total_counts_mito', 'pct_counts_mito', 'leiden_2'
    uns: 'hvg', 'leiden', 'log1p', 'neighbors', 'pca', 'rank_genes_groups', 'umap'
    obsm: 'X_pca', 'X_umap'
    obsp: 'connectivities', 'distances'
Doublet clusters: ['7']
leiden_2           0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  \
doublets_manual
no               106  98  97  80  78  77  75   0  68  67  66  52  51  42  37
yes                0   0   0   0   0   0   0  72   0   0   0   0   0   0   0

leiden_2         15  16  17  18
doublets_manual
no               34  29  16  13
yes               0   0   0   0
Subsetted cells to: (1158, 33538)
Saving processed data

/opt/conda/lib/python3.10/site-packages/anndata/_core/anndata.py:1292: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c

Key: IL1Bpos_CD14_monocyte
Value: /home/jupyter/certpro_up1/unharmonized_output/up1_cluster_unharmonize_IL1Bpos_CD14_monocyte_2024-09-30.h5ad
AnnData object with n_obs × n_vars = 92839 × 33538
    obs: 'barcodes', 'batch_id', 'cell_name', 'cell_uuid', 'chip_id', 'hto_barcode', 'hto_category', 'n_genes', 'n_mito_umis', 'n_reads', 'n_umis', 'original_barcodes', 'pbmc_sample_id', 'pool_id', 'well_id', 'sample.sampleKitGuid', 'cohort.cohortGuid', 'subject.subjectGuid', 'subject.biologicalSex', 'subject.race', 'subject.ethnicity', 'subject.birthYear', 'sample.visitName', 'sample.drawDate', 'specimens.specimenGuid', 'specimens.specimenType', 'file.id', 'file.batchID', 'subset_grp', 'predicted_doublet', 'doublet_score', 'AIFI_L1', 'AIFI_L1_score', 'AIFI_L2', 'AIFI_L2_score', 'AIFI_L3', 'AIFI_L3_score', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mito', 'log1p_total_counts_mito', 'pct_counts_mito', 'leiden_2'
    uns: 'hvg', 'leiden', 'log1p', 'neighbors', 'pca', 'rank_genes_groups', 'umap'
    obsm: 'X_pca', 'X_umap'
    obsp: 'connectivities', 'distances'
Doublet clusters: ['32', '28', '18', '6', '15', '30']
leiden_2            0     1     2     3     4     5     6     7     8     9  \
doublets_manual
no               6291  5899  5548  5117  5089  4910     0  4658  4281  4146
yes                 0     0     0     0     0     0  4791     0     0     0

leiden_2         ...    23    24    25    26    27   28   29   30   31   32
doublets_manual  ...
no               ...  1543  1482  1394  1218  1059    0  733    0  326    0
yes              ...     0     0     0     0     0  781    0  576    0  107

[2 rows x 33 columns]
Subsetted cells to: (92839, 33538)
Saving processed data

/opt/conda/lib/python3.10/site-packages/anndata/_core/anndata.py:1292: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c

Key: Activated_memory_B_cell
Value: /home/jupyter/certpro_up1/unharmonized_output/up1_cluster_unharmonize_Activated_memory_B_cell_2024-09-30.h5ad
AnnData object with n_obs × n_vars = 1745 × 33538
    obs: 'barcodes', 'batch_id', 'cell_name', 'cell_uuid', 'chip_id', 'hto_barcode', 'hto_category', 'n_genes', 'n_mito_umis', 'n_reads', 'n_umis', 'original_barcodes', 'pbmc_sample_id', 'pool_id', 'well_id', 'sample.sampleKitGuid', 'cohort.cohortGuid', 'subject.subjectGuid', 'subject.biologicalSex', 'subject.race', 'subject.ethnicity', 'subject.birthYear', 'sample.visitName', 'sample.drawDate', 'specimens.specimenGuid', 'specimens.specimenType', 'file.id', 'file.batchID', 'subset_grp', 'predicted_doublet', 'doublet_score', 'AIFI_L1', 'AIFI_L1_score', 'AIFI_L2', 'AIFI_L2_score', 'AIFI_L3', 'AIFI_L3_score', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mito', 'log1p_total_counts_mito', 'pct_counts_mito', 'leiden_2'
    uns: 'hvg', 'leiden', 'log1p', 'neighbors', 'pca', 'rank_genes_groups', 'umap'
    obsm: 'X_pca', 'X_umap'
    obsp: 'connectivities', 'distances'
Doublet clusters: ['0', '8']
leiden_2           0    1    2    3    4    5    6    7    8    9   10  11  \
doublets_manual
no                 0  165  165  153  143  132  123  116    0  106  104  93
yes              167    0    0    0    0    0    0    0  110    0    0   0

leiden_2         12  13  14  15
doublets_manual
no               69  51  34  14
yes               0   0   0   0
Subsetted cells to: (1745, 33538)
Saving processed data

/opt/conda/lib/python3.10/site-packages/anndata/_core/anndata.py:1292: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c

Key: ASDC
Value: /home/jupyter/certpro_up1/unharmonized_output/up1_cluster_unharmonize_ASDC_2024-09-30.h5ad
AnnData object with n_obs × n_vars = 1301 × 33538
    obs: 'barcodes', 'batch_id', 'cell_name', 'cell_uuid', 'chip_id', 'hto_barcode', 'hto_category', 'n_genes', 'n_mito_umis', 'n_reads', 'n_umis', 'original_barcodes', 'pbmc_sample_id', 'pool_id', 'well_id', 'sample.sampleKitGuid', 'cohort.cohortGuid', 'subject.subjectGuid', 'subject.biologicalSex', 'subject.race', 'subject.ethnicity', 'subject.birthYear', 'sample.visitName', 'sample.drawDate', 'specimens.specimenGuid', 'specimens.specimenType', 'file.id', 'file.batchID', 'subset_grp', 'predicted_doublet', 'doublet_score', 'AIFI_L1', 'AIFI_L1_score', 'AIFI_L2', 'AIFI_L2_score', 'AIFI_L3', 'AIFI_L3_score', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mito', 'log1p_total_counts_mito', 'pct_counts_mito', 'leiden_2'
    uns: 'hvg', 'leiden', 'log1p', 'neighbors', 'pca', 'rank_genes_groups', 'umap'
    obsm: 'X_pca', 'X_umap'
    obsp: 'connectivities', 'distances'
Doublet clusters: ['12', '15']
leiden_2           0    1    2   3   4   5   6   7   8   9  10  11  12  13  \
doublets_manual
no               139  111  100  99  99  98  98  95  91  88  88  83   0  17
yes                0    0    0   0   0   0   0   0   0   0   0   0  68   0

leiden_2         14  15
doublets_manual
no               15   0
yes               0  12
Subsetted cells to: (1301, 33538)
Saving processed data

/opt/conda/lib/python3.10/site-packages/anndata/_core/anndata.py:1292: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c

Key: CD4_MAIT
Value: /home/jupyter/certpro_up1/unharmonized_output/up1_cluster_unharmonize_CD4_MAIT_2024-09-30.h5ad
AnnData object with n_obs × n_vars = 2414 × 33538
    obs: 'barcodes', 'batch_id', 'cell_name', 'cell_uuid', 'chip_id', 'hto_barcode', 'hto_category', 'n_genes', 'n_mito_umis', 'n_reads', 'n_umis', 'original_barcodes', 'pbmc_sample_id', 'pool_id', 'well_id', 'sample.sampleKitGuid', 'cohort.cohortGuid', 'subject.subjectGuid', 'subject.biologicalSex', 'subject.race', 'subject.ethnicity', 'subject.birthYear', 'sample.visitName', 'sample.drawDate', 'specimens.specimenGuid', 'specimens.specimenType', 'file.id', 'file.batchID', 'subset_grp', 'predicted_doublet', 'doublet_score', 'AIFI_L1', 'AIFI_L1_score', 'AIFI_L2', 'AIFI_L2_score', 'AIFI_L3', 'AIFI_L3_score', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mito', 'log1p_total_counts_mito', 'pct_counts_mito', 'leiden_2'
    uns: 'hvg', 'leiden', 'log1p', 'neighbors', 'pca', 'rank_genes_groups', 'umap'
    obsm: 'X_pca', 'X_umap'
    obsp: 'connectivities', 'distances'
Doublet clusters: ['13', '16', '4', '2', '9', '7', '16', '3', '6', '15', '17', '5']
leiden_2           0    1    2    3    4    5    6    7    8    9   10  11  \
doublets_manual
no               268  244    0    0    0    0    0    0  120    0  100  93
yes                0    0  234  219  196  191  134  128    0  109    0   0

leiden_2         12  13  14  15  16  17
doublets_manual
no               78   0  59   0   0   0
yes               0  77   0  59  55  50
Subsetted cells to: (2414, 33538)
Saving processed data

/opt/conda/lib/python3.10/site-packages/anndata/_core/anndata.py:1292: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c

Key: CD27pos_effector_B_cell
Value: /home/jupyter/certpro_up1/unharmonized_output/up1_cluster_unharmonize_CD27pos_effector_B_cell_2024-09-30.h5ad
AnnData object with n_obs × n_vars = 15844 × 33538
    obs: 'barcodes', 'batch_id', 'cell_name', 'cell_uuid', 'chip_id', 'hto_barcode', 'hto_category', 'n_genes', 'n_mito_umis', 'n_reads', 'n_umis', 'original_barcodes', 'pbmc_sample_id', 'pool_id', 'well_id', 'sample.sampleKitGuid', 'cohort.cohortGuid', 'subject.subjectGuid', 'subject.biologicalSex', 'subject.race', 'subject.ethnicity', 'subject.birthYear', 'sample.visitName', 'sample.drawDate', 'specimens.specimenGuid', 'specimens.specimenType', 'file.id', 'file.batchID', 'subset_grp', 'predicted_doublet', 'doublet_score', 'AIFI_L1', 'AIFI_L1_score', 'AIFI_L2', 'AIFI_L2_score', 'AIFI_L3', 'AIFI_L3_score', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mito', 'log1p_total_counts_mito', 'pct_counts_mito', 'leiden_2'
    uns: 'hvg', 'leiden', 'log1p', 'neighbors', 'pca', 'rank_genes_groups', 'umap'
    obsm: 'X_pca', 'X_umap'
    obsp: 'connectivities', 'distances'
Doublet clusters: ['17', '21', '20']
leiden_2            0     1     2     3    4    5    6    7    8    9  ...  \
doublets_manual                                                        ...
no               1410  1317  1290  1103  916  903  899  823  728  665  ...
yes                 0     0     0     0    0    0    0    0    0    0  ...

leiden_2          15   16   17   18   19   20   21   22   23   24
doublets_manual
no               453  427    0  377  299    0    0  197  184  181
yes                0    0  422    0    0  218  211    0    0    0

[2 rows x 25 columns]
Subsetted cells to: (15844, 33538)
Saving processed data

/opt/conda/lib/python3.10/site-packages/anndata/_core/anndata.py:1292: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c

Key: SOX4pos_Vd1_gdT
Value: /home/jupyter/certpro_up1/unharmonized_output/up1_cluster_unharmonize_SOX4pos_Vd1_gdT_2024-09-30.h5ad
AnnData object with n_obs × n_vars = 14256 × 33538
    obs: 'barcodes', 'batch_id', 'cell_name', 'cell_uuid', 'chip_id', 'hto_barcode', 'hto_category', 'n_genes', 'n_mito_umis', 'n_reads', 'n_umis', 'original_barcodes', 'pbmc_sample_id', 'pool_id', 'well_id', 'sample.sampleKitGuid', 'cohort.cohortGuid', 'subject.subjectGuid', 'subject.biologicalSex', 'subject.race', 'subject.ethnicity', 'subject.birthYear', 'sample.visitName', 'sample.drawDate', 'specimens.specimenGuid', 'specimens.specimenType', 'file.id', 'file.batchID', 'subset_grp', 'predicted_doublet', 'doublet_score', 'AIFI_L1', 'AIFI_L1_score', 'AIFI_L2', 'AIFI_L2_score', 'AIFI_L3', 'AIFI_L3_score', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mito', 'log1p_total_counts_mito', 'pct_counts_mito', 'leiden_2'
    uns: 'hvg', 'leiden', 'log1p', 'neighbors', 'pca', 'rank_genes_groups', 'umap'
    obsm: 'X_pca', 'X_umap'
    obsp: 'connectivities', 'distances'
Doublet clusters: ['19', '20', '21']
leiden_2            0     1     2     3     4     5    6    7    8    9  ...  \
doublets_manual                                                          ...
no               1209  1093  1092  1055  1040  1028  961  948  918  888  ...
yes                 0     0     0     0     0     0    0    0    0    0  ...

leiden_2          13   14   15   16   17   18   19   20   21  22
doublets_manual
no               505  394  332  210  172  139    0    0    0  52
yes                0    0    0    0    0    0  131  118  117   0

[2 rows x 23 columns]
Subsetted cells to: (14256, 33538)
Saving processed data

/opt/conda/lib/python3.10/site-packages/anndata/_core/anndata.py:1292: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c

Key: ISGpos_naive_B_cell
Value: /home/jupyter/certpro_up1/unharmonized_output/up1_cluster_unharmonize_ISGpos_naive_B_cell_2024-09-30.h5ad
AnnData object with n_obs × n_vars = 13274 × 33538
    obs: 'barcodes', 'batch_id', 'cell_name', 'cell_uuid', 'chip_id', 'hto_barcode', 'hto_category', 'n_genes', 'n_mito_umis', 'n_reads', 'n_umis', 'original_barcodes', 'pbmc_sample_id', 'pool_id', 'well_id', 'sample.sampleKitGuid', 'cohort.cohortGuid', 'subject.subjectGuid', 'subject.biologicalSex', 'subject.race', 'subject.ethnicity', 'subject.birthYear', 'sample.visitName', 'sample.drawDate', 'specimens.specimenGuid', 'specimens.specimenType', 'file.id', 'file.batchID', 'subset_grp', 'predicted_doublet', 'doublet_score', 'AIFI_L1', 'AIFI_L1_score', 'AIFI_L2', 'AIFI_L2_score', 'AIFI_L3', 'AIFI_L3_score', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mito', 'log1p_total_counts_mito', 'pct_counts_mito', 'leiden_2'
    uns: 'hvg', 'leiden', 'log1p', 'neighbors', 'pca', 'rank_genes_groups', 'umap'
    obsm: 'X_pca', 'X_umap'
    obsp: 'connectivities', 'distances'
Doublet clusters: ['11', '16', '20', '21', '19']
leiden_2            0     1     2    3    4    5    6    7    8    9  ...  \
doublets_manual                                                       ...
no               1133  1021  1019  973  938  898  861  802  753  716  ...
yes                 0     0     0    0    0    0    0    0    0    0  ...

leiden_2          14   15   16   17   18   19  20  21  22  23
doublets_manual
no               360  330    0  240  165    0   0   0  33  19
yes                0    0  266    0    0  138  91  66   0   0

[2 rows x 24 columns]
Subsetted cells to: (13274, 33538)
Saving processed data

/opt/conda/lib/python3.10/site-packages/anndata/_core/anndata.py:1292: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c

Key: GZMBneg_CD27pos_EM_CD4_T_cell
Value: /home/jupyter/certpro_up1/unharmonized_output/up1_cluster_unharmonize_GZMBneg_CD27pos_EM_CD4_T_cell_2024-09-30.h5ad
AnnData object with n_obs × n_vars = 63630 × 33538
    obs: 'barcodes', 'batch_id', 'cell_name', 'cell_uuid', 'chip_id', 'hto_barcode', 'hto_category', 'n_genes', 'n_mito_umis', 'n_reads', 'n_umis', 'original_barcodes', 'pbmc_sample_id', 'pool_id', 'well_id', 'sample.sampleKitGuid', 'cohort.cohortGuid', 'subject.subjectGuid', 'subject.biologicalSex', 'subject.race', 'subject.ethnicity', 'subject.birthYear', 'sample.visitName', 'sample.drawDate', 'specimens.specimenGuid', 'specimens.specimenType', 'file.id', 'file.batchID', 'subset_grp', 'predicted_doublet', 'doublet_score', 'AIFI_L1', 'AIFI_L1_score', 'AIFI_L2', 'AIFI_L2_score', 'AIFI_L3', 'AIFI_L3_score', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mito', 'log1p_total_counts_mito', 'pct_counts_mito', 'leiden_2'
    uns: 'hvg', 'leiden', 'log1p', 'neighbors', 'pca', 'rank_genes_groups', 'umap'
    obsm: 'X_pca', 'X_umap'
    obsp: 'connectivities', 'distances'
Doublet clusters: ['19']
leiden_2            0     1     2     3     4     5     6     7     8     9  \
doublets_manual
no               5292  5207  4596  4197  4119  4023  3942  3857  3818  3299
yes                 0     0     0     0     0     0     0     0     0     0

leiden_2         ...    14    15    16    17    18   19   20   21   22  23
doublets_manual  ...
no               ...  2009  1763  1461  1227  1059    0  575  378  191  39
yes              ...     0     0     0     0     0  597    0    0    0   0

[2 rows x 24 columns]
Subsetted cells to: (63630, 33538)
Saving processed data

/opt/conda/lib/python3.10/site-packages/anndata/_core/anndata.py:1292: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c

Key: Plasma_cell
Value: /home/jupyter/certpro_up1/unharmonized_output/up1_cluster_unharmonize_Plasma_cell_2024-09-30.h5ad
AnnData object with n_obs × n_vars = 10676 × 33538
    obs: 'barcodes', 'batch_id', 'cell_name', 'cell_uuid', 'chip_id', 'hto_barcode', 'hto_category', 'n_genes', 'n_mito_umis', 'n_reads', 'n_umis', 'original_barcodes', 'pbmc_sample_id', 'pool_id', 'well_id', 'sample.sampleKitGuid', 'cohort.cohortGuid', 'subject.subjectGuid', 'subject.biologicalSex', 'subject.race', 'subject.ethnicity', 'subject.birthYear', 'sample.visitName', 'sample.drawDate', 'specimens.specimenGuid', 'specimens.specimenType', 'file.id', 'file.batchID', 'subset_grp', 'predicted_doublet', 'doublet_score', 'AIFI_L1', 'AIFI_L1_score', 'AIFI_L2', 'AIFI_L2_score', 'AIFI_L3', 'AIFI_L3_score', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mito', 'log1p_total_counts_mito', 'pct_counts_mito', 'leiden_2'
    uns: 'hvg', 'leiden', 'log1p', 'neighbors', 'pca', 'rank_genes_groups', 'umap'
    obsm: 'X_pca', 'X_umap'
    obsp: 'connectivities', 'distances'
Doublet clusters: ['23', '13', '18', '10']
leiden_2           0    1    2    3    4    5    6    7    8    9  ...   17  \
doublets_manual                                                    ...
no               818  773  744  737  700  679  580  571  549  514  ...  222
yes                0    0    0    0    0    0    0    0    0    0  ...    0

leiden_2          18   19   20   21  22  23  24  25  26
doublets_manual
no                 0  212  201  139  84   0  76  40  29
yes              212    0    0    0   0  77   0   0   0

[2 rows x 27 columns]
Subsetted cells to: (10676, 33538)
Saving processed data

/opt/conda/lib/python3.10/site-packages/anndata/_core/anndata.py:1292: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c

Key: GZMBpos_Vd2_gdT
Value: /home/jupyter/certpro_up1/unharmonized_output/up1_cluster_unharmonize_GZMBpos_Vd2_gdT_2024-09-30.h5ad
AnnData object with n_obs × n_vars = 42208 × 33538
    obs: 'barcodes', 'batch_id', 'cell_name', 'cell_uuid', 'chip_id', 'hto_barcode', 'hto_category', 'n_genes', 'n_mito_umis', 'n_reads', 'n_umis', 'original_barcodes', 'pbmc_sample_id', 'pool_id', 'well_id', 'sample.sampleKitGuid', 'cohort.cohortGuid', 'subject.subjectGuid', 'subject.biologicalSex', 'subject.race', 'subject.ethnicity', 'subject.birthYear', 'sample.visitName', 'sample.drawDate', 'specimens.specimenGuid', 'specimens.specimenType', 'file.id', 'file.batchID', 'subset_grp', 'predicted_doublet', 'doublet_score', 'AIFI_L1', 'AIFI_L1_score', 'AIFI_L2', 'AIFI_L2_score', 'AIFI_L3', 'AIFI_L3_score', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mito', 'log1p_total_counts_mito', 'pct_counts_mito', 'leiden_2'
    uns: 'hvg', 'leiden', 'log1p', 'neighbors', 'pca', 'rank_genes_groups', 'umap'
    obsm: 'X_pca', 'X_umap'
    obsp: 'connectivities', 'distances'
Doublet clusters: ['19', '22']
leiden_2            0     1     2     3     4     5     6     7     8     9  \
doublets_manual
no               4659  3212  2773  2582  2577  2496  2467  2452  2328  2253
yes                 0     0     0     0     0     0     0     0     0     0

leiden_2         ...    15   16   17   18   19   20   21   22  23  24
doublets_manual  ...
no               ...  1050  958  714  581    0  369  226    0  56  53
yes              ...     0    0    0    0  510    0    0  189   0   0

[2 rows x 25 columns]
Subsetted cells to: (42208, 33538)
Saving processed data

/opt/conda/lib/python3.10/site-packages/anndata/_core/anndata.py:1292: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c

Key: Platelet
Value: /home/jupyter/certpro_up1/unharmonized_output/up1_cluster_unharmonize_Platelet_2024-09-30.h5ad
AnnData object with n_obs × n_vars = 18082 × 33538
    obs: 'barcodes', 'batch_id', 'cell_name', 'cell_uuid', 'chip_id', 'hto_barcode', 'hto_category', 'n_genes', 'n_mito_umis', 'n_reads', 'n_umis', 'original_barcodes', 'pbmc_sample_id', 'pool_id', 'well_id', 'sample.sampleKitGuid', 'cohort.cohortGuid', 'subject.subjectGuid', 'subject.biologicalSex', 'subject.race', 'subject.ethnicity', 'subject.birthYear', 'sample.visitName', 'sample.drawDate', 'specimens.specimenGuid', 'specimens.specimenType', 'file.id', 'file.batchID', 'subset_grp', 'predicted_doublet', 'doublet_score', 'AIFI_L1', 'AIFI_L1_score', 'AIFI_L2', 'AIFI_L2_score', 'AIFI_L3', 'AIFI_L3_score', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mito', 'log1p_total_counts_mito', 'pct_counts_mito', 'leiden_2'
    uns: 'hvg', 'leiden', 'log1p', 'neighbors', 'pca', 'rank_genes_groups', 'umap'
    obsm: 'X_pca', 'X_umap'
    obsp: 'connectivities', 'distances'
Doublet clusters: ['18', '10', '7', '16', '17', '13', '14']
leiden_2            0     1     2     3     4     5     6     7     8    9  \
doublets_manual
no               2051  1653  1634  1606  1515  1432  1423     0  1002  896
yes                 0     0     0     0     0     0     0  1048     0    0

leiden_2         ...   11   12   13   14   15   16   17   18   19  20
doublets_manual  ...
no               ...  652  580    0    0  287    0    0    0  119  94
yes              ...    0    0  383  313    0  267  220  170    0   0

[2 rows x 21 columns]
Subsetted cells to: (18082, 33538)
Saving processed data

/opt/conda/lib/python3.10/site-packages/anndata/_core/anndata.py:1292: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c

Key: Proliferating_NK_cell
Value: /home/jupyter/certpro_up1/unharmonized_output/up1_cluster_unharmonize_Proliferating_NK_cell_2024-09-30.h5ad
AnnData object with n_obs × n_vars = 6403 × 33538
    obs: 'barcodes', 'batch_id', 'cell_name', 'cell_uuid', 'chip_id', 'hto_barcode', 'hto_category', 'n_genes', 'n_mito_umis', 'n_reads', 'n_umis', 'original_barcodes', 'pbmc_sample_id', 'pool_id', 'well_id', 'sample.sampleKitGuid', 'cohort.cohortGuid', 'subject.subjectGuid', 'subject.biologicalSex', 'subject.race', 'subject.ethnicity', 'subject.birthYear', 'sample.visitName', 'sample.drawDate', 'specimens.specimenGuid', 'specimens.specimenType', 'file.id', 'file.batchID', 'subset_grp', 'predicted_doublet', 'doublet_score', 'AIFI_L1', 'AIFI_L1_score', 'AIFI_L2', 'AIFI_L2_score', 'AIFI_L3', 'AIFI_L3_score', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mito', 'log1p_total_counts_mito', 'pct_counts_mito', 'leiden_2'
    uns: 'hvg', 'leiden', 'log1p', 'neighbors', 'pca', 'rank_genes_groups', 'umap'
    obsm: 'X_pca', 'X_umap'
    obsp: 'connectivities', 'distances'
Doublet clusters: ['21', '20', '10', '8']
leiden_2           0    1    2    3    4    5    6    7    8    9  ...   12  \
doublets_manual                                                    ...
no               685  473  430  429  417  404  365  348    0  314  ...  254
yes                0    0    0    0    0    0    0    0  336    0  ...    0

leiden_2          13   14   15   16   17   18  19  20  21
doublets_manual
no               240  232  225  208  176  104  92   0   0
yes                0    0    0    0    0    0   0  76  30

[2 rows x 22 columns]
Subsetted cells to: (6403, 33538)
Saving processed data

/opt/conda/lib/python3.10/site-packages/anndata/_core/anndata.py:1292: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c

Key: GZMKpos_CD56dim_NK_cell
Value: /home/jupyter/certpro_up1/unharmonized_output/up1_cluster_unharmonize_GZMKpos_CD56dim_NK_cell_2024-09-30.h5ad
AnnData object with n_obs × n_vars = 22967 × 33538
    obs: 'barcodes', 'batch_id', 'cell_name', 'cell_uuid', 'chip_id', 'hto_barcode', 'hto_category', 'n_genes', 'n_mito_umis', 'n_reads', 'n_umis', 'original_barcodes', 'pbmc_sample_id', 'pool_id', 'well_id', 'sample.sampleKitGuid', 'cohort.cohortGuid', 'subject.subjectGuid', 'subject.biologicalSex', 'subject.race', 'subject.ethnicity', 'subject.birthYear', 'sample.visitName', 'sample.drawDate', 'specimens.specimenGuid', 'specimens.specimenType', 'file.id', 'file.batchID', 'subset_grp', 'predicted_doublet', 'doublet_score', 'AIFI_L1', 'AIFI_L1_score', 'AIFI_L2', 'AIFI_L2_score', 'AIFI_L3', 'AIFI_L3_score', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mito', 'log1p_total_counts_mito', 'pct_counts_mito', 'leiden_2'
    uns: 'hvg', 'leiden', 'log1p', 'neighbors', 'pca', 'rank_genes_groups', 'umap'
    obsm: 'X_pca', 'X_umap'
    obsp: 'connectivities', 'distances'
Doublet clusters: ['7', '18', '22', '20']
leiden_2            0     1     2     3     4     5     6     7     8     9  \
doublets_manual
no               1866  1789  1734  1696  1687  1681  1553     0  1261  1169
yes                 0     0     0     0     0     0     0  1279     0     0

leiden_2         ...   14   15   16   17   18   19   20   21   22  23
doublets_manual  ...
no               ...  621  597  584  458    0  346    0  225    0  88
yes              ...    0    0    0    0  392    0  321    0  117   0

[2 rows x 24 columns]
Subsetted cells to: (22967, 33538)
Saving processed data

/opt/conda/lib/python3.10/site-packages/anndata/_core/anndata.py:1292: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c

Key: KLRF1neg_GZMBpos_CD27neg_memory_CD4_T_cell
Value: /home/jupyter/certpro_up1/unharmonized_output/up1_cluster_unharmonize_KLRF1neg_GZMBpos_CD27neg_memory_CD4_T_cell_2024-09-30.h5ad
AnnData object with n_obs × n_vars = 6686 × 33538
    obs: 'barcodes', 'batch_id', 'cell_name', 'cell_uuid', 'chip_id', 'hto_barcode', 'hto_category', 'n_genes', 'n_mito_umis', 'n_reads', 'n_umis', 'original_barcodes', 'pbmc_sample_id', 'pool_id', 'well_id', 'sample.sampleKitGuid', 'cohort.cohortGuid', 'subject.subjectGuid', 'subject.biologicalSex', 'subject.race', 'subject.ethnicity', 'subject.birthYear', 'sample.visitName', 'sample.drawDate', 'specimens.specimenGuid', 'specimens.specimenType', 'file.id', 'file.batchID', 'subset_grp', 'predicted_doublet', 'doublet_score', 'AIFI_L1', 'AIFI_L1_score', 'AIFI_L2', 'AIFI_L2_score', 'AIFI_L3', 'AIFI_L3_score', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mito', 'log1p_total_counts_mito', 'pct_counts_mito', 'leiden_2'
    uns: 'hvg', 'leiden', 'log1p', 'neighbors', 'pca', 'rank_genes_groups', 'umap'
    obsm: 'X_pca', 'X_umap'
    obsp: 'connectivities', 'distances'
Doublet clusters: ['17']
leiden_2           0    1    2    3    4    5    6    7    8    9  ...   12  \
doublets_manual                                                    ...
no               699  623  612  472  451  426  420  404  364  361  ...  257
yes                0    0    0    0    0    0    0    0    0    0  ...    0

leiden_2          13   14   15  16  17  18  19  20  21
doublets_manual
no               239  238  188  90   0  61  60  57   4
yes                0    0    0   0  62   0   0   0   0

[2 rows x 22 columns]
Subsetted cells to: (6686, 33538)
Saving processed data

/opt/conda/lib/python3.10/site-packages/anndata/_core/anndata.py:1292: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c

Key: Early_memory_B_cell
Value: /home/jupyter/certpro_up1/unharmonized_output/up1_cluster_unharmonize_Early_memory_B_cell_2024-09-30.h5ad
AnnData object with n_obs × n_vars = 5127 × 33538
    obs: 'barcodes', 'batch_id', 'cell_name', 'cell_uuid', 'chip_id', 'hto_barcode', 'hto_category', 'n_genes', 'n_mito_umis', 'n_reads', 'n_umis', 'original_barcodes', 'pbmc_sample_id', 'pool_id', 'well_id', 'sample.sampleKitGuid', 'cohort.cohortGuid', 'subject.subjectGuid', 'subject.biologicalSex', 'subject.race', 'subject.ethnicity', 'subject.birthYear', 'sample.visitName', 'sample.drawDate', 'specimens.specimenGuid', 'specimens.specimenType', 'file.id', 'file.batchID', 'subset_grp', 'predicted_doublet', 'doublet_score', 'AIFI_L1', 'AIFI_L1_score', 'AIFI_L2', 'AIFI_L2_score', 'AIFI_L3', 'AIFI_L3_score', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mito', 'log1p_total_counts_mito', 'pct_counts_mito', 'leiden_2'
    uns: 'hvg', 'leiden', 'log1p', 'neighbors', 'pca', 'rank_genes_groups', 'umap'
    obsm: 'X_pca', 'X_umap'
    obsp: 'connectivities', 'distances'
Doublet clusters: ['3', '16', '26']
leiden_2           0    1    2    3    4    5    6    7    8    9  ...   18  \
doublets_manual                                                    ...
no               502  403  340    0  282  274  272  234  228  189  ...  120
yes                0    0    0  285    0    0    0    0    0    0  ...    0

leiden_2          19   20  21  22  23  24  25  26  27
doublets_manual
no               112  109  90  89  88  87  57   0   7
yes                0    0   0   0   0   0   0  34   0

[2 rows x 28 columns]
Subsetted cells to: (5127, 33538)
Saving processed data

/opt/conda/lib/python3.10/site-packages/anndata/_core/anndata.py:1292: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c

Key: C1Qpos_CD16_monocyte
Value: /home/jupyter/certpro_up1/unharmonized_output/up1_cluster_unharmonize_C1Qpos_CD16_monocyte_2024-09-30.h5ad
AnnData object with n_obs × n_vars = 3895 × 33538
    obs: 'barcodes', 'batch_id', 'cell_name', 'cell_uuid', 'chip_id', 'hto_barcode', 'hto_category', 'n_genes', 'n_mito_umis', 'n_reads', 'n_umis', 'original_barcodes', 'pbmc_sample_id', 'pool_id', 'well_id', 'sample.sampleKitGuid', 'cohort.cohortGuid', 'subject.subjectGuid', 'subject.biologicalSex', 'subject.race', 'subject.ethnicity', 'subject.birthYear', 'sample.visitName', 'sample.drawDate', 'specimens.specimenGuid', 'specimens.specimenType', 'file.id', 'file.batchID', 'subset_grp', 'predicted_doublet', 'doublet_score', 'AIFI_L1', 'AIFI_L1_score', 'AIFI_L2', 'AIFI_L2_score', 'AIFI_L3', 'AIFI_L3_score', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mito', 'log1p_total_counts_mito', 'pct_counts_mito', 'leiden_2'
    uns: 'hvg', 'leiden', 'log1p', 'neighbors', 'pca', 'rank_genes_groups', 'umap'
    obsm: 'X_pca', 'X_umap'
    obsp: 'connectivities', 'distances'
Doublet clusters: ['1', '11', '16', '13', '18']
leiden_2           0    1    2    3    4    5    6    7    8    9   10   11  \
doublets_manual
no               366    0  325  310  291  291  288  270  245  200  186    0
yes                0  329    0    0    0    0    0    0    0    0    0  176

leiden_2          12   13   14   15  16  17  18
doublets_manual
no               166    0  116  106   0  39   0
yes                0  119    0    0  51   0  21
Subsetted cells to: (3895, 33538)
Saving processed data

/opt/conda/lib/python3.10/site-packages/anndata/_core/anndata.py:1292: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c

Key: CM_CD4_T_cell
Value: /home/jupyter/certpro_up1/unharmonized_output/up1_cluster_unharmonize_CM_CD4_T_cell_2024-09-30.h5ad
AnnData object with n_obs × n_vars = 215598 × 33538
    obs: 'barcodes', 'batch_id', 'cell_name', 'cell_uuid', 'chip_id', 'hto_barcode', 'hto_category', 'n_genes', 'n_mito_umis', 'n_reads', 'n_umis', 'original_barcodes', 'pbmc_sample_id', 'pool_id', 'well_id', 'sample.sampleKitGuid', 'cohort.cohortGuid', 'subject.subjectGuid', 'subject.biologicalSex', 'subject.race', 'subject.ethnicity', 'subject.birthYear', 'sample.visitName', 'sample.drawDate', 'specimens.specimenGuid', 'specimens.specimenType', 'file.id', 'file.batchID', 'subset_grp', 'predicted_doublet', 'doublet_score', 'AIFI_L1', 'AIFI_L1_score', 'AIFI_L2', 'AIFI_L2_score', 'AIFI_L3', 'AIFI_L3_score', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mito', 'log1p_total_counts_mito', 'pct_counts_mito', 'leiden_2'
    uns: 'hvg', 'leiden', 'log1p', 'neighbors', 'pca', 'rank_genes_groups', 'umap'
    obsm: 'X_pca', 'X_umap'
    obsp: 'connectivities', 'distances'
Doublet clusters: ['18', '20', '22', '24']
leiden_2             0      1      2      3      4      5      6      7  \
doublets_manual
no               16724  16525  15156  14290  12282  11788  11152  11073
yes                  0      0      0      0      0      0      0      0

leiden_2             8      9  ...    15    16    17    18    19    20    21  \
doublets_manual                ...
no               10073  10005  ...  7842  6686  6514     0  4449     0  2943
yes                  0      0  ...     0     0     0  4699     0  4325     0

leiden_2           22   23   24
doublets_manual
no                  0  853    0
yes              1608    0  515

[2 rows x 25 columns]
Subsetted cells to: (215598, 33538)
Saving processed data

/opt/conda/lib/python3.10/site-packages/anndata/_core/anndata.py:1292: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c

Key: KLRF1pos_GZMBpos_CD27neg_EM_CD8_T_cell
Value: /home/jupyter/certpro_up1/unharmonized_output/up1_cluster_unharmonize_KLRF1pos_GZMBpos_CD27neg_EM_CD8_T_cell_2024-09-30.h5ad
AnnData object with n_obs × n_vars = 13046 × 33538
    obs: 'barcodes', 'batch_id', 'cell_name', 'cell_uuid', 'chip_id', 'hto_barcode', 'hto_category', 'n_genes', 'n_mito_umis', 'n_reads', 'n_umis', 'original_barcodes', 'pbmc_sample_id', 'pool_id', 'well_id', 'sample.sampleKitGuid', 'cohort.cohortGuid', 'subject.subjectGuid', 'subject.biologicalSex', 'subject.race', 'subject.ethnicity', 'subject.birthYear', 'sample.visitName', 'sample.drawDate', 'specimens.specimenGuid', 'specimens.specimenType', 'file.id', 'file.batchID', 'subset_grp', 'predicted_doublet', 'doublet_score', 'AIFI_L1', 'AIFI_L1_score', 'AIFI_L2', 'AIFI_L2_score', 'AIFI_L3', 'AIFI_L3_score', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mito', 'log1p_total_counts_mito', 'pct_counts_mito', 'leiden_2'
    uns: 'hvg', 'leiden', 'log1p', 'neighbors', 'pca', 'rank_genes_groups', 'umap'
    obsm: 'X_pca', 'X_umap'
    obsp: 'connectivities', 'distances'
Doublet clusters: ['18', '22', '16']
leiden_2            0     1    2    3    4    5    6    7    8    9  ...   13  \
doublets_manual                                                      ...
no               1164  1057  924  913  795  761  733  714  690  684  ...  542
yes                 0     0    0    0    0    0    0    0    0    0  ...    0

leiden_2          14   15   16   17   18   19   20  21  22
doublets_manual
no               533  478    0  223    0  194  117  86   0
yes                0    0  409    0  214    0    0   0  61

[2 rows x 23 columns]
Subsetted cells to: (13046, 33538)
Saving processed data

/opt/conda/lib/python3.10/site-packages/anndata/_core/anndata.py:1292: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c

Key: ISGpos_memory_CD4_T_cell
Value: /home/jupyter/certpro_up1/unharmonized_output/up1_cluster_unharmonize_ISGpos_memory_CD4_T_cell_2024-09-30.h5ad
AnnData object with n_obs × n_vars = 7778 × 33538
    obs: 'barcodes', 'batch_id', 'cell_name', 'cell_uuid', 'chip_id', 'hto_barcode', 'hto_category', 'n_genes', 'n_mito_umis', 'n_reads', 'n_umis', 'original_barcodes', 'pbmc_sample_id', 'pool_id', 'well_id', 'sample.sampleKitGuid', 'cohort.cohortGuid', 'subject.subjectGuid', 'subject.biologicalSex', 'subject.race', 'subject.ethnicity', 'subject.birthYear', 'sample.visitName', 'sample.drawDate', 'specimens.specimenGuid', 'specimens.specimenType', 'file.id', 'file.batchID', 'subset_grp', 'predicted_doublet', 'doublet_score', 'AIFI_L1', 'AIFI_L1_score', 'AIFI_L2', 'AIFI_L2_score', 'AIFI_L3', 'AIFI_L3_score', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mito', 'log1p_total_counts_mito', 'pct_counts_mito', 'leiden_2'
    uns: 'hvg', 'leiden', 'log1p', 'neighbors', 'pca', 'rank_genes_groups', 'umap'
    obsm: 'X_pca', 'X_umap'
    obsp: 'connectivities', 'distances'
Doublet clusters: ['24', '15', '19', '22']
leiden_2           0    1    2    3    4    5    6    7    8    9  ...   15  \
doublets_manual                                                    ...
no               723  620  617  611  559  524  472  462  455  358  ...    0
yes                0    0    0    0    0    0    0    0    0    0  ...  180

leiden_2          16   17   18   19  20  21  22  23  24
doublets_manual
no               157  149  136    0  94  90   0  52   0
yes                0    0    0  104   0   0  63   0  19

[2 rows x 25 columns]
Subsetted cells to: (7778, 33538)
Saving processed data

/opt/conda/lib/python3.10/site-packages/anndata/_core/anndata.py:1292: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c

Key: Core_naive_CD4_T_cell
Value: /home/jupyter/certpro_up1/unharmonized_output/up1_cluster_unharmonize_Core_naive_CD4_T_cell_2024-09-30.h5ad
AnnData object with n_obs × n_vars = 850888 × 33538
    obs: 'barcodes', 'batch_id', 'cell_name', 'cell_uuid', 'chip_id', 'hto_barcode', 'hto_category', 'n_genes', 'n_mito_umis', 'n_reads', 'n_umis', 'original_barcodes', 'pbmc_sample_id', 'pool_id', 'well_id', 'sample.sampleKitGuid', 'cohort.cohortGuid', 'subject.subjectGuid', 'subject.biologicalSex', 'subject.race', 'subject.ethnicity', 'subject.birthYear', 'sample.visitName', 'sample.drawDate', 'specimens.specimenGuid', 'specimens.specimenType', 'file.id', 'file.batchID', 'subset_grp', 'predicted_doublet', 'doublet_score', 'AIFI_L1', 'AIFI_L1_score', 'AIFI_L2', 'AIFI_L2_score', 'AIFI_L3', 'AIFI_L3_score', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mito', 'log1p_total_counts_mito', 'pct_counts_mito', 'leiden_2'
    uns: 'hvg', 'leiden', 'log1p', 'neighbors', 'pca', 'rank_genes_groups', 'umap'
    obsm: 'X_pca', 'X_umap'
    obsp: 'connectivities', 'distances'
Doublet clusters: ['16', '17', '18', '23', '21', '22']
leiden_2             0      1      2      3      4      5      6      7  \
doublets_manual
no               84999  71893  68713  67034  62945  55141  52183  45092
yes                  0      0      0      0      0      0      0      0

leiden_2             8      9  ...     15     16     17     18     19    20  \
doublets_manual                ...
no               43544  42572  ...  18420      0      0      0  12059  9473
yes                  0      0  ...      0  16473  12867  12079      0     0

leiden_2           21    22    23  24
doublets_manual
no                  0     0     0   4
yes              9181  8740  7113   0

[2 rows x 25 columns]
Subsetted cells to: (850888, 33538)
Saving processed data

/opt/conda/lib/python3.10/site-packages/anndata/_core/anndata.py:1292: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c

Key: GZMBneg_CD27neg_EM_CD4_T_cell
Value: /home/jupyter/certpro_up1/unharmonized_output/up1_cluster_unharmonize_GZMBneg_CD27neg_EM_CD4_T_cell_2024-09-30.h5ad
AnnData object with n_obs × n_vars = 67463 × 33538
    obs: 'barcodes', 'batch_id', 'cell_name', 'cell_uuid', 'chip_id', 'hto_barcode', 'hto_category', 'n_genes', 'n_mito_umis', 'n_reads', 'n_umis', 'original_barcodes', 'pbmc_sample_id', 'pool_id', 'well_id', 'sample.sampleKitGuid', 'cohort.cohortGuid', 'subject.subjectGuid', 'subject.biologicalSex', 'subject.race', 'subject.ethnicity', 'subject.birthYear', 'sample.visitName', 'sample.drawDate', 'specimens.specimenGuid', 'specimens.specimenType', 'file.id', 'file.batchID', 'subset_grp', 'predicted_doublet', 'doublet_score', 'AIFI_L1', 'AIFI_L1_score', 'AIFI_L2', 'AIFI_L2_score', 'AIFI_L3', 'AIFI_L3_score', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mito', 'log1p_total_counts_mito', 'pct_counts_mito', 'leiden_2'
    uns: 'hvg', 'leiden', 'log1p', 'neighbors', 'pca', 'rank_genes_groups', 'umap'
    obsm: 'X_pca', 'X_umap'
    obsp: 'connectivities', 'distances'
Doublet clusters: ['16', '21', '22', '23', '24']
leiden_2            0     1     2     3     4     5     6     7     8     9  \
doublets_manual
no               5179  4988  4834  4611  4465  4060  4052  3553  3223  3096
yes                 0     0     0     0     0     0     0     0     0     0

leiden_2         ...    17    18    19    20    21   22   23   24   25  26
doublets_manual  ...
no               ...  1641  1424  1390  1339     0    0    0    0  212  14
yes              ...     0     0     0     0  1095  814  235  216    0   0

[2 rows x 27 columns]
Subsetted cells to: (67463, 33538)
Saving processed data

/opt/conda/lib/python3.10/site-packages/anndata/_core/anndata.py:1292: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c

Key: cDC1
Value: /home/jupyter/certpro_up1/unharmonized_output/up1_cluster_unharmonize_cDC1_2024-09-30.h5ad
AnnData object with n_obs × n_vars = 1645 × 33538
    obs: 'barcodes', 'batch_id', 'cell_name', 'cell_uuid', 'chip_id', 'hto_barcode', 'hto_category', 'n_genes', 'n_mito_umis', 'n_reads', 'n_umis', 'original_barcodes', 'pbmc_sample_id', 'pool_id', 'well_id', 'sample.sampleKitGuid', 'cohort.cohortGuid', 'subject.subjectGuid', 'subject.biologicalSex', 'subject.race', 'subject.ethnicity', 'subject.birthYear', 'sample.visitName', 'sample.drawDate', 'specimens.specimenGuid', 'specimens.specimenType', 'file.id', 'file.batchID', 'subset_grp', 'predicted_doublet', 'doublet_score', 'AIFI_L1', 'AIFI_L1_score', 'AIFI_L2', 'AIFI_L2_score', 'AIFI_L3', 'AIFI_L3_score', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mito', 'log1p_total_counts_mito', 'pct_counts_mito', 'leiden_2'
    uns: 'hvg', 'leiden', 'log1p', 'neighbors', 'pca', 'rank_genes_groups', 'umap'
    obsm: 'X_pca', 'X_umap'
    obsp: 'connectivities', 'distances'
Doublet clusters: ['15', '10', '9', '16']
leiden_2           0    1    2    3    4    5    6    7    8   9  10  11  12  \
doublets_manual
no               178  164  148  140  140  137  125  111  102   0   0  70  51
yes                0    0    0    0    0    0    0    0    0  83  80   0   0

leiden_2         13  14  15  16
doublets_manual
no               48  37   0   0
yes               0   0  16  15
Subsetted cells to: (1645, 33538)
Saving processed data

/opt/conda/lib/python3.10/site-packages/anndata/_core/anndata.py:1292: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c

Key: Memory_CD4_Treg
Value: /home/jupyter/certpro_up1/unharmonized_output/up1_cluster_unharmonize_Memory_CD4_Treg_2024-09-30.h5ad
AnnData object with n_obs × n_vars = 29943 × 33538
    obs: 'barcodes', 'batch_id', 'cell_name', 'cell_uuid', 'chip_id', 'hto_barcode', 'hto_category', 'n_genes', 'n_mito_umis', 'n_reads', 'n_umis', 'original_barcodes', 'pbmc_sample_id', 'pool_id', 'well_id', 'sample.sampleKitGuid', 'cohort.cohortGuid', 'subject.subjectGuid', 'subject.biologicalSex', 'subject.race', 'subject.ethnicity', 'subject.birthYear', 'sample.visitName', 'sample.drawDate', 'specimens.specimenGuid', 'specimens.specimenType', 'file.id', 'file.batchID', 'subset_grp', 'predicted_doublet', 'doublet_score', 'AIFI_L1', 'AIFI_L1_score', 'AIFI_L2', 'AIFI_L2_score', 'AIFI_L3', 'AIFI_L3_score', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mito', 'log1p_total_counts_mito', 'pct_counts_mito', 'leiden_2'
    uns: 'hvg', 'leiden', 'log1p', 'neighbors', 'pca', 'rank_genes_groups', 'umap'
    obsm: 'X_pca', 'X_umap'
    obsp: 'connectivities', 'distances'
Doublet clusters: ['19', '7']
leiden_2            0     1     2     3     4     5     6     7     8     9  \
doublets_manual
no               2584  2376  2199  2011  1971  1913  1839     0  1738  1710
yes                 0     0     0     0     0     0     0  1797     0     0

leiden_2         ...    13    14   15   16   17   18   19   20   21  22
doublets_manual  ...
no               ...  1222  1095  840  706  461  399    0  283  104  82
yes              ...     0     0    0    0    0    0  323    0    0   0

[2 rows x 23 columns]
Subsetted cells to: (29943, 33538)
Saving processed data

/opt/conda/lib/python3.10/site-packages/anndata/_core/anndata.py:1292: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c

Key: pDC
Value: /home/jupyter/certpro_up1/unharmonized_output/up1_cluster_unharmonize_pDC_2024-09-30.h5ad
AnnData object with n_obs × n_vars = 21701 × 33538
    obs: 'barcodes', 'batch_id', 'cell_name', 'cell_uuid', 'chip_id', 'hto_barcode', 'hto_category', 'n_genes', 'n_mito_umis', 'n_reads', 'n_umis', 'original_barcodes', 'pbmc_sample_id', 'pool_id', 'well_id', 'sample.sampleKitGuid', 'cohort.cohortGuid', 'subject.subjectGuid', 'subject.biologicalSex', 'subject.race', 'subject.ethnicity', 'subject.birthYear', 'sample.visitName', 'sample.drawDate', 'specimens.specimenGuid', 'specimens.specimenType', 'file.id', 'file.batchID', 'subset_grp', 'predicted_doublet', 'doublet_score', 'AIFI_L1', 'AIFI_L1_score', 'AIFI_L2', 'AIFI_L2_score', 'AIFI_L3', 'AIFI_L3_score', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mito', 'log1p_total_counts_mito', 'pct_counts_mito', 'leiden_2'
    uns: 'hvg', 'leiden', 'log1p', 'neighbors', 'pca', 'rank_genes_groups', 'umap'
    obsm: 'X_pca', 'X_umap'
    obsp: 'connectivities', 'distances'
Doublet clusters: ['15', '17', '20', '22', '21', '23', '13']
leiden_2            0     1     2     3     4     5     6     7     8     9  \
doublets_manual
no               1933  1655  1627  1458  1243  1214  1213  1152  1147  1037
yes                 0     0     0     0     0     0     0     0     0     0

leiden_2         ...   14   15   16   17   18   19   20   21   22  23
doublets_manual  ...
no               ...  717    0  647    0  504  435    0    0    0   0
yes              ...    0  679    0  537    0    0  320  261  140  90

[2 rows x 24 columns]
Subsetted cells to: (21701, 33538)
Saving processed data

/opt/conda/lib/python3.10/site-packages/anndata/_core/anndata.py:1292: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c

Key: CLP_cell
Value: /home/jupyter/certpro_up1/unharmonized_output/up1_cluster_unharmonize_CLP_cell_2024-09-30.h5ad
AnnData object with n_obs × n_vars = 952 × 33538
    obs: 'barcodes', 'batch_id', 'cell_name', 'cell_uuid', 'chip_id', 'hto_barcode', 'hto_category', 'n_genes', 'n_mito_umis', 'n_reads', 'n_umis', 'original_barcodes', 'pbmc_sample_id', 'pool_id', 'well_id', 'sample.sampleKitGuid', 'cohort.cohortGuid', 'subject.subjectGuid', 'subject.biologicalSex', 'subject.race', 'subject.ethnicity', 'subject.birthYear', 'sample.visitName', 'sample.drawDate', 'specimens.specimenGuid', 'specimens.specimenType', 'file.id', 'file.batchID', 'subset_grp', 'predicted_doublet', 'doublet_score', 'AIFI_L1', 'AIFI_L1_score', 'AIFI_L2', 'AIFI_L2_score', 'AIFI_L3', 'AIFI_L3_score', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mito', 'log1p_total_counts_mito', 'pct_counts_mito', 'leiden_2'
    uns: 'hvg', 'leiden', 'log1p', 'neighbors', 'pca', 'rank_genes_groups', 'umap'
    obsm: 'X_pca', 'X_umap'
    obsp: 'connectivities', 'distances'
Doublet clusters: ['8', '0', '5']
leiden_2           0    1    2   3   4   5   6   7   8   9  10  11
doublets_manual
no                 0  115  104  93  79   0  76  73   0  56  50  50
yes              117    0    0   0   0  79   0   0  60   0   0   0
Subsetted cells to: (952, 33538)
Saving processed data

/opt/conda/lib/python3.10/site-packages/anndata/_core/anndata.py:1292: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c

Key: BaEoMaP_cell
Value: /home/jupyter/certpro_up1/unharmonized_output/up1_cluster_unharmonize_BaEoMaP_cell_2024-09-30.h5ad
AnnData object with n_obs × n_vars = 139 × 33538
    obs: 'barcodes', 'batch_id', 'cell_name', 'cell_uuid', 'chip_id', 'hto_barcode', 'hto_category', 'n_genes', 'n_mito_umis', 'n_reads', 'n_umis', 'original_barcodes', 'pbmc_sample_id', 'pool_id', 'well_id', 'sample.sampleKitGuid', 'cohort.cohortGuid', 'subject.subjectGuid', 'subject.biologicalSex', 'subject.race', 'subject.ethnicity', 'subject.birthYear', 'sample.visitName', 'sample.drawDate', 'specimens.specimenGuid', 'specimens.specimenType', 'file.id', 'file.batchID', 'subset_grp', 'predicted_doublet', 'doublet_score', 'AIFI_L1', 'AIFI_L1_score', 'AIFI_L2', 'AIFI_L2_score', 'AIFI_L3', 'AIFI_L3_score', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mito', 'log1p_total_counts_mito', 'pct_counts_mito', 'leiden_2'
    uns: 'hvg', 'leiden', 'log1p', 'neighbors', 'pca', 'rank_genes_groups', 'umap'
    obsm: 'X_pca', 'X_umap'
    obsp: 'connectivities', 'distances'
Doublet clusters: []
The list is empty
leiden_2          0   1   2   3   4   5   6  7  8  9  10  11  12  13
doublets_manual
no               23  16  14  13  11  10  10  8  8  8   6   5   5   2
Subsetted cells to: (139, 33538)
Saving processed data

/opt/conda/lib/python3.10/site-packages/anndata/_core/anndata.py:1292: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c

Key: ISGpos_naive_CD8_T_cell
Value: /home/jupyter/certpro_up1/unharmonized_output/up1_cluster_unharmonize_ISGpos_naive_CD8_T_cell_2024-09-30.h5ad
AnnData object with n_obs × n_vars = 4076 × 33538
    obs: 'barcodes', 'batch_id', 'cell_name', 'cell_uuid', 'chip_id', 'hto_barcode', 'hto_category', 'n_genes', 'n_mito_umis', 'n_reads', 'n_umis', 'original_barcodes', 'pbmc_sample_id', 'pool_id', 'well_id', 'sample.sampleKitGuid', 'cohort.cohortGuid', 'subject.subjectGuid', 'subject.biologicalSex', 'subject.race', 'subject.ethnicity', 'subject.birthYear', 'sample.visitName', 'sample.drawDate', 'specimens.specimenGuid', 'specimens.specimenType', 'file.id', 'file.batchID', 'subset_grp', 'predicted_doublet', 'doublet_score', 'AIFI_L1', 'AIFI_L1_score', 'AIFI_L2', 'AIFI_L2_score', 'AIFI_L3', 'AIFI_L3_score', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mito', 'log1p_total_counts_mito', 'pct_counts_mito', 'leiden_2'
    uns: 'hvg', 'leiden', 'log1p', 'neighbors', 'pca', 'rank_genes_groups', 'umap'
    obsm: 'X_pca', 'X_umap'
    obsp: 'connectivities', 'distances'
Doublet clusters: ['15']
leiden_2           0    1    2    3    4    5    6    7    8    9   10   11  \
doublets_manual
no               472  343  322  318  314  255  224  196  185  182  174  154
yes                0    0    0    0    0    0    0    0    0    0    0    0

leiden_2          12   13   14   15   16   17  18  19
doublets_manual
no               140  136  133    0  107  101  97  94
yes                0    0    0  129    0    0   0   0
Subsetted cells to: (4076, 33538)
Saving processed data

/opt/conda/lib/python3.10/site-packages/anndata/_core/anndata.py:1292: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c

Key: Proliferating_T_cell
Value: /home/jupyter/certpro_up1/unharmonized_output/up1_cluster_unharmonize_Proliferating_T_cell_2024-09-30.h5ad
AnnData object with n_obs × n_vars = 7280 × 33538
    obs: 'barcodes', 'batch_id', 'cell_name', 'cell_uuid', 'chip_id', 'hto_barcode', 'hto_category', 'n_genes', 'n_mito_umis', 'n_reads', 'n_umis', 'original_barcodes', 'pbmc_sample_id', 'pool_id', 'well_id', 'sample.sampleKitGuid', 'cohort.cohortGuid', 'subject.subjectGuid', 'subject.biologicalSex', 'subject.race', 'subject.ethnicity', 'subject.birthYear', 'sample.visitName', 'sample.drawDate', 'specimens.specimenGuid', 'specimens.specimenType', 'file.id', 'file.batchID', 'subset_grp', 'predicted_doublet', 'doublet_score', 'AIFI_L1', 'AIFI_L1_score', 'AIFI_L2', 'AIFI_L2_score', 'AIFI_L3', 'AIFI_L3_score', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mito', 'log1p_total_counts_mito', 'pct_counts_mito', 'leiden_2'
    uns: 'hvg', 'leiden', 'log1p', 'neighbors', 'pca', 'rank_genes_groups', 'umap'
    obsm: 'X_pca', 'X_umap'
    obsp: 'connectivities', 'distances'
Doublet clusters: ['13', '22', '25']
leiden_2           0    1    2    3    4    5    6    7    8    9  ...   16  \
doublets_manual                                                    ...
no               647  644  516  473  456  381  331  330  313  312  ...  217
yes                0    0    0    0    0    0    0    0    0    0  ...    0

leiden_2          17   18   19   20   21  22  23  24  25
doublets_manual
no               199  178  164  151  101   0  86  78   0
yes                0    0    0    0    0  91   0   0  35

[2 rows x 26 columns]
Subsetted cells to: (7280, 33538)
Saving processed data

/opt/conda/lib/python3.10/site-packages/anndata/_core/anndata.py:1292: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c

Key: Core_naive_CD8_T_cell
Value: /home/jupyter/certpro_up1/unharmonized_output/up1_cluster_unharmonize_Core_naive_CD8_T_cell_2024-09-30.h5ad
AnnData object with n_obs × n_vars = 485383 × 33538
    obs: 'barcodes', 'batch_id', 'cell_name', 'cell_uuid', 'chip_id', 'hto_barcode', 'hto_category', 'n_genes', 'n_mito_umis', 'n_reads', 'n_umis', 'original_barcodes', 'pbmc_sample_id', 'pool_id', 'well_id', 'sample.sampleKitGuid', 'cohort.cohortGuid', 'subject.subjectGuid', 'subject.biologicalSex', 'subject.race', 'subject.ethnicity', 'subject.birthYear', 'sample.visitName', 'sample.drawDate', 'specimens.specimenGuid', 'specimens.specimenType', 'file.id', 'file.batchID', 'subset_grp', 'predicted_doublet', 'doublet_score', 'AIFI_L1', 'AIFI_L1_score', 'AIFI_L2', 'AIFI_L2_score', 'AIFI_L3', 'AIFI_L3_score', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mito', 'log1p_total_counts_mito', 'pct_counts_mito', 'leiden_2'
    uns: 'hvg', 'leiden', 'log1p', 'neighbors', 'pca', 'rank_genes_groups', 'umap'
    obsm: 'X_pca', 'X_umap'
    obsp: 'connectivities', 'distances'
Doublet clusters: ['16']
leiden_2             0      1      2      3      4      5      6      7  \
doublets_manual
no               49989  45022  41873  41297  37517  30936  28738  28627
yes                  0      0      0      0      0      0      0      0

leiden_2             8      9     10     11     12     13     14    15    16  \
doublets_manual
no               27462  26288  26000  24394  23986  20521  20207  6405     0
yes                  0      0      0      0      0      0      0     0  2748

leiden_2           17   18
doublets_manual
no               2702  671
yes                 0    0
Subsetted cells to: (485383, 33538)
Saving processed data

/opt/conda/lib/python3.10/site-packages/anndata/_core/anndata.py:1292: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c

Key: Core_naive_B_cell
Value: /home/jupyter/certpro_up1/unharmonized_output/up1_cluster_unharmonize_Core_naive_B_cell_2024-09-30.h5ad
AnnData object with n_obs × n_vars = 285478 × 33538
    obs: 'barcodes', 'batch_id', 'cell_name', 'cell_uuid', 'chip_id', 'hto_barcode', 'hto_category', 'n_genes', 'n_mito_umis', 'n_reads', 'n_umis', 'original_barcodes', 'pbmc_sample_id', 'pool_id', 'well_id', 'sample.sampleKitGuid', 'cohort.cohortGuid', 'subject.subjectGuid', 'subject.biologicalSex', 'subject.race', 'subject.ethnicity', 'subject.birthYear', 'sample.visitName', 'sample.drawDate', 'specimens.specimenGuid', 'specimens.specimenType', 'file.id', 'file.batchID', 'subset_grp', 'predicted_doublet', 'doublet_score', 'AIFI_L1', 'AIFI_L1_score', 'AIFI_L2', 'AIFI_L2_score', 'AIFI_L3', 'AIFI_L3_score', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mito', 'log1p_total_counts_mito', 'pct_counts_mito', 'leiden_2'
    uns: 'hvg', 'leiden', 'log1p', 'neighbors', 'pca', 'rank_genes_groups', 'umap'
    obsm: 'X_pca', 'X_umap'
    obsp: 'connectivities', 'distances'
Doublet clusters: ['17', '21']
leiden_2             0      1      2      3      4      5      6      7  \
doublets_manual
no               24617  23029  22744  21151  20631  19849  18614  18502
yes                  0      0      0      0      0      0      0      0

leiden_2             8      9  ...     13    14    15    16    17    18    19  \
doublets_manual                ...
no               17938  15147  ...  10582  8923  8492  5501     0  1961  1386
yes                  0      0  ...      0     0     0     0  4562     0     0

leiden_2          20   21  22
doublets_manual
no               900    0   9
yes                0  606   0

[2 rows x 23 columns]
Subsetted cells to: (285478, 33538)
Saving processed data

/opt/conda/lib/python3.10/site-packages/anndata/_core/anndata.py:1292: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c

Key: Intermediate_monocyte
Value: /home/jupyter/certpro_up1/unharmonized_output/up1_cluster_unharmonize_Intermediate_monocyte_2024-09-30.h5ad
AnnData object with n_obs × n_vars = 8211 × 33538
    obs: 'barcodes', 'batch_id', 'cell_name', 'cell_uuid', 'chip_id', 'hto_barcode', 'hto_category', 'n_genes', 'n_mito_umis', 'n_reads', 'n_umis', 'original_barcodes', 'pbmc_sample_id', 'pool_id', 'well_id', 'sample.sampleKitGuid', 'cohort.cohortGuid', 'subject.subjectGuid', 'subject.biologicalSex', 'subject.race', 'subject.ethnicity', 'subject.birthYear', 'sample.visitName', 'sample.drawDate', 'specimens.specimenGuid', 'specimens.specimenType', 'file.id', 'file.batchID', 'subset_grp', 'predicted_doublet', 'doublet_score', 'AIFI_L1', 'AIFI_L1_score', 'AIFI_L2', 'AIFI_L2_score', 'AIFI_L3', 'AIFI_L3_score', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mito', 'log1p_total_counts_mito', 'pct_counts_mito', 'leiden_2'
    uns: 'hvg', 'leiden', 'log1p', 'neighbors', 'pca', 'rank_genes_groups', 'umap'
    obsm: 'X_pca', 'X_umap'
    obsp: 'connectivities', 'distances'
Doublet clusters: ['1', '3', '18']
leiden_2           0    1    2    3    4    5    6    7    8    9  ...   11  \
doublets_manual                                                    ...
no               699    0  634    0  570  549  492  451  399  379  ...  361
yes                0  641    0  607    0    0    0    0    0    0  ...    0

leiden_2          12   13   14   15   16   17   18   19   20
doublets_manual
no               351  340  312  261  229  177    0  134  111
yes                0    0    0    0    0    0  142    0    0

[2 rows x 21 columns]
Subsetted cells to: (8211, 33538)
Saving processed data

/opt/conda/lib/python3.10/site-packages/anndata/_core/anndata.py:1292: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c

Key: Erythrocyte
Value: /home/jupyter/certpro_up1/unharmonized_output/up1_cluster_unharmonize_Erythrocyte_2024-09-30.h5ad
AnnData object with n_obs × n_vars = 13051 × 33538
    obs: 'barcodes', 'batch_id', 'cell_name', 'cell_uuid', 'chip_id', 'hto_barcode', 'hto_category', 'n_genes', 'n_mito_umis', 'n_reads', 'n_umis', 'original_barcodes', 'pbmc_sample_id', 'pool_id', 'well_id', 'sample.sampleKitGuid', 'cohort.cohortGuid', 'subject.subjectGuid', 'subject.biologicalSex', 'subject.race', 'subject.ethnicity', 'subject.birthYear', 'sample.visitName', 'sample.drawDate', 'specimens.specimenGuid', 'specimens.specimenType', 'file.id', 'file.batchID', 'subset_grp', 'predicted_doublet', 'doublet_score', 'AIFI_L1', 'AIFI_L1_score', 'AIFI_L2', 'AIFI_L2_score', 'AIFI_L3', 'AIFI_L3_score', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mito', 'log1p_total_counts_mito', 'pct_counts_mito', 'leiden_2'
    uns: 'hvg', 'leiden', 'log1p', 'neighbors', 'pca', 'rank_genes_groups', 'umap'
    obsm: 'X_pca', 'X_umap'
    obsp: 'connectivities', 'distances'
Doublet clusters: ['0', '1', '2', '3', '5', '6', '7', '8', '9', '10', '11', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23']
leiden_2            0     1    2    3    4    5    6    7    8    9  ...   14  \
doublets_manual                                                      ...
no                  0     0    0    0  765    0    0    0    0    0  ...    0
yes              1531  1015  966  966    0  662  658  631  614  583  ...  426

leiden_2          15   16   17   18   19   20   21  22  23
doublets_manual
no                 0    0    0    0    0    0    0   0   0
yes              383  381  343  327  290  180  180  83  30

[2 rows x 24 columns]
Subsetted cells to: (13051, 33538)
Saving processed data

/opt/conda/lib/python3.10/site-packages/anndata/_core/anndata.py:1292: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c

Key: HLAnegDRhi_cDC2
Value: /home/jupyter/certpro_up1/unharmonized_output/up1_cluster_unharmonize_HLAnegDRhi_cDC2_2024-09-30.h5ad
AnnData object with n_obs × n_vars = 16118 × 33538
    obs: 'barcodes', 'batch_id', 'cell_name', 'cell_uuid', 'chip_id', 'hto_barcode', 'hto_category', 'n_genes', 'n_mito_umis', 'n_reads', 'n_umis', 'original_barcodes', 'pbmc_sample_id', 'pool_id', 'well_id', 'sample.sampleKitGuid', 'cohort.cohortGuid', 'subject.subjectGuid', 'subject.biologicalSex', 'subject.race', 'subject.ethnicity', 'subject.birthYear', 'sample.visitName', 'sample.drawDate', 'specimens.specimenGuid', 'specimens.specimenType', 'file.id', 'file.batchID', 'subset_grp', 'predicted_doublet', 'doublet_score', 'AIFI_L1', 'AIFI_L1_score', 'AIFI_L2', 'AIFI_L2_score', 'AIFI_L3', 'AIFI_L3_score', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mito', 'log1p_total_counts_mito', 'pct_counts_mito', 'leiden_2'
    uns: 'hvg', 'leiden', 'log1p', 'neighbors', 'pca', 'rank_genes_groups', 'umap'
    obsm: 'X_pca', 'X_umap'
    obsp: 'connectivities', 'distances'
Doublet clusters: ['23', '25', '14', '9', '22']
leiden_2            0     1     2    3    4    5    6    7    8    9  ...  \
doublets_manual                                                       ...
no               1299  1060  1027  952  905  883  852  845  835    0  ...
yes                 0     0     0    0    0    0    0    0    0  825  ...

leiden_2          16   17   18   19   20   21   22  23  24  25
doublets_manual
no               617  391  366  283  220  172    0   0  67   0
yes                0    0    0    0    0    0  121  98   0  43

[2 rows x 26 columns]
Subsetted cells to: (16118, 33538)
Saving processed data

/opt/conda/lib/python3.10/site-packages/anndata/_core/anndata.py:1292: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c

Key: Core_CD16_monocyte
Value: /home/jupyter/certpro_up1/unharmonized_output/up1_cluster_unharmonize_Core_CD16_monocyte_2024-09-30.h5ad
AnnData object with n_obs × n_vars = 41989 × 33538
    obs: 'barcodes', 'batch_id', 'cell_name', 'cell_uuid', 'chip_id', 'hto_barcode', 'hto_category', 'n_genes', 'n_mito_umis', 'n_reads', 'n_umis', 'original_barcodes', 'pbmc_sample_id', 'pool_id', 'well_id', 'sample.sampleKitGuid', 'cohort.cohortGuid', 'subject.subjectGuid', 'subject.biologicalSex', 'subject.race', 'subject.ethnicity', 'subject.birthYear', 'sample.visitName', 'sample.drawDate', 'specimens.specimenGuid', 'specimens.specimenType', 'file.id', 'file.batchID', 'subset_grp', 'predicted_doublet', 'doublet_score', 'AIFI_L1', 'AIFI_L1_score', 'AIFI_L2', 'AIFI_L2_score', 'AIFI_L3', 'AIFI_L3_score', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mito', 'log1p_total_counts_mito', 'pct_counts_mito', 'leiden_2'
    uns: 'hvg', 'leiden', 'log1p', 'neighbors', 'pca', 'rank_genes_groups', 'umap'
    obsm: 'X_pca', 'X_umap'
    obsp: 'connectivities', 'distances'
Doublet clusters: ['14', '15', '17', '19']
leiden_2            0     1     2     3     4     5     6     7     8     9  \
doublets_manual
no               4275  3218  3190  2727  2562  2529  2489  2466  2206  2073
yes                 0     0     0     0     0     0     0     0     0     0

leiden_2         ...    12    13    14    15   16   17   18   19   20   21
doublets_manual  ...
no               ...  1754  1688     0     0  958    0  792    0  567  274
yes              ...     0     0  1603  1380    0  930    0  590    0    0

[2 rows x 22 columns]
Subsetted cells to: (41989, 33538)
Saving processed data

/opt/conda/lib/python3.10/site-packages/anndata/_core/anndata.py:1292: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c

Key: CD95_memory_B_cell
Value: /home/jupyter/certpro_up1/unharmonized_output/up1_cluster_unharmonize_CD95_memory_B_cell_2024-09-30.h5ad
AnnData object with n_obs × n_vars = 5179 × 33538
    obs: 'barcodes', 'batch_id', 'cell_name', 'cell_uuid', 'chip_id', 'hto_barcode', 'hto_category', 'n_genes', 'n_mito_umis', 'n_reads', 'n_umis', 'original_barcodes', 'pbmc_sample_id', 'pool_id', 'well_id', 'sample.sampleKitGuid', 'cohort.cohortGuid', 'subject.subjectGuid', 'subject.biologicalSex', 'subject.race', 'subject.ethnicity', 'subject.birthYear', 'sample.visitName', 'sample.drawDate', 'specimens.specimenGuid', 'specimens.specimenType', 'file.id', 'file.batchID', 'subset_grp', 'predicted_doublet', 'doublet_score', 'AIFI_L1', 'AIFI_L1_score', 'AIFI_L2', 'AIFI_L2_score', 'AIFI_L3', 'AIFI_L3_score', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mito', 'log1p_total_counts_mito', 'pct_counts_mito', 'leiden_2'
    uns: 'hvg', 'leiden', 'log1p', 'neighbors', 'pca', 'rank_genes_groups', 'umap'
    obsm: 'X_pca', 'X_umap'
    obsp: 'connectivities', 'distances'
Doublet clusters: ['8', '13', '15']
leiden_2           0    1    2    3    4    5    6    7    8    9   10   11  \
doublets_manual
no               656  561  432  377  361  333  332  311    0  295  281  237
yes                0    0    0    0    0    0    0    0  305    0    0    0

leiden_2          12   13   14  15  16  17  18
doublets_manual
no               198    0  162   0  26  26  14
yes                0  189    0  83   0   0   0
Subsetted cells to: (5179, 33538)
Saving processed data

/opt/conda/lib/python3.10/site-packages/anndata/_core/anndata.py:1292: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c

Key: GZMKneg_CD27pos_EM_CD8_T_cell
Value: /home/jupyter/certpro_up1/unharmonized_output/up1_cluster_unharmonize_GZMKneg_CD27pos_EM_CD8_T_cell_2024-09-30.h5ad
AnnData object with n_obs × n_vars = 4432 × 33538
    obs: 'barcodes', 'batch_id', 'cell_name', 'cell_uuid', 'chip_id', 'hto_barcode', 'hto_category', 'n_genes', 'n_mito_umis', 'n_reads', 'n_umis', 'original_barcodes', 'pbmc_sample_id', 'pool_id', 'well_id', 'sample.sampleKitGuid', 'cohort.cohortGuid', 'subject.subjectGuid', 'subject.biologicalSex', 'subject.race', 'subject.ethnicity', 'subject.birthYear', 'sample.visitName', 'sample.drawDate', 'specimens.specimenGuid', 'specimens.specimenType', 'file.id', 'file.batchID', 'subset_grp', 'predicted_doublet', 'doublet_score', 'AIFI_L1', 'AIFI_L1_score', 'AIFI_L2', 'AIFI_L2_score', 'AIFI_L3', 'AIFI_L3_score', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mito', 'log1p_total_counts_mito', 'pct_counts_mito', 'leiden_2'
    uns: 'hvg', 'leiden', 'log1p', 'neighbors', 'pca', 'rank_genes_groups', 'umap'
    obsm: 'X_pca', 'X_umap'
    obsp: 'connectivities', 'distances'
Doublet clusters: ['19']
leiden_2           0    1    2    3    4    5    6    7    8    9  ...   13  \
doublets_manual                                                    ...
no               454  431  326  273  262  254  230  230  230  222  ...  159
yes                0    0    0    0    0    0    0    0    0    0  ...    0

leiden_2          14   15   16   17  18  19  20  21  22
doublets_manual
no               113  106  106  105  98   0  58  58  54
yes                0    0    0    0   0  88   0   0   0

[2 rows x 23 columns]
Subsetted cells to: (4432, 33538)
Saving processed data

/opt/conda/lib/python3.10/site-packages/anndata/_core/anndata.py:1292: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c

Key: ISGpos_CD16_monocyte
Value: /home/jupyter/certpro_up1/unharmonized_output/up1_cluster_unharmonize_ISGpos_CD16_monocyte_2024-09-30.h5ad
AnnData object with n_obs × n_vars = 8493 × 33538
    obs: 'barcodes', 'batch_id', 'cell_name', 'cell_uuid', 'chip_id', 'hto_barcode', 'hto_category', 'n_genes', 'n_mito_umis', 'n_reads', 'n_umis', 'original_barcodes', 'pbmc_sample_id', 'pool_id', 'well_id', 'sample.sampleKitGuid', 'cohort.cohortGuid', 'subject.subjectGuid', 'subject.biologicalSex', 'subject.race', 'subject.ethnicity', 'subject.birthYear', 'sample.visitName', 'sample.drawDate', 'specimens.specimenGuid', 'specimens.specimenType', 'file.id', 'file.batchID', 'subset_grp', 'predicted_doublet', 'doublet_score', 'AIFI_L1', 'AIFI_L1_score', 'AIFI_L2', 'AIFI_L2_score', 'AIFI_L3', 'AIFI_L3_score', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mito', 'log1p_total_counts_mito', 'pct_counts_mito', 'leiden_2'
    uns: 'hvg', 'leiden', 'log1p', 'neighbors', 'pca', 'rank_genes_groups', 'umap'
    obsm: 'X_pca', 'X_umap'
    obsp: 'connectivities', 'distances'
Doublet clusters: ['1', '3', '7', '15', '17', '18', '19']
leiden_2           0    1    2    3    4    5    6    7    8    9   10   11  \
doublets_manual
no               815    0  665    0  522  517  516    0  438  398  396  390
yes                0  767    0  627    0    0    0  510    0    0    0    0

leiden_2          12   13   14   15   16   17   18  19
doublets_manual
no               387  320  265    0  236    0    0   0
yes                0    0    0  250    0  225  199  50
Subsetted cells to: (8493, 33538)
Saving processed data

/opt/conda/lib/python3.10/site-packages/anndata/_core/anndata.py:1292: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c

Key: Core_memory_B_cell
Value: /home/jupyter/certpro_up1/unharmonized_output/up1_cluster_unharmonize_Core_memory_B_cell_2024-09-30.h5ad
AnnData object with n_obs × n_vars = 78152 × 33538
    obs: 'barcodes', 'batch_id', 'cell_name', 'cell_uuid', 'chip_id', 'hto_barcode', 'hto_category', 'n_genes', 'n_mito_umis', 'n_reads', 'n_umis', 'original_barcodes', 'pbmc_sample_id', 'pool_id', 'well_id', 'sample.sampleKitGuid', 'cohort.cohortGuid', 'subject.subjectGuid', 'subject.biologicalSex', 'subject.race', 'subject.ethnicity', 'subject.birthYear', 'sample.visitName', 'sample.drawDate', 'specimens.specimenGuid', 'specimens.specimenType', 'file.id', 'file.batchID', 'subset_grp', 'predicted_doublet', 'doublet_score', 'AIFI_L1', 'AIFI_L1_score', 'AIFI_L2', 'AIFI_L2_score', 'AIFI_L3', 'AIFI_L3_score', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mito', 'log1p_total_counts_mito', 'pct_counts_mito', 'leiden_2'
    uns: 'hvg', 'leiden', 'log1p', 'neighbors', 'pca', 'rank_genes_groups', 'umap'
    obsm: 'X_pca', 'X_umap'
    obsp: 'connectivities', 'distances'
Doublet clusters: ['15', '19']
leiden_2            0     1     2     3     4     5     6     7     8     9  \
doublets_manual
no               8430  7233  6553  5851  5679  5629  5084  5082  4954  4844
yes                 0     0     0     0     0     0     0     0     0     0

leiden_2         ...    13    14    15    16    17   18   19   20   21  22
doublets_manual  ...
no               ...  1657  1446     0  1227  1054  825    0  465  383   3
yes              ...     0     0  1297     0     0    0  505    0    0   0

[2 rows x 23 columns]
Subsetted cells to: (78152, 33538)
Saving processed data

/opt/conda/lib/python3.10/site-packages/anndata/_core/anndata.py:1292: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c

Key: ISGpos_CD56dim_NK_cell
Value: /home/jupyter/certpro_up1/unharmonized_output/up1_cluster_unharmonize_ISGpos_CD56dim_NK_cell_2024-09-30.h5ad
AnnData object with n_obs × n_vars = 8471 × 33538
    obs: 'barcodes', 'batch_id', 'cell_name', 'cell_uuid', 'chip_id', 'hto_barcode', 'hto_category', 'n_genes', 'n_mito_umis', 'n_reads', 'n_umis', 'original_barcodes', 'pbmc_sample_id', 'pool_id', 'well_id', 'sample.sampleKitGuid', 'cohort.cohortGuid', 'subject.subjectGuid', 'subject.biologicalSex', 'subject.race', 'subject.ethnicity', 'subject.birthYear', 'sample.visitName', 'sample.drawDate', 'specimens.specimenGuid', 'specimens.specimenType', 'file.id', 'file.batchID', 'subset_grp', 'predicted_doublet', 'doublet_score', 'AIFI_L1', 'AIFI_L1_score', 'AIFI_L2', 'AIFI_L2_score', 'AIFI_L3', 'AIFI_L3_score', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mito', 'log1p_total_counts_mito', 'pct_counts_mito', 'leiden_2'
    uns: 'hvg', 'leiden', 'log1p', 'neighbors', 'pca', 'rank_genes_groups', 'umap'
    obsm: 'X_pca', 'X_umap'
    obsp: 'connectivities', 'distances'
Doublet clusters: ['6', '7', '16', '17', '19', '20', '1', '13']
leiden_2           0    1    2    3    4    5    6    7    8    9  ...   12  \
doublets_manual                                                    ...
no               973    0  716  670  660  581    0    0  398  389  ...  316
yes                0  717    0    0    0    0  506  458    0    0  ...    0

leiden_2          13   14   15   16   17  18  19  20  21
doublets_manual
no                 0  270  229    0    0  98   0   0  37
yes              291    0    0  189  124   0  95  81   0

[2 rows x 22 columns]
Subsetted cells to: (8471, 33538)
Saving processed data

/opt/conda/lib/python3.10/site-packages/anndata/_core/anndata.py:1292: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c

Key: KLRF1neg_effector_Vd1_gdT
Value: /home/jupyter/certpro_up1/unharmonized_output/up1_cluster_unharmonize_KLRF1neg_effector_Vd1_gdT_2024-09-30.h5ad
AnnData object with n_obs × n_vars = 5670 × 33538
    obs: 'barcodes', 'batch_id', 'cell_name', 'cell_uuid', 'chip_id', 'hto_barcode', 'hto_category', 'n_genes', 'n_mito_umis', 'n_reads', 'n_umis', 'original_barcodes', 'pbmc_sample_id', 'pool_id', 'well_id', 'sample.sampleKitGuid', 'cohort.cohortGuid', 'subject.subjectGuid', 'subject.biologicalSex', 'subject.race', 'subject.ethnicity', 'subject.birthYear', 'sample.visitName', 'sample.drawDate', 'specimens.specimenGuid', 'specimens.specimenType', 'file.id', 'file.batchID', 'subset_grp', 'predicted_doublet', 'doublet_score', 'AIFI_L1', 'AIFI_L1_score', 'AIFI_L2', 'AIFI_L2_score', 'AIFI_L3', 'AIFI_L3_score', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mito', 'log1p_total_counts_mito', 'pct_counts_mito', 'leiden_2'
    uns: 'hvg', 'leiden', 'log1p', 'neighbors', 'pca', 'rank_genes_groups', 'umap'
    obsm: 'X_pca', 'X_umap'
    obsp: 'connectivities', 'distances'
Doublet clusters: ['9', '17', '19', '20']
leiden_2           0    1    2    3    4    5    6    7    8    9  ...   11  \
doublets_manual                                                    ...
no               473  453  432  410  382  378  361  352  333    0  ...  269
yes                0    0    0    0    0    0    0    0    0  286  ...    0

leiden_2          12   13   14   15   16  17  18  19  20
doublets_manual
no               236  227  202  195  139   0  81   0   0
yes                0    0    0    0    0  85   0  73  26

[2 rows x 21 columns]
Subsetted cells to: (5670, 33538)
Saving processed data

/opt/conda/lib/python3.10/site-packages/anndata/_core/anndata.py:1292: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c

Key: GZMKpos_Vd2_gdT
Value: /home/jupyter/certpro_up1/unharmonized_output/up1_cluster_unharmonize_GZMKpos_Vd2_gdT_2024-09-30.h5ad
AnnData object with n_obs × n_vars = 57517 × 33538
    obs: 'barcodes', 'batch_id', 'cell_name', 'cell_uuid', 'chip_id', 'hto_barcode', 'hto_category', 'n_genes', 'n_mito_umis', 'n_reads', 'n_umis', 'original_barcodes', 'pbmc_sample_id', 'pool_id', 'well_id', 'sample.sampleKitGuid', 'cohort.cohortGuid', 'subject.subjectGuid', 'subject.biologicalSex', 'subject.race', 'subject.ethnicity', 'subject.birthYear', 'sample.visitName', 'sample.drawDate', 'specimens.specimenGuid', 'specimens.specimenType', 'file.id', 'file.batchID', 'subset_grp', 'predicted_doublet', 'doublet_score', 'AIFI_L1', 'AIFI_L1_score', 'AIFI_L2', 'AIFI_L2_score', 'AIFI_L3', 'AIFI_L3_score', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mito', 'log1p_total_counts_mito', 'pct_counts_mito', 'leiden_2'
    uns: 'hvg', 'leiden', 'log1p', 'neighbors', 'pca', 'rank_genes_groups', 'umap'
    obsm: 'X_pca', 'X_umap'
    obsp: 'connectivities', 'distances'
Doublet clusters: ['14', '19']
leiden_2            0     1     2     3     4     5     6     7     8     9  \
doublets_manual
no               5550  5452  5183  5134  5058  4000  3971  3221  2558  2381
yes                 0     0     0     0     0     0     0     0     0     0

leiden_2         ...    13    14    15    16   17   18   19   20   21   22
doublets_manual  ...
no               ...  1856     0  1591  1302  504  466    0  350  299  106
yes              ...     0  1803     0     0    0    0  442    0    0    0

[2 rows x 23 columns]
Subsetted cells to: (57517, 33538)
Saving processed data

/opt/conda/lib/python3.10/site-packages/anndata/_core/anndata.py:1292: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c

Key: SOX4pos_naive_CD8_T_cell
Value: /home/jupyter/certpro_up1/unharmonized_output/up1_cluster_unharmonize_SOX4pos_naive_CD8_T_cell_2024-09-30.h5ad
AnnData object with n_obs × n_vars = 26703 × 33538
    obs: 'barcodes', 'batch_id', 'cell_name', 'cell_uuid', 'chip_id', 'hto_barcode', 'hto_category', 'n_genes', 'n_mito_umis', 'n_reads', 'n_umis', 'original_barcodes', 'pbmc_sample_id', 'pool_id', 'well_id', 'sample.sampleKitGuid', 'cohort.cohortGuid', 'subject.subjectGuid', 'subject.biologicalSex', 'subject.race', 'subject.ethnicity', 'subject.birthYear', 'sample.visitName', 'sample.drawDate', 'specimens.specimenGuid', 'specimens.specimenType', 'file.id', 'file.batchID', 'subset_grp', 'predicted_doublet', 'doublet_score', 'AIFI_L1', 'AIFI_L1_score', 'AIFI_L2', 'AIFI_L2_score', 'AIFI_L3', 'AIFI_L3_score', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mito', 'log1p_total_counts_mito', 'pct_counts_mito', 'leiden_2'
    uns: 'hvg', 'leiden', 'log1p', 'neighbors', 'pca', 'rank_genes_groups', 'umap'
    obsm: 'X_pca', 'X_umap'
    obsp: 'connectivities', 'distances'
Doublet clusters: ['15', '18', '13']
leiden_2            0     1     2     3     4     5     6     7     8     9  \
doublets_manual
no               3039  2901  2523  2255  1839  1727  1568  1527  1467  1431
yes                 0     0     0     0     0     0     0     0     0     0

leiden_2         ...    11   12   13   14   15   16   17   18   19   20
doublets_manual  ...
no               ...  1004  882    0  764    0  349  318    0  247  189
yes              ...     0    0  828    0  522    0    0  260    0    0

[2 rows x 21 columns]
Subsetted cells to: (26703, 33538)
Saving processed data

/opt/conda/lib/python3.10/site-packages/anndata/_core/anndata.py:1292: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c

Key: GZMKneg_CD56dim_NK_cell
Value: /home/jupyter/certpro_up1/unharmonized_output/up1_cluster_unharmonize_GZMKneg_CD56dim_NK_cell_2024-09-30.h5ad
AnnData object with n_obs × n_vars = 176507 × 33538
    obs: 'barcodes', 'batch_id', 'cell_name', 'cell_uuid', 'chip_id', 'hto_barcode', 'hto_category', 'n_genes', 'n_mito_umis', 'n_reads', 'n_umis', 'original_barcodes', 'pbmc_sample_id', 'pool_id', 'well_id', 'sample.sampleKitGuid', 'cohort.cohortGuid', 'subject.subjectGuid', 'subject.biologicalSex', 'subject.race', 'subject.ethnicity', 'subject.birthYear', 'sample.visitName', 'sample.drawDate', 'specimens.specimenGuid', 'specimens.specimenType', 'file.id', 'file.batchID', 'subset_grp', 'predicted_doublet', 'doublet_score', 'AIFI_L1', 'AIFI_L1_score', 'AIFI_L2', 'AIFI_L2_score', 'AIFI_L3', 'AIFI_L3_score', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mito', 'log1p_total_counts_mito', 'pct_counts_mito', 'leiden_2'
    uns: 'hvg', 'leiden', 'log1p', 'neighbors', 'pca', 'rank_genes_groups', 'umap'
    obsm: 'X_pca', 'X_umap'
    obsp: 'connectivities', 'distances'
Doublet clusters: ['18', '20', '24', '25']
leiden_2             0      1      2      3      4      5      6      7  \
doublets_manual
no               12405  12165  11974  11741  11415  11378  11041  10117
yes                  0      0      0      0      0      0      0      0

leiden_2             8     9  ...    18    19    20    21    22    23    24  \
doublets_manual               ...
no               10078  8381  ...     0  3604     0  2650  2642  2370     0
yes                  0     0  ...  3655     0  2996     0     0     0  1158

leiden_2           25   26   27
doublets_manual
no                  0  912  518
yes              1138    0    0

[2 rows x 28 columns]
Subsetted cells to: (176507, 33538)
Saving processed data

/opt/conda/lib/python3.10/site-packages/anndata/_core/anndata.py:1292: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c

Key: ISGpos_memory_CD8_T_cell
Value: /home/jupyter/certpro_up1/unharmonized_output/up1_cluster_unharmonize_ISGpos_memory_CD8_T_cell_2024-09-30.h5ad
AnnData object with n_obs × n_vars = 1548 × 33538
    obs: 'barcodes', 'batch_id', 'cell_name', 'cell_uuid', 'chip_id', 'hto_barcode', 'hto_category', 'n_genes', 'n_mito_umis', 'n_reads', 'n_umis', 'original_barcodes', 'pbmc_sample_id', 'pool_id', 'well_id', 'sample.sampleKitGuid', 'cohort.cohortGuid', 'subject.subjectGuid', 'subject.biologicalSex', 'subject.race', 'subject.ethnicity', 'subject.birthYear', 'sample.visitName', 'sample.drawDate', 'specimens.specimenGuid', 'specimens.specimenType', 'file.id', 'file.batchID', 'subset_grp', 'predicted_doublet', 'doublet_score', 'AIFI_L1', 'AIFI_L1_score', 'AIFI_L2', 'AIFI_L2_score', 'AIFI_L3', 'AIFI_L3_score', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mito', 'log1p_total_counts_mito', 'pct_counts_mito', 'leiden_2'
    uns: 'hvg', 'leiden', 'log1p', 'neighbors', 'pca', 'rank_genes_groups', 'umap'
    obsm: 'X_pca', 'X_umap'
    obsp: 'connectivities', 'distances'
Doublet clusters: ['16']
leiden_2           0    1    2    3    4    5    6   7   8   9  10  11  12  \
doublets_manual
no               163  144  136  134  129  111  106  97  89  87  76  66  65
yes                0    0    0    0    0    0    0   0   0   0   0   0   0

leiden_2         13  14  15  16
doublets_manual
no               45  37  33   0
yes               0   0   0  30
Subsetted cells to: (1548, 33538)
Saving processed data

/opt/conda/lib/python3.10/site-packages/anndata/_core/anndata.py:1292: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c

Key: KLRB1pos_memory_CD8_Treg
Value: /home/jupyter/certpro_up1/unharmonized_output/up1_cluster_unharmonize_KLRB1pos_memory_CD8_Treg_2024-09-30.h5ad
AnnData object with n_obs × n_vars = 613 × 33538
    obs: 'barcodes', 'batch_id', 'cell_name', 'cell_uuid', 'chip_id', 'hto_barcode', 'hto_category', 'n_genes', 'n_mito_umis', 'n_reads', 'n_umis', 'original_barcodes', 'pbmc_sample_id', 'pool_id', 'well_id', 'sample.sampleKitGuid', 'cohort.cohortGuid', 'subject.subjectGuid', 'subject.biologicalSex', 'subject.race', 'subject.ethnicity', 'subject.birthYear', 'sample.visitName', 'sample.drawDate', 'specimens.specimenGuid', 'specimens.specimenType', 'file.id', 'file.batchID', 'subset_grp', 'predicted_doublet', 'doublet_score', 'AIFI_L1', 'AIFI_L1_score', 'AIFI_L2', 'AIFI_L2_score', 'AIFI_L3', 'AIFI_L3_score', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mito', 'log1p_total_counts_mito', 'pct_counts_mito', 'leiden_2'
    uns: 'hvg', 'leiden', 'log1p', 'neighbors', 'pca', 'rank_genes_groups', 'umap'
    obsm: 'X_pca', 'X_umap'
    obsp: 'connectivities', 'distances'
Doublet clusters: []
The list is empty
leiden_2          0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  \
doublets_manual
no               52  51  51  50  50  45  42  40  40  37  32  32  21  20  18

leiden_2         15  16  17  18
doublets_manual
no               15   7   6   4
Subsetted cells to: (613, 33538)
Saving processed data

/opt/conda/lib/python3.10/site-packages/anndata/_core/anndata.py:1292: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c

Key: Type_2_polarized_memory_B_cell
Value: /home/jupyter/certpro_up1/unharmonized_output/up1_cluster_unharmonize_Type_2_polarized_memory_B_cell_2024-09-30.h5ad
AnnData object with n_obs × n_vars = 6449 × 33538
    obs: 'barcodes', 'batch_id', 'cell_name', 'cell_uuid', 'chip_id', 'hto_barcode', 'hto_category', 'n_genes', 'n_mito_umis', 'n_reads', 'n_umis', 'original_barcodes', 'pbmc_sample_id', 'pool_id', 'well_id', 'sample.sampleKitGuid', 'cohort.cohortGuid', 'subject.subjectGuid', 'subject.biologicalSex', 'subject.race', 'subject.ethnicity', 'subject.birthYear', 'sample.visitName', 'sample.drawDate', 'specimens.specimenGuid', 'specimens.specimenType', 'file.id', 'file.batchID', 'subset_grp', 'predicted_doublet', 'doublet_score', 'AIFI_L1', 'AIFI_L1_score', 'AIFI_L2', 'AIFI_L2_score', 'AIFI_L3', 'AIFI_L3_score', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mito', 'log1p_total_counts_mito', 'pct_counts_mito', 'leiden_2'
    uns: 'hvg', 'leiden', 'log1p', 'neighbors', 'pca', 'rank_genes_groups', 'umap'
    obsm: 'X_pca', 'X_umap'
    obsp: 'connectivities', 'distances'
Doublet clusters: ['17', '8']
leiden_2           0    1    2    3    4    5    6    7    8    9  ...   15  \
doublets_manual                                                    ...
no               625  564  533  499  485  485  398  364    0  273  ...  145
yes                0    0    0    0    0    0    0    0  347    0  ...    0

leiden_2          16   17  18  19  20  21  22  23  24
doublets_manual
no               118    0  92  83  64  54  47  42  23
yes                0  113   0   0   0   0   0   0   0

[2 rows x 25 columns]
Subsetted cells to: (6449, 33538)
Saving processed data

/opt/conda/lib/python3.10/site-packages/anndata/_core/anndata.py:1292: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c

Key: CD27neg_effector_B_cell
Value: /home/jupyter/certpro_up1/unharmonized_output/up1_cluster_unharmonize_CD27neg_effector_B_cell_2024-09-30.h5ad
AnnData object with n_obs × n_vars = 11104 × 33538
    obs: 'barcodes', 'batch_id', 'cell_name', 'cell_uuid', 'chip_id', 'hto_barcode', 'hto_category', 'n_genes', 'n_mito_umis', 'n_reads', 'n_umis', 'original_barcodes', 'pbmc_sample_id', 'pool_id', 'well_id', 'sample.sampleKitGuid', 'cohort.cohortGuid', 'subject.subjectGuid', 'subject.biologicalSex', 'subject.race', 'subject.ethnicity', 'subject.birthYear', 'sample.visitName', 'sample.drawDate', 'specimens.specimenGuid', 'specimens.specimenType', 'file.id', 'file.batchID', 'subset_grp', 'predicted_doublet', 'doublet_score', 'AIFI_L1', 'AIFI_L1_score', 'AIFI_L2', 'AIFI_L2_score', 'AIFI_L3', 'AIFI_L3_score', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mito', 'log1p_total_counts_mito', 'pct_counts_mito', 'leiden_2'
    uns: 'hvg', 'leiden', 'log1p', 'neighbors', 'pca', 'rank_genes_groups', 'umap'
    obsm: 'X_pca', 'X_umap'
    obsp: 'connectivities', 'distances'
Doublet clusters: ['15', '17', '22', '14', '19']
leiden_2            0    1    2    3    4    5    6    7    8    9  ...   13  \
doublets_manual                                                     ...
no               1005  867  859  856  851  798  792  785  764  645  ...  361
yes                 0    0    0    0    0    0    0    0    0    0  ...    0

leiden_2          14   15   16   17  18  19  20  21  22
doublets_manual
no                 0    0  123    0  68   0  45  28   0
yes              320  148    0  108   0  50   0   0  26

[2 rows x 23 columns]
Subsetted cells to: (11104, 33538)
Saving processed data

/opt/conda/lib/python3.10/site-packages/anndata/_core/anndata.py:1292: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c

Key: Adaptive_NK_cell
Value: /home/jupyter/certpro_up1/unharmonized_output/up1_cluster_unharmonize_Adaptive_NK_cell_2024-09-30.h5ad
AnnData object with n_obs × n_vars = 29815 × 33538
    obs: 'barcodes', 'batch_id', 'cell_name', 'cell_uuid', 'chip_id', 'hto_barcode', 'hto_category', 'n_genes', 'n_mito_umis', 'n_reads', 'n_umis', 'original_barcodes', 'pbmc_sample_id', 'pool_id', 'well_id', 'sample.sampleKitGuid', 'cohort.cohortGuid', 'subject.subjectGuid', 'subject.biologicalSex', 'subject.race', 'subject.ethnicity', 'subject.birthYear', 'sample.visitName', 'sample.drawDate', 'specimens.specimenGuid', 'specimens.specimenType', 'file.id', 'file.batchID', 'subset_grp', 'predicted_doublet', 'doublet_score', 'AIFI_L1', 'AIFI_L1_score', 'AIFI_L2', 'AIFI_L2_score', 'AIFI_L3', 'AIFI_L3_score', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mito', 'log1p_total_counts_mito', 'pct_counts_mito', 'leiden_2'
    uns: 'hvg', 'leiden', 'log1p', 'neighbors', 'pca', 'rank_genes_groups', 'umap'
    obsm: 'X_pca', 'X_umap'
    obsp: 'connectivities', 'distances'
Doublet clusters: ['14', '19', '20', '21', '17']
leiden_2            0     1     2     3     4     5     6     7     8     9  \
doublets_manual
no               2491  2354  2302  2213  2211  2081  1790  1598  1544  1280
yes                 0     0     0     0     0     0     0     0     0     0

leiden_2         ...    12    13    14   15   16   17   18   19   20   21
doublets_manual  ...
no               ...  1105  1026     0  939  870    0  770    0    0    0
yes              ...     0     0  1002    0    0  869    0  350  337  325

[2 rows x 22 columns]
Subsetted cells to: (29815, 33538)
Saving processed data

/opt/conda/lib/python3.10/site-packages/anndata/_core/anndata.py:1292: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c

Key: CD8_MAIT
Value: /home/jupyter/certpro_up1/unharmonized_output/up1_cluster_unharmonize_CD8_MAIT_2024-09-30.h5ad
AnnData object with n_obs × n_vars = 69752 × 33538
    obs: 'barcodes', 'batch_id', 'cell_name', 'cell_uuid', 'chip_id', 'hto_barcode', 'hto_category', 'n_genes', 'n_mito_umis', 'n_reads', 'n_umis', 'original_barcodes', 'pbmc_sample_id', 'pool_id', 'well_id', 'sample.sampleKitGuid', 'cohort.cohortGuid', 'subject.subjectGuid', 'subject.biologicalSex', 'subject.race', 'subject.ethnicity', 'subject.birthYear', 'sample.visitName', 'sample.drawDate', 'specimens.specimenGuid', 'specimens.specimenType', 'file.id', 'file.batchID', 'subset_grp', 'predicted_doublet', 'doublet_score', 'AIFI_L1', 'AIFI_L1_score', 'AIFI_L2', 'AIFI_L2_score', 'AIFI_L3', 'AIFI_L3_score', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mito', 'log1p_total_counts_mito', 'pct_counts_mito', 'leiden_2'
    uns: 'hvg', 'leiden', 'log1p', 'neighbors', 'pca', 'rank_genes_groups', 'umap'
    obsm: 'X_pca', 'X_umap'
    obsp: 'connectivities', 'distances'
Doublet clusters: ['19', '21', '12']
leiden_2            0     1     2     3     4     5     6     7     8     9  \
doublets_manual
no               7483  7051  6781  5522  5370  5106  4967  4490  4473  3129
yes                 0     0     0     0     0     0     0     0     0     0

leiden_2         ...    12    13    14    15    16    17   18   19   20  21
doublets_manual  ...
no               ...     0  1436  1171  1134  1020  1008  891    0  145   0
yes              ...  1544     0     0     0     0     0    0  699    0  95

[2 rows x 22 columns]
Subsetted cells to: (69752, 33538)
Saving processed data

/opt/conda/lib/python3.10/site-packages/anndata/_core/anndata.py:1292: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c

Key: KLRB1pos_memory_CD4_Treg
Value: /home/jupyter/certpro_up1/unharmonized_output/up1_cluster_unharmonize_KLRB1pos_memory_CD4_Treg_2024-09-30.h5ad
AnnData object with n_obs × n_vars = 2862 × 33538
    obs: 'barcodes', 'batch_id', 'cell_name', 'cell_uuid', 'chip_id', 'hto_barcode', 'hto_category', 'n_genes', 'n_mito_umis', 'n_reads', 'n_umis', 'original_barcodes', 'pbmc_sample_id', 'pool_id', 'well_id', 'sample.sampleKitGuid', 'cohort.cohortGuid', 'subject.subjectGuid', 'subject.biologicalSex', 'subject.race', 'subject.ethnicity', 'subject.birthYear', 'sample.visitName', 'sample.drawDate', 'specimens.specimenGuid', 'specimens.specimenType', 'file.id', 'file.batchID', 'subset_grp', 'predicted_doublet', 'doublet_score', 'AIFI_L1', 'AIFI_L1_score', 'AIFI_L2', 'AIFI_L2_score', 'AIFI_L3', 'AIFI_L3_score', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mito', 'log1p_total_counts_mito', 'pct_counts_mito', 'leiden_2'
    uns: 'hvg', 'leiden', 'log1p', 'neighbors', 'pca', 'rank_genes_groups', 'umap'
    obsm: 'X_pca', 'X_umap'
    obsp: 'connectivities', 'distances'
Doublet clusters: ['17']
leiden_2           0    1    2    3    4    5    6    7    8    9   10   11  \
doublets_manual
no               308  294  227  210  201  173  164  159  159  141  139  136
yes                0    0    0    0    0    0    0    0    0    0    0    0

leiden_2          12   13  14  15  16  17
doublets_manual
no               131  116  98  87  61   0
yes                0    0   0   0   0  58
Subsetted cells to: (2862, 33538)
Saving processed data

/opt/conda/lib/python3.10/site-packages/anndata/_core/anndata.py:1292: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c

Key: CD8aa
Value: /home/jupyter/certpro_up1/unharmonized_output/up1_cluster_unharmonize_CD8aa_2024-09-30.h5ad
AnnData object with n_obs × n_vars = 45020 × 33538
    obs: 'barcodes', 'batch_id', 'cell_name', 'cell_uuid', 'chip_id', 'hto_barcode', 'hto_category', 'n_genes', 'n_mito_umis', 'n_reads', 'n_umis', 'original_barcodes', 'pbmc_sample_id', 'pool_id', 'well_id', 'sample.sampleKitGuid', 'cohort.cohortGuid', 'subject.subjectGuid', 'subject.biologicalSex', 'subject.race', 'subject.ethnicity', 'subject.birthYear', 'sample.visitName', 'sample.drawDate', 'specimens.specimenGuid', 'specimens.specimenType', 'file.id', 'file.batchID', 'subset_grp', 'predicted_doublet', 'doublet_score', 'AIFI_L1', 'AIFI_L1_score', 'AIFI_L2', 'AIFI_L2_score', 'AIFI_L3', 'AIFI_L3_score', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mito', 'log1p_total_counts_mito', 'pct_counts_mito', 'leiden_2'
    uns: 'hvg', 'leiden', 'log1p', 'neighbors', 'pca', 'rank_genes_groups', 'umap'
    obsm: 'X_pca', 'X_umap'
    obsp: 'connectivities', 'distances'
Doublet clusters: []
The list is empty
leiden_2            0     1     2     3     4     5     6     7     8     9  \
doublets_manual
no               3891  3347  3346  3138  2974  2923  2910  2807  2779  2769

leiden_2         ...    12    13    14    15    16   17   18   19   20  21
doublets_manual  ...
no               ...  1843  1831  1710  1368  1303  857  309  262  185  65

[1 rows x 22 columns]
Subsetted cells to: (45020, 33538)
Saving processed data

/opt/conda/lib/python3.10/site-packages/anndata/_core/anndata.py:1292: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c

Key: ISGpos_naive_CD4_T_cell
Value: /home/jupyter/certpro_up1/unharmonized_output/up1_cluster_unharmonize_ISGpos_naive_CD4_T_cell_2024-09-30.h5ad
AnnData object with n_obs × n_vars = 20386 × 33538
    obs: 'barcodes', 'batch_id', 'cell_name', 'cell_uuid', 'chip_id', 'hto_barcode', 'hto_category', 'n_genes', 'n_mito_umis', 'n_reads', 'n_umis', 'original_barcodes', 'pbmc_sample_id', 'pool_id', 'well_id', 'sample.sampleKitGuid', 'cohort.cohortGuid', 'subject.subjectGuid', 'subject.biologicalSex', 'subject.race', 'subject.ethnicity', 'subject.birthYear', 'sample.visitName', 'sample.drawDate', 'specimens.specimenGuid', 'specimens.specimenType', 'file.id', 'file.batchID', 'subset_grp', 'predicted_doublet', 'doublet_score', 'AIFI_L1', 'AIFI_L1_score', 'AIFI_L2', 'AIFI_L2_score', 'AIFI_L3', 'AIFI_L3_score', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mito', 'log1p_total_counts_mito', 'pct_counts_mito', 'leiden_2'
    uns: 'hvg', 'leiden', 'log1p', 'neighbors', 'pca', 'rank_genes_groups', 'umap'
    obsm: 'X_pca', 'X_umap'
    obsp: 'connectivities', 'distances'
Doublet clusters: ['20', '21']
leiden_2            0     1     2     3     4     5     6     7     8     9  \
doublets_manual
no               1779  1775  1651  1596  1482  1466  1351  1079  1029  1005
yes                 0     0     0     0     0     0     0     0     0     0

leiden_2         ...   14   15   16   17   18   19   20  21  22  23
doublets_manual  ...
no               ...  648  565  331  309  274  253    0   0  30  27
yes              ...    0    0    0    0    0    0  241  73   0   0

[2 rows x 24 columns]
Subsetted cells to: (20386, 33538)
Saving processed data

/opt/conda/lib/python3.10/site-packages/anndata/_core/anndata.py:1292: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c

Key: KLRF1pos_effector_Vd1_gdT
Value: /home/jupyter/certpro_up1/unharmonized_output/up1_cluster_unharmonize_KLRF1pos_effector_Vd1_gdT_2024-09-30.h5ad
AnnData object with n_obs × n_vars = 3942 × 33538
    obs: 'barcodes', 'batch_id', 'cell_name', 'cell_uuid', 'chip_id', 'hto_barcode', 'hto_category', 'n_genes', 'n_mito_umis', 'n_reads', 'n_umis', 'original_barcodes', 'pbmc_sample_id', 'pool_id', 'well_id', 'sample.sampleKitGuid', 'cohort.cohortGuid', 'subject.subjectGuid', 'subject.biologicalSex', 'subject.race', 'subject.ethnicity', 'subject.birthYear', 'sample.visitName', 'sample.drawDate', 'specimens.specimenGuid', 'specimens.specimenType', 'file.id', 'file.batchID', 'subset_grp', 'predicted_doublet', 'doublet_score', 'AIFI_L1', 'AIFI_L1_score', 'AIFI_L2', 'AIFI_L2_score', 'AIFI_L3', 'AIFI_L3_score', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mito', 'log1p_total_counts_mito', 'pct_counts_mito', 'leiden_2'
    uns: 'hvg', 'leiden', 'log1p', 'neighbors', 'pca', 'rank_genes_groups', 'umap'
    obsm: 'X_pca', 'X_umap'
    obsp: 'connectivities', 'distances'
Doublet clusters: ['17', '19', '21', '16']
leiden_2           0    1    2    3    4    5    6    7    8    9  ...   13  \
doublets_manual                                                    ...
no               336  294  284  271  264  260  250  248  218  191  ...  146
yes                0    0    0    0    0    0    0    0    0    0  ...    0

leiden_2          14   15   16  17  18  19  20  21  22
doublets_manual
no               121  111    0   0  77   0  47   0  36
yes                0    0  103  78   0  50   0  46   0

[2 rows x 23 columns]
Subsetted cells to: (3942, 33538)
Saving processed data

/opt/conda/lib/python3.10/site-packages/anndata/_core/anndata.py:1292: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c

Key: ISGpos_cDC2
Value: /home/jupyter/certpro_up1/unharmonized_output/up1_cluster_unharmonize_ISGpos_cDC2_2024-09-30.h5ad
AnnData object with n_obs × n_vars = 2298 × 33538
    obs: 'barcodes', 'batch_id', 'cell_name', 'cell_uuid', 'chip_id', 'hto_barcode', 'hto_category', 'n_genes', 'n_mito_umis', 'n_reads', 'n_umis', 'original_barcodes', 'pbmc_sample_id', 'pool_id', 'well_id', 'sample.sampleKitGuid', 'cohort.cohortGuid', 'subject.subjectGuid', 'subject.biologicalSex', 'subject.race', 'subject.ethnicity', 'subject.birthYear', 'sample.visitName', 'sample.drawDate', 'specimens.specimenGuid', 'specimens.specimenType', 'file.id', 'file.batchID', 'subset_grp', 'predicted_doublet', 'doublet_score', 'AIFI_L1', 'AIFI_L1_score', 'AIFI_L2', 'AIFI_L2_score', 'AIFI_L3', 'AIFI_L3_score', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mito', 'log1p_total_counts_mito', 'pct_counts_mito', 'leiden_2'
    uns: 'hvg', 'leiden', 'log1p', 'neighbors', 'pca', 'rank_genes_groups', 'umap'
    obsm: 'X_pca', 'X_umap'
    obsp: 'connectivities', 'distances'
Doublet clusters: ['2', '14', '16', '17']
leiden_2           0    1    2    3    4    5    6    7    8    9   10   11  \
doublets_manual
no               224  208    0  179  176  163  161  159  139  126  121  120
yes                0    0  180    0    0    0    0    0    0    0    0    0

leiden_2          12  13  14  15  16  17
doublets_manual
no               101  82   0  36   0   0
yes                0   0  60   0  35  28
Subsetted cells to: (2298, 33538)
Saving processed data

/opt/conda/lib/python3.10/site-packages/anndata/_core/anndata.py:1292: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c

Key: Naive_CD4_Treg
Value: /home/jupyter/certpro_up1/unharmonized_output/up1_cluster_unharmonize_Naive_CD4_Treg_2024-09-30.h5ad
AnnData object with n_obs × n_vars = 40775 × 33538
    obs: 'barcodes', 'batch_id', 'cell_name', 'cell_uuid', 'chip_id', 'hto_barcode', 'hto_category', 'n_genes', 'n_mito_umis', 'n_reads', 'n_umis', 'original_barcodes', 'pbmc_sample_id', 'pool_id', 'well_id', 'sample.sampleKitGuid', 'cohort.cohortGuid', 'subject.subjectGuid', 'subject.biologicalSex', 'subject.race', 'subject.ethnicity', 'subject.birthYear', 'sample.visitName', 'sample.drawDate', 'specimens.specimenGuid', 'specimens.specimenType', 'file.id', 'file.batchID', 'subset_grp', 'predicted_doublet', 'doublet_score', 'AIFI_L1', 'AIFI_L1_score', 'AIFI_L2', 'AIFI_L2_score', 'AIFI_L3', 'AIFI_L3_score', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mito', 'log1p_total_counts_mito', 'pct_counts_mito', 'leiden_2'
    uns: 'hvg', 'leiden', 'log1p', 'neighbors', 'pca', 'rank_genes_groups', 'umap'
    obsm: 'X_pca', 'X_umap'
    obsp: 'connectivities', 'distances'
Doublet clusters: ['17', '18']
leiden_2            0     1     2     3     4     5     6     7     8     9  \
doublets_manual
no               4371  4196  3890  3868  3403  3193  3181  2982  2238  2087
yes                 0     0     0     0     0     0     0     0     0     0

leiden_2           10    11    12    13   14   15   16   17  18  19
doublets_manual
no               1550  1542  1375  1235  845  377  242    0   0   2
yes                 0     0     0     0    0    0    0  129  69   0
Subsetted cells to: (40775, 33538)
Saving processed data

/opt/conda/lib/python3.10/site-packages/anndata/_core/anndata.py:1292: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c

Key: ILC
Value: /home/jupyter/certpro_up1/unharmonized_output/up1_cluster_unharmonize_ILC_2024-09-30.h5ad
AnnData object with n_obs × n_vars = 2857 × 33538
    obs: 'barcodes', 'batch_id', 'cell_name', 'cell_uuid', 'chip_id', 'hto_barcode', 'hto_category', 'n_genes', 'n_mito_umis', 'n_reads', 'n_umis', 'original_barcodes', 'pbmc_sample_id', 'pool_id', 'well_id', 'sample.sampleKitGuid', 'cohort.cohortGuid', 'subject.subjectGuid', 'subject.biologicalSex', 'subject.race', 'subject.ethnicity', 'subject.birthYear', 'sample.visitName', 'sample.drawDate', 'specimens.specimenGuid', 'specimens.specimenType', 'file.id', 'file.batchID', 'subset_grp', 'predicted_doublet', 'doublet_score', 'AIFI_L1', 'AIFI_L1_score', 'AIFI_L2', 'AIFI_L2_score', 'AIFI_L3', 'AIFI_L3_score', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mito', 'log1p_total_counts_mito', 'pct_counts_mito', 'leiden_2'
    uns: 'hvg', 'leiden', 'log1p', 'neighbors', 'pca', 'rank_genes_groups', 'umap'
    obsm: 'X_pca', 'X_umap'
    obsp: 'connectivities', 'distances'
Doublet clusters: ['17']
leiden_2           0    1    2    3    4    5    6    7    8    9  ...   11  \
doublets_manual                                                    ...
no               268  229  229  216  212  176  167  157  139  133  ...  125
yes                0    0    0    0    0    0    0    0    0    0  ...    0

leiden_2          12   13   14   15  16  17  18  19  20
doublets_manual
no               113  106  104  103  71   0  45  45  44
yes                0    0    0    0   0  49   0   0   0

[2 rows x 21 columns]
Subsetted cells to: (2857, 33538)
Saving processed data

/opt/conda/lib/python3.10/site-packages/anndata/_core/anndata.py:1292: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c

Key: GZMKpos_memory_CD4_Treg
Value: /home/jupyter/certpro_up1/unharmonized_output/up1_cluster_unharmonize_GZMKpos_memory_CD4_Treg_2024-09-30.h5ad
AnnData object with n_obs × n_vars = 283 × 33538
    obs: 'barcodes', 'batch_id', 'cell_name', 'cell_uuid', 'chip_id', 'hto_barcode', 'hto_category', 'n_genes', 'n_mito_umis', 'n_reads', 'n_umis', 'original_barcodes', 'pbmc_sample_id', 'pool_id', 'well_id', 'sample.sampleKitGuid', 'cohort.cohortGuid', 'subject.subjectGuid', 'subject.biologicalSex', 'subject.race', 'subject.ethnicity', 'subject.birthYear', 'sample.visitName', 'sample.drawDate', 'specimens.specimenGuid', 'specimens.specimenType', 'file.id', 'file.batchID', 'subset_grp', 'predicted_doublet', 'doublet_score', 'AIFI_L1', 'AIFI_L1_score', 'AIFI_L2', 'AIFI_L2_score', 'AIFI_L3', 'AIFI_L3_score', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mito', 'log1p_total_counts_mito', 'pct_counts_mito', 'leiden_2'
    uns: 'hvg', 'leiden', 'log1p', 'neighbors', 'pca', 'rank_genes_groups', 'umap'
    obsm: 'X_pca', 'X_umap'
    obsp: 'connectivities', 'distances'
Doublet clusters: []
The list is empty
leiden_2          0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  \
doublets_manual
no               37  33  24  20  19  17  17  12  12  12  12  11  11  11  10

leiden_2         15  16  17  18
doublets_manual
no                8   8   5   4
Subsetted cells to: (283, 33538)
Saving processed data

/opt/conda/lib/python3.10/site-packages/anndata/_core/anndata.py:1292: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c

Key: Transitional_B_cell
Value: /home/jupyter/certpro_up1/unharmonized_output/up1_cluster_unharmonize_Transitional_B_cell_2024-09-30.h5ad
AnnData object with n_obs × n_vars = 53456 × 33538
    obs: 'barcodes', 'batch_id', 'cell_name', 'cell_uuid', 'chip_id', 'hto_barcode', 'hto_category', 'n_genes', 'n_mito_umis', 'n_reads', 'n_umis', 'original_barcodes', 'pbmc_sample_id', 'pool_id', 'well_id', 'sample.sampleKitGuid', 'cohort.cohortGuid', 'subject.subjectGuid', 'subject.biologicalSex', 'subject.race', 'subject.ethnicity', 'subject.birthYear', 'sample.visitName', 'sample.drawDate', 'specimens.specimenGuid', 'specimens.specimenType', 'file.id', 'file.batchID', 'subset_grp', 'predicted_doublet', 'doublet_score', 'AIFI_L1', 'AIFI_L1_score', 'AIFI_L2', 'AIFI_L2_score', 'AIFI_L3', 'AIFI_L3_score', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mito', 'log1p_total_counts_mito', 'pct_counts_mito', 'leiden_2'
    uns: 'hvg', 'leiden', 'log1p', 'neighbors', 'pca', 'rank_genes_groups', 'umap'
    obsm: 'X_pca', 'X_umap'
    obsp: 'connectivities', 'distances'
Doublet clusters: ['20', '23', '22', '21', '24', '14']
leiden_2            0     1     2     3     4     5     6     7     8     9  \
doublets_manual
no               4950  4548  4534  4395  4377  3875  3384  2666  2628  2347
yes                 0     0     0     0     0     0     0     0     0     0

leiden_2         ...    16    17   18   19   20   21   22  23  24  25
doublets_manual  ...
no               ...  1231  1020  974  865    0    0    0   0   0  28
yes              ...     0     0    0    0  583  353  266  65  57   0

[2 rows x 26 columns]
Subsetted cells to: (53456, 33538)
Saving processed data

/opt/conda/lib/python3.10/site-packages/anndata/_core/anndata.py:1292: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c

Key: ISGpos_CD14_monocyte
Value: /home/jupyter/certpro_up1/unharmonized_output/up1_cluster_unharmonize_ISGpos_CD14_monocyte_2024-09-30.h5ad
AnnData object with n_obs × n_vars = 49727 × 33538
    obs: 'barcodes', 'batch_id', 'cell_name', 'cell_uuid', 'chip_id', 'hto_barcode', 'hto_category', 'n_genes', 'n_mito_umis', 'n_reads', 'n_umis', 'original_barcodes', 'pbmc_sample_id', 'pool_id', 'well_id', 'sample.sampleKitGuid', 'cohort.cohortGuid', 'subject.subjectGuid', 'subject.biologicalSex', 'subject.race', 'subject.ethnicity', 'subject.birthYear', 'sample.visitName', 'sample.drawDate', 'specimens.specimenGuid', 'specimens.specimenType', 'file.id', 'file.batchID', 'subset_grp', 'predicted_doublet', 'doublet_score', 'AIFI_L1', 'AIFI_L1_score', 'AIFI_L2', 'AIFI_L2_score', 'AIFI_L3', 'AIFI_L3_score', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mito', 'log1p_total_counts_mito', 'pct_counts_mito', 'leiden_2'
    uns: 'hvg', 'leiden', 'log1p', 'neighbors', 'pca', 'rank_genes_groups', 'umap'
    obsm: 'X_pca', 'X_umap'
    obsp: 'connectivities', 'distances'
Doublet clusters: ['4', '16', '20', '21', '23']
leiden_2            0     1     2     3     4     5     6     7     8     9  \
doublets_manual
no               4610  3926  3358  3321     0  2909  2871  2781  2642  2276
yes                 0     0     0     0  2940     0     0     0     0     0

leiden_2         ...    16    17    18   19   20   21   22   23   24  25
doublets_manual  ...
no               ...     0  1190  1046  927    0    0  321    0  125  26
yes              ...  1319     0     0    0  857  352    0  308    0   0

[2 rows x 26 columns]
Subsetted cells to: (49727, 33538)
Saving processed data

/opt/conda/lib/python3.10/site-packages/anndata/_core/anndata.py:1292: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c

Key: DN_T_cell
Value: /home/jupyter/certpro_up1/unharmonized_output/up1_cluster_unharmonize_DN_T_cell_2024-09-30.h5ad
AnnData object with n_obs × n_vars = 8281 × 33538
    obs: 'barcodes', 'batch_id', 'cell_name', 'cell_uuid', 'chip_id', 'hto_barcode', 'hto_category', 'n_genes', 'n_mito_umis', 'n_reads', 'n_umis', 'original_barcodes', 'pbmc_sample_id', 'pool_id', 'well_id', 'sample.sampleKitGuid', 'cohort.cohortGuid', 'subject.subjectGuid', 'subject.biologicalSex', 'subject.race', 'subject.ethnicity', 'subject.birthYear', 'sample.visitName', 'sample.drawDate', 'specimens.specimenGuid', 'specimens.specimenType', 'file.id', 'file.batchID', 'subset_grp', 'predicted_doublet', 'doublet_score', 'AIFI_L1', 'AIFI_L1_score', 'AIFI_L2', 'AIFI_L2_score', 'AIFI_L3', 'AIFI_L3_score', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mito', 'log1p_total_counts_mito', 'pct_counts_mito', 'leiden_2'
    uns: 'hvg', 'leiden', 'log1p', 'neighbors', 'pca', 'rank_genes_groups', 'umap'
    obsm: 'X_pca', 'X_umap'
    obsp: 'connectivities', 'distances'
Doublet clusters: ['21', '18', '20']
leiden_2           0    1    2    3    4    5    6    7    8    9  ...   12  \
doublets_manual                                                    ...
no               761  591  545  544  537  532  531  470  457  438  ...  394
yes                0    0    0    0    0    0    0    0    0    0  ...    0

leiden_2          13   14   15   16   17   18  19  20  21
doublets_manual
no               376  292  271  241  204    0  89   0   0
yes                0    0    0    0    0  109   0  74  17

[2 rows x 22 columns]
Subsetted cells to: (8281, 33538)
Saving processed data

/opt/conda/lib/python3.10/site-packages/anndata/_core/anndata.py:1292: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c

Key: Naive_Vd1_gdT
Value: /home/jupyter/certpro_up1/unharmonized_output/up1_cluster_unharmonize_Naive_Vd1_gdT_2024-09-30.h5ad
AnnData object with n_obs × n_vars = 40534 × 33538
    obs: 'barcodes', 'batch_id', 'cell_name', 'cell_uuid', 'chip_id', 'hto_barcode', 'hto_category', 'n_genes', 'n_mito_umis', 'n_reads', 'n_umis', 'original_barcodes', 'pbmc_sample_id', 'pool_id', 'well_id', 'sample.sampleKitGuid', 'cohort.cohortGuid', 'subject.subjectGuid', 'subject.biologicalSex', 'subject.race', 'subject.ethnicity', 'subject.birthYear', 'sample.visitName', 'sample.drawDate', 'specimens.specimenGuid', 'specimens.specimenType', 'file.id', 'file.batchID', 'subset_grp', 'predicted_doublet', 'doublet_score', 'AIFI_L1', 'AIFI_L1_score', 'AIFI_L2', 'AIFI_L2_score', 'AIFI_L3', 'AIFI_L3_score', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mito', 'log1p_total_counts_mito', 'pct_counts_mito', 'leiden_2'
    uns: 'hvg', 'leiden', 'log1p', 'neighbors', 'pca', 'rank_genes_groups', 'umap'
    obsm: 'X_pca', 'X_umap'
    obsp: 'connectivities', 'distances'
Doublet clusters: ['19']
leiden_2            0     1     2     3     4     5     6     7     8     9  \
doublets_manual
no               3476  3274  3066  3025  2992  2880  2878  2263  2195  1885
yes                 0     0     0     0     0     0     0     0     0     0

leiden_2           10    11    12    13    14    15   16   17   18   19
doublets_manual
no               1872  1671  1636  1626  1609  1497  924  850  677    0
yes                 0     0     0     0     0     0    0    0    0  238
Subsetted cells to: (40534, 33538)
Saving processed data

/opt/conda/lib/python3.10/site-packages/anndata/_core/anndata.py:1292: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  df[key] = c

In [111]:
out_files
out_files

['./deepcleaned_output_2/up1_deepcleaned_Core_CD14_monocyte_2024-10-16.h5ad',
 './deepcleaned_output_2/up1_deepcleaned_KLRF1neg_GZMBpos_CD27neg_EM_CD8_T_cell_2024-10-16.h5ad',
 './deepcleaned_output_2/up1_deepcleaned_CD14pos_cDC2_2024-10-16.h5ad',
 './deepcleaned_output_2/up1_deepcleaned_GZMKpos_CD27pos_EM_CD8_T_cell_2024-10-16.h5ad',
 './deepcleaned_output_2/up1_deepcleaned_ISGpos_MAIT_2024-10-16.h5ad',
 './deepcleaned_output_2/up1_deepcleaned_CD56bright_NK_cell_2024-10-16.h5ad',
 './deepcleaned_output_2/up1_deepcleaned_CM_CD8_T_cell_2024-10-16.h5ad',
 './deepcleaned_output_2/up1_deepcleaned_SOX4pos_naive_CD4_T_cell_2024-10-16.h5ad',
 './deepcleaned_output_2/up1_deepcleaned_CMP_cell_2024-10-16.h5ad',
 './deepcleaned_output_2/up1_deepcleaned_IL1Bpos_CD14_monocyte_2024-10-16.h5ad',
 './deepcleaned_output_2/up1_deepcleaned_Activated_memory_B_cell_2024-10-16.h5ad',
 './deepcleaned_output_2/up1_deepcleaned_ASDC_2024-10-16.h5ad',
 './deepcleaned_output_2/up1_deepcleaned_CD4_MAIT_2024-10-16.h5ad',
 './deepcleaned_output_2/up1_deepcleaned_CD27pos_effector_B_cell_2024-10-16.h5ad',
 './deepcleaned_output_2/up1_deepcleaned_SOX4pos_Vd1_gdT_2024-10-16.h5ad',
 './deepcleaned_output_2/up1_deepcleaned_ISGpos_naive_B_cell_2024-10-16.h5ad',
 './deepcleaned_output_2/up1_deepcleaned_GZMBneg_CD27pos_EM_CD4_T_cell_2024-10-16.h5ad',
 './deepcleaned_output_2/up1_deepcleaned_Plasma_cell_2024-10-16.h5ad',
 './deepcleaned_output_2/up1_deepcleaned_GZMBpos_Vd2_gdT_2024-10-16.h5ad',
 './deepcleaned_output_2/up1_deepcleaned_Platelet_2024-10-16.h5ad',
 './deepcleaned_output_2/up1_deepcleaned_Proliferating_NK_cell_2024-10-16.h5ad',
 './deepcleaned_output_2/up1_deepcleaned_GZMKpos_CD56dim_NK_cell_2024-10-16.h5ad',
 './deepcleaned_output_2/up1_deepcleaned_KLRF1neg_GZMBpos_CD27neg_memory_CD4_T_cell_2024-10-16.h5ad',
 './deepcleaned_output_2/up1_deepcleaned_Early_memory_B_cell_2024-10-16.h5ad',
 './deepcleaned_output_2/up1_deepcleaned_C1Qpos_CD16_monocyte_2024-10-16.h5ad',
 './deepcleaned_output_2/up1_deepcleaned_CM_CD4_T_cell_2024-10-16.h5ad',
 './deepcleaned_output_2/up1_deepcleaned_KLRF1pos_GZMBpos_CD27neg_EM_CD8_T_cell_2024-10-16.h5ad',
 './deepcleaned_output_2/up1_deepcleaned_ISGpos_memory_CD4_T_cell_2024-10-16.h5ad',
 './deepcleaned_output_2/up1_deepcleaned_Core_naive_CD4_T_cell_2024-10-16.h5ad',
 './deepcleaned_output_2/up1_deepcleaned_GZMBneg_CD27neg_EM_CD4_T_cell_2024-10-16.h5ad',
 './deepcleaned_output_2/up1_deepcleaned_cDC1_2024-10-16.h5ad',
 './deepcleaned_output_2/up1_deepcleaned_Memory_CD4_Treg_2024-10-16.h5ad',
 './deepcleaned_output_2/up1_deepcleaned_pDC_2024-10-16.h5ad',
 './deepcleaned_output_2/up1_deepcleaned_CLP_cell_2024-10-16.h5ad',
 './deepcleaned_output_2/up1_deepcleaned_BaEoMaP_cell_2024-10-16.h5ad',
 './deepcleaned_output_2/up1_deepcleaned_ISGpos_naive_CD8_T_cell_2024-10-16.h5ad',
 './deepcleaned_output_2/up1_deepcleaned_Proliferating_T_cell_2024-10-16.h5ad',
 './deepcleaned_output_2/up1_deepcleaned_Core_naive_CD8_T_cell_2024-10-16.h5ad',
 './deepcleaned_output_2/up1_deepcleaned_Core_naive_B_cell_2024-10-16.h5ad',
 './deepcleaned_output_2/up1_deepcleaned_Intermediate_monocyte_2024-10-16.h5ad',
 './deepcleaned_output_2/up1_deepcleaned_Erythrocyte_2024-10-16.h5ad',
 './deepcleaned_output_2/up1_deepcleaned_HLAnegDRhi_cDC2_2024-10-16.h5ad',
 './deepcleaned_output_2/up1_deepcleaned_Core_CD16_monocyte_2024-10-16.h5ad',
 './deepcleaned_output_2/up1_deepcleaned_CD95_memory_B_cell_2024-10-16.h5ad',
 './deepcleaned_output_2/up1_deepcleaned_GZMKneg_CD27pos_EM_CD8_T_cell_2024-10-16.h5ad',
 './deepcleaned_output_2/up1_deepcleaned_ISGpos_CD16_monocyte_2024-10-16.h5ad',
 './deepcleaned_output_2/up1_deepcleaned_Core_memory_B_cell_2024-10-16.h5ad',
 './deepcleaned_output_2/up1_deepcleaned_ISGpos_CD56dim_NK_cell_2024-10-16.h5ad',
 './deepcleaned_output_2/up1_deepcleaned_KLRF1neg_effector_Vd1_gdT_2024-10-16.h5ad',
 './deepcleaned_output_2/up1_deepcleaned_GZMKpos_Vd2_gdT_2024-10-16.h5ad',
 './deepcleaned_output_2/up1_deepcleaned_SOX4pos_naive_CD8_T_cell_2024-10-16.h5ad',
 './deepcleaned_output_2/up1_deepcleaned_GZMKneg_CD56dim_NK_cell_2024-10-16.h5ad',
 './deepcleaned_output_2/up1_deepcleaned_ISGpos_memory_CD8_T_cell_2024-10-16.h5ad',
 './deepcleaned_output_2/up1_deepcleaned_KLRB1pos_memory_CD8_Treg_2024-10-16.h5ad',
 './deepcleaned_output_2/up1_deepcleaned_Type_2_polarized_memory_B_cell_2024-10-16.h5ad',
 './deepcleaned_output_2/up1_deepcleaned_CD27neg_effector_B_cell_2024-10-16.h5ad',
 './deepcleaned_output_2/up1_deepcleaned_Adaptive_NK_cell_2024-10-16.h5ad',
 './deepcleaned_output_2/up1_deepcleaned_CD8_MAIT_2024-10-16.h5ad',
 './deepcleaned_output_2/up1_deepcleaned_KLRB1pos_memory_CD4_Treg_2024-10-16.h5ad',
 './deepcleaned_output_2/up1_deepcleaned_CD8aa_2024-10-16.h5ad',
 './deepcleaned_output_2/up1_deepcleaned_ISGpos_naive_CD4_T_cell_2024-10-16.h5ad',
 './deepcleaned_output_2/up1_deepcleaned_KLRF1pos_effector_Vd1_gdT_2024-10-16.h5ad',
 './deepcleaned_output_2/up1_deepcleaned_ISGpos_cDC2_2024-10-16.h5ad',
 './deepcleaned_output_2/up1_deepcleaned_Naive_CD4_Treg_2024-10-16.h5ad',
 './deepcleaned_output_2/up1_deepcleaned_ILC_2024-10-16.h5ad',
 './deepcleaned_output_2/up1_deepcleaned_GZMKpos_memory_CD4_Treg_2024-10-16.h5ad',
 './deepcleaned_output_2/up1_deepcleaned_Transitional_B_cell_2024-10-16.h5ad',
 './deepcleaned_output_2/up1_deepcleaned_ISGpos_CD14_monocyte_2024-10-16.h5ad',
 './deepcleaned_output_2/up1_deepcleaned_DN_T_cell_2024-10-16.h5ad',
 './deepcleaned_output_2/up1_deepcleaned_Naive_Vd1_gdT_2024-10-16.h5ad']

In [96]:
path = '/home/jupyter/certpro_up1/deepcleaned_output/'

In [97]:
out_files_csv = get_filepaths_with_glob(path, "up1_doublet_meta_*.csv") 
out_files_csv

['/home/jupyter/certpro_up1/deepcleaned_output/up1_doublet_meta_BaEoMaP_cell_2024-10-16.csv',
 '/home/jupyter/certpro_up1/deepcleaned_output/up1_doublet_meta_GZMKpos_CD56dim_NK_cell_2024-10-16.csv',
 '/home/jupyter/certpro_up1/deepcleaned_output/up1_doublet_meta_GZMKneg_CD56dim_NK_cell_2024-10-16.csv',
 '/home/jupyter/certpro_up1/deepcleaned_output/up1_doublet_meta_GZMKpos_memory_CD4_Treg_2024-10-16.csv',
 '/home/jupyter/certpro_up1/deepcleaned_output/up1_doublet_meta_KLRF1pos_effector_Vd1_gdT_2024-10-16.csv',
 '/home/jupyter/certpro_up1/deepcleaned_output/up1_doublet_meta_ISGpos_naive_CD4_T_cell_2024-10-16.csv',
 '/home/jupyter/certpro_up1/deepcleaned_output/up1_doublet_meta_ISGpos_CD56dim_NK_cell_2024-10-16.csv',
 '/home/jupyter/certpro_up1/deepcleaned_output/up1_doublet_meta_Core_memory_B_cell_2024-10-16.csv',
 '/home/jupyter/certpro_up1/deepcleaned_output/up1_doublet_meta_CM_CD8_T_cell_2024-10-16.csv',
 '/home/jupyter/certpro_up1/deepcleaned_output/up1_doublet_meta_ASDC_2024-10-16.csv',
 '/home/jupyter/certpro_up1/deepcleaned_output/up1_doublet_meta_ISGpos_naive_B_cell_2024-10-16.csv',
 '/home/jupyter/certpro_up1/deepcleaned_output/up1_doublet_meta_Core_naive_CD8_T_cell_2024-10-16.csv',
 '/home/jupyter/certpro_up1/deepcleaned_output/up1_doublet_meta_CD27pos_effector_B_cell_2024-10-16.csv',
 '/home/jupyter/certpro_up1/deepcleaned_output/up1_doublet_meta_GZMKpos_Vd2_gdT_2024-10-16.csv',
 '/home/jupyter/certpro_up1/deepcleaned_output/up1_doublet_meta_CLP_cell_2024-10-16.csv',
 '/home/jupyter/certpro_up1/deepcleaned_output/up1_doublet_meta_Naive_Vd1_gdT_2024-10-16.csv',
 '/home/jupyter/certpro_up1/deepcleaned_output/up1_doublet_meta_CD27neg_effector_B_cell_2024-10-16.csv',
 '/home/jupyter/certpro_up1/deepcleaned_output/up1_doublet_meta_cDC1_2024-10-16.csv',
 '/home/jupyter/certpro_up1/deepcleaned_output/up1_doublet_meta_ISGpos_cDC2_2024-10-16.csv',
 '/home/jupyter/certpro_up1/deepcleaned_output/up1_doublet_meta_ILC_2024-10-16.csv',
 '/home/jupyter/certpro_up1/deepcleaned_output/up1_doublet_meta_Adaptive_NK_cell_2024-10-16.csv',
 '/home/jupyter/certpro_up1/deepcleaned_output/up1_doublet_meta_pDC_2024-10-16.csv',
 '/home/jupyter/certpro_up1/deepcleaned_output/up1_doublet_meta_KLRB1pos_memory_CD4_Treg_2024-10-16.csv',
 '/home/jupyter/certpro_up1/deepcleaned_output/up1_doublet_meta_Erythrocyte_2024-10-16.csv',
 '/home/jupyter/certpro_up1/deepcleaned_output/up1_doublet_meta_Platelet_2024-10-16.csv',
 '/home/jupyter/certpro_up1/deepcleaned_output/up1_doublet_meta_CD95_memory_B_cell_2024-10-16.csv',
 '/home/jupyter/certpro_up1/deepcleaned_output/up1_doublet_meta_GZMKpos_CD27pos_EM_CD8_T_cell_2024-10-16.csv',
 '/home/jupyter/certpro_up1/deepcleaned_output/up1_doublet_meta_ISGpos_CD16_monocyte_2024-10-16.csv',
 '/home/jupyter/certpro_up1/deepcleaned_output/up1_doublet_meta_Core_naive_CD4_T_cell_2024-10-16.csv',
 '/home/jupyter/certpro_up1/deepcleaned_output/up1_doublet_meta_Core_CD14_monocyte_2024-10-16.csv',
 '/home/jupyter/certpro_up1/deepcleaned_output/up1_doublet_meta_C1Qpos_CD16_monocyte_2024-10-16.csv',
 '/home/jupyter/certpro_up1/deepcleaned_output/up1_doublet_meta_Early_memory_B_cell_2024-10-16.csv',
 '/home/jupyter/certpro_up1/deepcleaned_output/up1_doublet_meta_Transitional_B_cell_2024-10-16.csv',
 '/home/jupyter/certpro_up1/deepcleaned_output/up1_doublet_meta_SOX4pos_Vd1_gdT_2024-10-16.csv',
 '/home/jupyter/certpro_up1/deepcleaned_output/up1_doublet_meta_CMP_cell_2024-10-16.csv',
 '/home/jupyter/certpro_up1/deepcleaned_output/up1_doublet_meta_Naive_CD4_Treg_2024-10-16.csv',
 '/home/jupyter/certpro_up1/deepcleaned_output/up1_doublet_meta_CD8_MAIT_2024-10-16.csv',
 '/home/jupyter/certpro_up1/deepcleaned_output/up1_doublet_meta_CD8aa_2024-10-16.csv',
 '/home/jupyter/certpro_up1/deepcleaned_output/up1_doublet_meta_GZMBpos_Vd2_gdT_2024-10-16.csv',
 '/home/jupyter/certpro_up1/deepcleaned_output/up1_doublet_meta_DN_T_cell_2024-10-16.csv',
 '/home/jupyter/certpro_up1/deepcleaned_output/up1_doublet_meta_KLRF1pos_GZMBpos_CD27neg_EM_CD8_T_cell_2024-10-16.csv',
 '/home/jupyter/certpro_up1/deepcleaned_output/up1_doublet_meta_GZMBneg_CD27pos_EM_CD4_T_cell_2024-10-16.csv',
 '/home/jupyter/certpro_up1/deepcleaned_output/up1_doublet_meta_ISGpos_memory_CD8_T_cell_2024-10-16.csv',
 '/home/jupyter/certpro_up1/deepcleaned_output/up1_doublet_meta_Type_2_polarized_memory_B_cell_2024-10-16.csv',
 '/home/jupyter/certpro_up1/deepcleaned_output/up1_doublet_meta_KLRF1neg_GZMBpos_CD27neg_memory_CD4_T_cell_2024-10-16.csv',
 '/home/jupyter/certpro_up1/deepcleaned_output/up1_doublet_meta_ISGpos_MAIT_2024-10-16.csv',
 '/home/jupyter/certpro_up1/deepcleaned_output/up1_doublet_meta_ISGpos_naive_CD8_T_cell_2024-10-16.csv',
 '/home/jupyter/certpro_up1/deepcleaned_output/up1_doublet_meta_Intermediate_monocyte_2024-10-16.csv',
 '/home/jupyter/certpro_up1/deepcleaned_output/up1_doublet_meta_GZMBneg_CD27neg_EM_CD4_T_cell_2024-10-16.csv',
 '/home/jupyter/certpro_up1/deepcleaned_output/up1_doublet_meta_SOX4pos_naive_CD8_T_cell_2024-10-16.csv',
 '/home/jupyter/certpro_up1/deepcleaned_output/up1_doublet_meta_IL1Bpos_CD14_monocyte_2024-10-16.csv',
 '/home/jupyter/certpro_up1/deepcleaned_output/up1_doublet_meta_CD14pos_cDC2_2024-10-16.csv',
 '/home/jupyter/certpro_up1/deepcleaned_output/up1_doublet_meta_SOX4pos_naive_CD4_T_cell_2024-10-16.csv',
 '/home/jupyter/certpro_up1/deepcleaned_output/up1_doublet_meta_Plasma_cell_2024-10-16.csv',
 '/home/jupyter/certpro_up1/deepcleaned_output/up1_doublet_meta_Proliferating_NK_cell_2024-10-16.csv',
 '/home/jupyter/certpro_up1/deepcleaned_output/up1_doublet_meta_Memory_CD4_Treg_2024-10-16.csv',
 '/home/jupyter/certpro_up1/deepcleaned_output/up1_doublet_meta_GZMKneg_CD27pos_EM_CD8_T_cell_2024-10-16.csv',
 '/home/jupyter/certpro_up1/deepcleaned_output/up1_doublet_meta_CD56bright_NK_cell_2024-10-16.csv',
 '/home/jupyter/certpro_up1/deepcleaned_output/up1_doublet_meta_ISGpos_memory_CD4_T_cell_2024-10-16.csv',
 '/home/jupyter/certpro_up1/deepcleaned_output/up1_doublet_meta_Core_naive_B_cell_2024-10-16.csv',
 '/home/jupyter/certpro_up1/deepcleaned_output/up1_doublet_meta_Core_CD16_monocyte_2024-10-16.csv',
 '/home/jupyter/certpro_up1/deepcleaned_output/up1_doublet_meta_Activated_memory_B_cell_2024-10-16.csv',
 '/home/jupyter/certpro_up1/deepcleaned_output/up1_doublet_meta_CD4_MAIT_2024-10-16.csv',
 '/home/jupyter/certpro_up1/deepcleaned_output/up1_doublet_meta_HLAnegDRhi_cDC2_2024-10-16.csv',
 '/home/jupyter/certpro_up1/deepcleaned_output/up1_doublet_meta_CM_CD4_T_cell_2024-10-16.csv',
 '/home/jupyter/certpro_up1/deepcleaned_output/up1_doublet_meta_KLRF1neg_effector_Vd1_gdT_2024-10-16.csv',
 '/home/jupyter/certpro_up1/deepcleaned_output/up1_doublet_meta_KLRF1neg_GZMBpos_CD27neg_EM_CD8_T_cell_2024-10-16.csv',
 '/home/jupyter/certpro_up1/deepcleaned_output/up1_doublet_meta_Proliferating_T_cell_2024-10-16.csv',
 '/home/jupyter/certpro_up1/deepcleaned_output/up1_doublet_meta_KLRB1pos_memory_CD8_Treg_2024-10-16.csv',
 '/home/jupyter/certpro_up1/deepcleaned_output/up1_doublet_meta_ISGpos_CD14_monocyte_2024-10-16.csv']

## Export Doublet Metadata

In [98]:
doublet_meta_comb = pd.concat(meta_list)

In [99]:
### check metadata
len(doublet_meta_comb['AIFI_L3'].unique())

70

In [101]:
### export
doublet_meta_comb.to_csv("./deepcleaned_output/up1_scRNA_218_samples_doublet_metadata_all_types.csv")

## Upload Cell Type data to HISE

Finally, we'll use `hisepy.upload.upload_files()` to send a copy of our output to HISE to use for downstream analysis steps.

In [102]:
ss = hisepy.get_study_spaces()
study_space_uuid = ss[0]['id']
title = 'IDE for 06 PBMC L3 Deepclean {d}'.format(d = date.today())
title

'IDE for 06 PBMC L3 Deepclean 2024-10-16'

In [103]:
search_id = element_id()
search_id

'seaborgium-thulium-cerium'

In [104]:
in_files = list(h5ad_uuids.values())
in_files

['7467d353-d8bf-467e-911c-4f759b83caf7',
 'eebab05a-bd3c-4921-8ae3-7345fac966c9',
 '410fc93a-f497-4ea4-81e2-fb8cbdc79a28',
 '6b18c554-64b3-43ae-9514-6ecd18c30f4d',
 '6f5b21ba-d98b-4003-bcf0-30e26a2cc2df',
 '153e45fc-e772-497c-9c4b-e986b7885f01',
 '9acd576f-2271-4ddb-b93e-20f0f63f87af',
 'fcafe12f-3a15-4807-aaea-e93f08445d02',
 '66122892-cddf-4c40-88b2-eaa53b7a6f4c',
 'c9356501-0f48-4590-83ea-34da6dc72b56',
 '0942c4af-20b7-4e2c-a822-a2e8f5044fff',
 'e8dfca7a-e64e-469b-bcc8-6d32a291ffed',
 'caad876a-5c80-4d5a-b245-c6c112b40912',
 'defe9422-db72-4210-b933-6f8919b001c5',
 'b2eec8c5-5bf9-47df-9428-ce26878f017d',
 'e19e9467-2945-4ddc-ac95-1403cc0aee4b',
 'c78d13d1-9580-4b4f-b212-11890ce22544',
 '60c73f54-4210-463f-9ced-920eb73bf924',
 'b8d55475-5c20-4bdb-8980-edaae687d77d',
 '27701eca-1fc6-4d14-9ed6-099e4d1b2668',
 'c5f11c26-23c5-4288-9200-176d57a52ddd',
 'f54f89d0-340d-47a9-bef2-ebcb854c6d72',
 '7ae41ec4-d970-424c-bba3-f5c9debfb3df',
 '48602a6c-9cb1-491d-a2d6-1075bf989e86',
 '91b76287-3228-48ac-9e7d-20e18db64d1c',
 'cd41cf65-774e-4963-b7a9-58c1ece9b4e6',
 'e117a6f9-38fb-4b96-8286-9caa4a6cffeb',
 '740e57fd-9f61-47d0-9aa2-a91ae11eb189',
 'd4c7b35c-bd04-4369-877e-1aa7735c8075',
 '2a2d7da2-9477-49bb-9875-75465025c82a',
 '048f530d-b389-40be-928c-d2abb0edb733',
 '23deb0fc-c3d3-46da-8ac6-32aade5fe560',
 '6d336963-8f41-4f62-9e5c-fa0a37702593',
 '839619aa-e3b2-4547-bd90-4176964e382f',
 '6ba5d0c5-0491-443a-9203-f633736c450f',
 'c446f59a-37ce-4941-becb-532ba52692da',
 'b4f0e6f3-7029-4646-bb76-63e76d1a71f1',
 '073a6180-e0e1-4ea0-9b75-1b1f8fef0584',
 '006eef48-c6be-4358-bf66-26e26c21b18d',
 '202a9e27-0856-48b4-94fe-70ab09bd22b6',
 'f759e068-c4b0-430d-9cd5-8d8575f08da4',
 '8120ab33-5d51-4446-ba0c-463d63566062',
 '13fb0746-6261-46e8-9a48-1c6f274fde7f',
 '2861547e-5606-4554-bcc2-da57161c2bf5',
 '02a52e24-afce-490b-8232-74f193db36a4',
 'c49caec9-53ed-4219-be46-8c534408a10c',
 '64a0bcaf-68f3-48f2-a488-2571f42cbd4d',
 'fb534804-80c4-4d46-b182-32bc7bdc80ca',
 '5b2a49ea-96e6-4d96-962b-12a284cafe54',
 'd566c813-fdec-4583-b125-73d8ddc04648',
 '40df01e8-82ce-4851-a67f-528e91d382c4',
 '7f9d8e3d-e901-4f25-b9f9-49739e83dc3b',
 '587352cf-bfa2-41e5-a19b-7ab531e253de',
 'fb90a3e5-5a30-4e1b-ba66-f70807655747',
 '8b2c297c-2e45-4345-9d99-f6a5f3211994',
 '506d1341-8654-49d2-8e77-572e53836b8c',
 '8a7e22a1-c9f1-4118-a238-4fb38791e87c',
 '23c65764-a97e-444f-95bc-d19cb643da42',
 '09fb23a7-3641-4303-a228-2f1eebdfb7a1',
 'df3092a2-cad7-463e-a462-fde70e9c475b',
 'ba92105f-2f48-419c-9319-d608db735049',
 'cce6b185-ac84-4d63-a9ee-89060ba6390b',
 'c1c0be81-c6b1-4b8b-87f9-133301163297',
 '5eb0cadf-1e90-45fd-aeac-4f5b7a553711',
 '09dd6805-0246-4fee-a3d1-ecc6b3cc3edd',
 'e71668a5-f418-47d1-add1-40540e6b81d3',
 '4aa69351-6c4e-4527-83bd-b34e0e5127e6',
 '4a18d4bc-46a6-4946-8997-ef65d3e7144f',
 '04e4ecdd-4aeb-4f29-9326-94078d132295',
 'ee8e6ae5-848f-476c-b6cb-694dea40c889']

In [105]:
len(in_files)

70

In [110]:
out_files

['./deepcleaned_output_2/up1_deepcleaned_Core_CD14_monocyte_2024-10-16.h5ad',
 './deepcleaned_output_2/up1_deepcleaned_KLRF1neg_GZMBpos_CD27neg_EM_CD8_T_cell_2024-10-16.h5ad',
 './deepcleaned_output_2/up1_deepcleaned_CD14pos_cDC2_2024-10-16.h5ad',
 './deepcleaned_output_2/up1_deepcleaned_GZMKpos_CD27pos_EM_CD8_T_cell_2024-10-16.h5ad',
 './deepcleaned_output_2/up1_deepcleaned_ISGpos_MAIT_2024-10-16.h5ad',
 './deepcleaned_output_2/up1_deepcleaned_CD56bright_NK_cell_2024-10-16.h5ad',
 './deepcleaned_output_2/up1_deepcleaned_CM_CD8_T_cell_2024-10-16.h5ad',
 './deepcleaned_output_2/up1_deepcleaned_SOX4pos_naive_CD4_T_cell_2024-10-16.h5ad',
 './deepcleaned_output_2/up1_deepcleaned_CMP_cell_2024-10-16.h5ad',
 './deepcleaned_output_2/up1_deepcleaned_IL1Bpos_CD14_monocyte_2024-10-16.h5ad',
 './deepcleaned_output_2/up1_deepcleaned_Activated_memory_B_cell_2024-10-16.h5ad',
 './deepcleaned_output_2/up1_deepcleaned_ASDC_2024-10-16.h5ad',
 './deepcleaned_output_2/up1_deepcleaned_CD4_MAIT_2024-10-16.h5ad',
 './deepcleaned_output_2/up1_deepcleaned_CD27pos_effector_B_cell_2024-10-16.h5ad',
 './deepcleaned_output_2/up1_deepcleaned_SOX4pos_Vd1_gdT_2024-10-16.h5ad',
 './deepcleaned_output_2/up1_deepcleaned_ISGpos_naive_B_cell_2024-10-16.h5ad',
 './deepcleaned_output_2/up1_deepcleaned_GZMBneg_CD27pos_EM_CD4_T_cell_2024-10-16.h5ad',
 './deepcleaned_output_2/up1_deepcleaned_Plasma_cell_2024-10-16.h5ad',
 './deepcleaned_output_2/up1_deepcleaned_GZMBpos_Vd2_gdT_2024-10-16.h5ad',
 './deepcleaned_output_2/up1_deepcleaned_Platelet_2024-10-16.h5ad',
 './deepcleaned_output_2/up1_deepcleaned_Proliferating_NK_cell_2024-10-16.h5ad',
 './deepcleaned_output_2/up1_deepcleaned_GZMKpos_CD56dim_NK_cell_2024-10-16.h5ad',
 './deepcleaned_output_2/up1_deepcleaned_KLRF1neg_GZMBpos_CD27neg_memory_CD4_T_cell_2024-10-16.h5ad',
 './deepcleaned_output_2/up1_deepcleaned_Early_memory_B_cell_2024-10-16.h5ad',
 './deepcleaned_output_2/up1_deepcleaned_C1Qpos_CD16_monocyte_2024-10-16.h5ad',
 './deepcleaned_output_2/up1_deepcleaned_CM_CD4_T_cell_2024-10-16.h5ad',
 './deepcleaned_output_2/up1_deepcleaned_KLRF1pos_GZMBpos_CD27neg_EM_CD8_T_cell_2024-10-16.h5ad',
 './deepcleaned_output_2/up1_deepcleaned_ISGpos_memory_CD4_T_cell_2024-10-16.h5ad',
 './deepcleaned_output_2/up1_deepcleaned_Core_naive_CD4_T_cell_2024-10-16.h5ad',
 './deepcleaned_output_2/up1_deepcleaned_GZMBneg_CD27neg_EM_CD4_T_cell_2024-10-16.h5ad',
 './deepcleaned_output_2/up1_deepcleaned_cDC1_2024-10-16.h5ad',
 './deepcleaned_output_2/up1_deepcleaned_Memory_CD4_Treg_2024-10-16.h5ad',
 './deepcleaned_output_2/up1_deepcleaned_pDC_2024-10-16.h5ad',
 './deepcleaned_output_2/up1_deepcleaned_CLP_cell_2024-10-16.h5ad',
 './deepcleaned_output_2/up1_deepcleaned_BaEoMaP_cell_2024-10-16.h5ad',
 './deepcleaned_output_2/up1_deepcleaned_ISGpos_naive_CD8_T_cell_2024-10-16.h5ad',
 './deepcleaned_output_2/up1_deepcleaned_Proliferating_T_cell_2024-10-16.h5ad',
 './deepcleaned_output_2/up1_deepcleaned_Core_naive_CD8_T_cell_2024-10-16.h5ad',
 './deepcleaned_output_2/up1_deepcleaned_Core_naive_B_cell_2024-10-16.h5ad',
 './deepcleaned_output_2/up1_deepcleaned_Intermediate_monocyte_2024-10-16.h5ad',
 './deepcleaned_output_2/up1_deepcleaned_Erythrocyte_2024-10-16.h5ad',
 './deepcleaned_output_2/up1_deepcleaned_HLAnegDRhi_cDC2_2024-10-16.h5ad',
 './deepcleaned_output_2/up1_deepcleaned_Core_CD16_monocyte_2024-10-16.h5ad',
 './deepcleaned_output_2/up1_deepcleaned_CD95_memory_B_cell_2024-10-16.h5ad',
 './deepcleaned_output_2/up1_deepcleaned_GZMKneg_CD27pos_EM_CD8_T_cell_2024-10-16.h5ad',
 './deepcleaned_output_2/up1_deepcleaned_ISGpos_CD16_monocyte_2024-10-16.h5ad',
 './deepcleaned_output_2/up1_deepcleaned_Core_memory_B_cell_2024-10-16.h5ad',
 './deepcleaned_output_2/up1_deepcleaned_ISGpos_CD56dim_NK_cell_2024-10-16.h5ad',
 './deepcleaned_output_2/up1_deepcleaned_KLRF1neg_effector_Vd1_gdT_2024-10-16.h5ad',
 './deepcleaned_output_2/up1_deepcleaned_GZMKpos_Vd2_gdT_2024-10-16.h5ad',
 './deepcleaned_output_2/up1_deepcleaned_SOX4pos_naive_CD8_T_cell_2024-10-16.h5ad',
 './deepcleaned_output_2/up1_deepcleaned_GZMKneg_CD56dim_NK_cell_2024-10-16.h5ad',
 './deepcleaned_output_2/up1_deepcleaned_ISGpos_memory_CD8_T_cell_2024-10-16.h5ad',
 './deepcleaned_output_2/up1_deepcleaned_KLRB1pos_memory_CD8_Treg_2024-10-16.h5ad',
 './deepcleaned_output_2/up1_deepcleaned_Type_2_polarized_memory_B_cell_2024-10-16.h5ad',
 './deepcleaned_output_2/up1_deepcleaned_CD27neg_effector_B_cell_2024-10-16.h5ad',
 './deepcleaned_output_2/up1_deepcleaned_Adaptive_NK_cell_2024-10-16.h5ad',
 './deepcleaned_output_2/up1_deepcleaned_CD8_MAIT_2024-10-16.h5ad',
 './deepcleaned_output_2/up1_deepcleaned_KLRB1pos_memory_CD4_Treg_2024-10-16.h5ad',
 './deepcleaned_output_2/up1_deepcleaned_CD8aa_2024-10-16.h5ad',
 './deepcleaned_output_2/up1_deepcleaned_ISGpos_naive_CD4_T_cell_2024-10-16.h5ad',
 './deepcleaned_output_2/up1_deepcleaned_KLRF1pos_effector_Vd1_gdT_2024-10-16.h5ad',
 './deepcleaned_output_2/up1_deepcleaned_ISGpos_cDC2_2024-10-16.h5ad',
 './deepcleaned_output_2/up1_deepcleaned_Naive_CD4_Treg_2024-10-16.h5ad',
 './deepcleaned_output_2/up1_deepcleaned_ILC_2024-10-16.h5ad',
 './deepcleaned_output_2/up1_deepcleaned_GZMKpos_memory_CD4_Treg_2024-10-16.h5ad',
 './deepcleaned_output_2/up1_deepcleaned_Transitional_B_cell_2024-10-16.h5ad',
 './deepcleaned_output_2/up1_deepcleaned_ISGpos_CD14_monocyte_2024-10-16.h5ad',
 './deepcleaned_output_2/up1_deepcleaned_DN_T_cell_2024-10-16.h5ad',
 './deepcleaned_output_2/up1_deepcleaned_Naive_Vd1_gdT_2024-10-16.h5ad']

In [112]:
hisepy.upload.upload_files(
    files = out_files,
    study_space_id = study_space_uuid,
    title = title,
    input_file_ids = in_files,
    destination = search_id
)

you are trying to upload file_ids... ['./deepcleaned_output_2/up1_deepcleaned_Core_CD14_monocyte_2024-10-16.h5ad', './deepcleaned_output_2/up1_deepcleaned_KLRF1neg_GZMBpos_CD27neg_EM_CD8_T_cell_2024-10-16.h5ad', './deepcleaned_output_2/up1_deepcleaned_CD14pos_cDC2_2024-10-16.h5ad', './deepcleaned_output_2/up1_deepcleaned_GZMKpos_CD27pos_EM_CD8_T_cell_2024-10-16.h5ad', './deepcleaned_output_2/up1_deepcleaned_ISGpos_MAIT_2024-10-16.h5ad', './deepcleaned_output_2/up1_deepcleaned_CD56bright_NK_cell_2024-10-16.h5ad', './deepcleaned_output_2/up1_deepcleaned_CM_CD8_T_cell_2024-10-16.h5ad', './deepcleaned_output_2/up1_deepcleaned_SOX4pos_naive_CD4_T_cell_2024-10-16.h5ad', './deepcleaned_output_2/up1_deepcleaned_CMP_cell_2024-10-16.h5ad', './deepcleaned_output_2/up1_deepcleaned_IL1Bpos_CD14_monocyte_2024-10-16.h5ad', './deepcleaned_output_2/up1_deepcleaned_Activated_memory_B_cell_2024-10-16.h5ad', './deepcleaned_output_2/up1_deepcleaned_ASDC_2024-10-16.h5ad', './deepcleaned_output_2/up1_deepcleaned_CD4_MAIT_2024-10-16.h5ad', './deepcleaned_output_2/up1_deepcleaned_CD27pos_effector_B_cell_2024-10-16.h5ad', './deepcleaned_output_2/up1_deepcleaned_SOX4pos_Vd1_gdT_2024-10-16.h5ad', './deepcleaned_output_2/up1_deepcleaned_ISGpos_naive_B_cell_2024-10-16.h5ad', './deepcleaned_output_2/up1_deepcleaned_GZMBneg_CD27pos_EM_CD4_T_cell_2024-10-16.h5ad', './deepcleaned_output_2/up1_deepcleaned_Plasma_cell_2024-10-16.h5ad', './deepcleaned_output_2/up1_deepcleaned_GZMBpos_Vd2_gdT_2024-10-16.h5ad', './deepcleaned_output_2/up1_deepcleaned_Platelet_2024-10-16.h5ad', './deepcleaned_output_2/up1_deepcleaned_Proliferating_NK_cell_2024-10-16.h5ad', './deepcleaned_output_2/up1_deepcleaned_GZMKpos_CD56dim_NK_cell_2024-10-16.h5ad', './deepcleaned_output_2/up1_deepcleaned_KLRF1neg_GZMBpos_CD27neg_memory_CD4_T_cell_2024-10-16.h5ad', './deepcleaned_output_2/up1_deepcleaned_Early_memory_B_cell_2024-10-16.h5ad', './deepcleaned_output_2/up1_deepcleaned_C1Qpos_CD16_monocyte_2024-10-16.h5ad', './deepcleaned_output_2/up1_deepcleaned_CM_CD4_T_cell_2024-10-16.h5ad', './deepcleaned_output_2/up1_deepcleaned_KLRF1pos_GZMBpos_CD27neg_EM_CD8_T_cell_2024-10-16.h5ad', './deepcleaned_output_2/up1_deepcleaned_ISGpos_memory_CD4_T_cell_2024-10-16.h5ad', './deepcleaned_output_2/up1_deepcleaned_Core_naive_CD4_T_cell_2024-10-16.h5ad', './deepcleaned_output_2/up1_deepcleaned_GZMBneg_CD27neg_EM_CD4_T_cell_2024-10-16.h5ad', './deepcleaned_output_2/up1_deepcleaned_cDC1_2024-10-16.h5ad', './deepcleaned_output_2/up1_deepcleaned_Memory_CD4_Treg_2024-10-16.h5ad', './deepcleaned_output_2/up1_deepcleaned_pDC_2024-10-16.h5ad', './deepcleaned_output_2/up1_deepcleaned_CLP_cell_2024-10-16.h5ad', './deepcleaned_output_2/up1_deepcleaned_BaEoMaP_cell_2024-10-16.h5ad', './deepcleaned_output_2/up1_deepcleaned_ISGpos_naive_CD8_T_cell_2024-10-16.h5ad', './deepcleaned_output_2/up1_deepcleaned_Proliferating_T_cell_2024-10-16.h5ad', './deepcleaned_output_2/up1_deepcleaned_Core_naive_CD8_T_cell_2024-10-16.h5ad', './deepcleaned_output_2/up1_deepcleaned_Core_naive_B_cell_2024-10-16.h5ad', './deepcleaned_output_2/up1_deepcleaned_Intermediate_monocyte_2024-10-16.h5ad', './deepcleaned_output_2/up1_deepcleaned_Erythrocyte_2024-10-16.h5ad', './deepcleaned_output_2/up1_deepcleaned_HLAnegDRhi_cDC2_2024-10-16.h5ad', './deepcleaned_output_2/up1_deepcleaned_Core_CD16_monocyte_2024-10-16.h5ad', './deepcleaned_output_2/up1_deepcleaned_CD95_memory_B_cell_2024-10-16.h5ad', './deepcleaned_output_2/up1_deepcleaned_GZMKneg_CD27pos_EM_CD8_T_cell_2024-10-16.h5ad', './deepcleaned_output_2/up1_deepcleaned_ISGpos_CD16_monocyte_2024-10-16.h5ad', './deepcleaned_output_2/up1_deepcleaned_Core_memory_B_cell_2024-10-16.h5ad', './deepcleaned_output_2/up1_deepcleaned_ISGpos_CD56dim_NK_cell_2024-10-16.h5ad', './deepcleaned_output_2/up1_deepcleaned_KLRF1neg_effector_Vd1_gdT_2024-10-16.h5ad', './deepcleaned_output_2/up1_deepcleaned_GZMKpos_Vd2_gdT_2024-10-16.h5ad', './deepcleaned_output_2/up1_deepcleaned_SOX4pos_naive_CD8_T_cell_2024-10-16.h5ad', './deepcleaned_output_2/up1_deepcleaned_GZMKneg_CD56dim_NK_cell_2024-10-16.h5ad', './deepcleaned_output_2/up1_deepcleaned_ISGpos_memory_CD8_T_cell_2024-10-16.h5ad', './deepcleaned_output_2/up1_deepcleaned_KLRB1pos_memory_CD8_Treg_2024-10-16.h5ad', './deepcleaned_output_2/up1_deepcleaned_Type_2_polarized_memory_B_cell_2024-10-16.h5ad', './deepcleaned_output_2/up1_deepcleaned_CD27neg_effector_B_cell_2024-10-16.h5ad', './deepcleaned_output_2/up1_deepcleaned_Adaptive_NK_cell_2024-10-16.h5ad', './deepcleaned_output_2/up1_deepcleaned_CD8_MAIT_2024-10-16.h5ad', './deepcleaned_output_2/up1_deepcleaned_KLRB1pos_memory_CD4_Treg_2024-10-16.h5ad', './deepcleaned_output_2/up1_deepcleaned_CD8aa_2024-10-16.h5ad', './deepcleaned_output_2/up1_deepcleaned_ISGpos_naive_CD4_T_cell_2024-10-16.h5ad', './deepcleaned_output_2/up1_deepcleaned_KLRF1pos_effector_Vd1_gdT_2024-10-16.h5ad', './deepcleaned_output_2/up1_deepcleaned_ISGpos_cDC2_2024-10-16.h5ad', './deepcleaned_output_2/up1_deepcleaned_Naive_CD4_Treg_2024-10-16.h5ad', './deepcleaned_output_2/up1_deepcleaned_ILC_2024-10-16.h5ad', './deepcleaned_output_2/up1_deepcleaned_GZMKpos_memory_CD4_Treg_2024-10-16.h5ad', './deepcleaned_output_2/up1_deepcleaned_Transitional_B_cell_2024-10-16.h5ad', './deepcleaned_output_2/up1_deepcleaned_ISGpos_CD14_monocyte_2024-10-16.h5ad', './deepcleaned_output_2/up1_deepcleaned_DN_T_cell_2024-10-16.h5ad', './deepcleaned_output_2/up1_deepcleaned_Naive_Vd1_gdT_2024-10-16.h5ad']. Do you truly want to proceed?

(y/n) y

{'trace_id': '656083d3-2214-4ae5-92cb-f7aacc40e6e9',
 'files': ['./deepcleaned_output_2/up1_deepcleaned_Core_CD14_monocyte_2024-10-16.h5ad',
  './deepcleaned_output_2/up1_deepcleaned_KLRF1neg_GZMBpos_CD27neg_EM_CD8_T_cell_2024-10-16.h5ad',
  './deepcleaned_output_2/up1_deepcleaned_CD14pos_cDC2_2024-10-16.h5ad',
  './deepcleaned_output_2/up1_deepcleaned_GZMKpos_CD27pos_EM_CD8_T_cell_2024-10-16.h5ad',
  './deepcleaned_output_2/up1_deepcleaned_ISGpos_MAIT_2024-10-16.h5ad',
  './deepcleaned_output_2/up1_deepcleaned_CD56bright_NK_cell_2024-10-16.h5ad',
  './deepcleaned_output_2/up1_deepcleaned_CM_CD8_T_cell_2024-10-16.h5ad',
  './deepcleaned_output_2/up1_deepcleaned_SOX4pos_naive_CD4_T_cell_2024-10-16.h5ad',
  './deepcleaned_output_2/up1_deepcleaned_CMP_cell_2024-10-16.h5ad',
  './deepcleaned_output_2/up1_deepcleaned_IL1Bpos_CD14_monocyte_2024-10-16.h5ad',
  './deepcleaned_output_2/up1_deepcleaned_Activated_memory_B_cell_2024-10-16.h5ad',
  './deepcleaned_output_2/up1_deepcleaned_ASDC_2024-10-16.h5ad',
  './deepcleaned_output_2/up1_deepcleaned_CD4_MAIT_2024-10-16.h5ad',
  './deepcleaned_output_2/up1_deepcleaned_CD27pos_effector_B_cell_2024-10-16.h5ad',
  './deepcleaned_output_2/up1_deepcleaned_SOX4pos_Vd1_gdT_2024-10-16.h5ad',
  './deepcleaned_output_2/up1_deepcleaned_ISGpos_naive_B_cell_2024-10-16.h5ad',
  './deepcleaned_output_2/up1_deepcleaned_GZMBneg_CD27pos_EM_CD4_T_cell_2024-10-16.h5ad',
  './deepcleaned_output_2/up1_deepcleaned_Plasma_cell_2024-10-16.h5ad',
  './deepcleaned_output_2/up1_deepcleaned_GZMBpos_Vd2_gdT_2024-10-16.h5ad',
  './deepcleaned_output_2/up1_deepcleaned_Platelet_2024-10-16.h5ad',
  './deepcleaned_output_2/up1_deepcleaned_Proliferating_NK_cell_2024-10-16.h5ad',
  './deepcleaned_output_2/up1_deepcleaned_GZMKpos_CD56dim_NK_cell_2024-10-16.h5ad',
  './deepcleaned_output_2/up1_deepcleaned_KLRF1neg_GZMBpos_CD27neg_memory_CD4_T_cell_2024-10-16.h5ad',
  './deepcleaned_output_2/up1_deepcleaned_Early_memory_B_cell_2024-10-16.h5ad',
  './deepcleaned_output_2/up1_deepcleaned_C1Qpos_CD16_monocyte_2024-10-16.h5ad',
  './deepcleaned_output_2/up1_deepcleaned_CM_CD4_T_cell_2024-10-16.h5ad',
  './deepcleaned_output_2/up1_deepcleaned_KLRF1pos_GZMBpos_CD27neg_EM_CD8_T_cell_2024-10-16.h5ad',
  './deepcleaned_output_2/up1_deepcleaned_ISGpos_memory_CD4_T_cell_2024-10-16.h5ad',
  './deepcleaned_output_2/up1_deepcleaned_Core_naive_CD4_T_cell_2024-10-16.h5ad',
  './deepcleaned_output_2/up1_deepcleaned_GZMBneg_CD27neg_EM_CD4_T_cell_2024-10-16.h5ad',
  './deepcleaned_output_2/up1_deepcleaned_cDC1_2024-10-16.h5ad',
  './deepcleaned_output_2/up1_deepcleaned_Memory_CD4_Treg_2024-10-16.h5ad',
  './deepcleaned_output_2/up1_deepcleaned_pDC_2024-10-16.h5ad',
  './deepcleaned_output_2/up1_deepcleaned_CLP_cell_2024-10-16.h5ad',
  './deepcleaned_output_2/up1_deepcleaned_BaEoMaP_cell_2024-10-16.h5ad',
  './deepcleaned_output_2/up1_deepcleaned_ISGpos_naive_CD8_T_cell_2024-10-16.h5ad',
  './deepcleaned_output_2/up1_deepcleaned_Proliferating_T_cell_2024-10-16.h5ad',
  './deepcleaned_output_2/up1_deepcleaned_Core_naive_CD8_T_cell_2024-10-16.h5ad',
  './deepcleaned_output_2/up1_deepcleaned_Core_naive_B_cell_2024-10-16.h5ad',
  './deepcleaned_output_2/up1_deepcleaned_Intermediate_monocyte_2024-10-16.h5ad',
  './deepcleaned_output_2/up1_deepcleaned_Erythrocyte_2024-10-16.h5ad',
  './deepcleaned_output_2/up1_deepcleaned_HLAnegDRhi_cDC2_2024-10-16.h5ad',
  './deepcleaned_output_2/up1_deepcleaned_Core_CD16_monocyte_2024-10-16.h5ad',
  './deepcleaned_output_2/up1_deepcleaned_CD95_memory_B_cell_2024-10-16.h5ad',
  './deepcleaned_output_2/up1_deepcleaned_GZMKneg_CD27pos_EM_CD8_T_cell_2024-10-16.h5ad',
  './deepcleaned_output_2/up1_deepcleaned_ISGpos_CD16_monocyte_2024-10-16.h5ad',
  './deepcleaned_output_2/up1_deepcleaned_Core_memory_B_cell_2024-10-16.h5ad',
  './deepcleaned_output_2/up1_deepcleaned_ISGpos_CD56dim_NK_cell_2024-10-16.h5ad',
  './deepcleaned_output_2/up1_deepcleaned_KLRF1neg_effector_Vd1_gdT_2024-10-16.h5ad',
  './deepcleaned_output_2/up1_deepcleaned_GZMKpos_Vd2_gdT_2024-10-16.h5ad',
  './deepcleaned_output_2/up1_deepcleaned_SOX4pos_naive_CD8_T_cell_2024-10-16.h5ad',
  './deepcleaned_output_2/up1_deepcleaned_GZMKneg_CD56dim_NK_cell_2024-10-16.h5ad',
  './deepcleaned_output_2/up1_deepcleaned_ISGpos_memory_CD8_T_cell_2024-10-16.h5ad',
  './deepcleaned_output_2/up1_deepcleaned_KLRB1pos_memory_CD8_Treg_2024-10-16.h5ad',
  './deepcleaned_output_2/up1_deepcleaned_Type_2_polarized_memory_B_cell_2024-10-16.h5ad',
  './deepcleaned_output_2/up1_deepcleaned_CD27neg_effector_B_cell_2024-10-16.h5ad',
  './deepcleaned_output_2/up1_deepcleaned_Adaptive_NK_cell_2024-10-16.h5ad',
  './deepcleaned_output_2/up1_deepcleaned_CD8_MAIT_2024-10-16.h5ad',
  './deepcleaned_output_2/up1_deepcleaned_KLRB1pos_memory_CD4_Treg_2024-10-16.h5ad',
  './deepcleaned_output_2/up1_deepcleaned_CD8aa_2024-10-16.h5ad',
  './deepcleaned_output_2/up1_deepcleaned_ISGpos_naive_CD4_T_cell_2024-10-16.h5ad',
  './deepcleaned_output_2/up1_deepcleaned_KLRF1pos_effector_Vd1_gdT_2024-10-16.h5ad',
  './deepcleaned_output_2/up1_deepcleaned_ISGpos_cDC2_2024-10-16.h5ad',
  './deepcleaned_output_2/up1_deepcleaned_Naive_CD4_Treg_2024-10-16.h5ad',
  './deepcleaned_output_2/up1_deepcleaned_ILC_2024-10-16.h5ad',
  './deepcleaned_output_2/up1_deepcleaned_GZMKpos_memory_CD4_Treg_2024-10-16.h5ad',
  './deepcleaned_output_2/up1_deepcleaned_Transitional_B_cell_2024-10-16.h5ad',
  './deepcleaned_output_2/up1_deepcleaned_ISGpos_CD14_monocyte_2024-10-16.h5ad',
  './deepcleaned_output_2/up1_deepcleaned_DN_T_cell_2024-10-16.h5ad',
  './deepcleaned_output_2/up1_deepcleaned_Naive_Vd1_gdT_2024-10-16.h5ad']}

In [172]:
import session_info
session_info.show()